### ISSUE TITLE
Recommended batching strategy for large input files

### ISSUE THREAD

**Issue by AlexanderDilthey** [eggnogdb/eggnog-mapper#106]
Hi, I'm trying to map a large protein database (7.1G file size, 37M proteins). I'm currently using the option `-m diamond`, but 1) the process seems to take a very long time (even with 20 CPUs) and b) it crashes because it can't allocate enough memory (on a large memory machine).

Is there any guidance as to what runtimes and memory usages one should expect? Any additional options to speed up the annotation process? And is there a recommended batching strategy for large input files?

**Comment by jhcepas** [comment]
see this: https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2#Setting_up_large_annotation_jobs
