### ISSUE TITLE
the question about eggNOG-mapper result

### ISSUE THREAD

**Issue by quliping** [eggnogdb/eggnog-mapper#108]
I'm a beginner about Bioinformatics. Actually, the 'eggNOG annot' column in the resut contain too many information. How should I classify it? For example, which are related to the DMSP degradation, which are related to the nitrogen cycle...Or some other classification just like those. All the results are mixed, there's no order. Hope for your help.

**Comment by jhcepas** [comment]
eggNOG free text descriptions cannot be used for classification. You can use eggNOG OGs, KEGG, GOs, or any other entry in the output.
