### ISSUE TITLE
Missing names and removing species from OGs

### ISSUE THREAD

**Issue by martaeide** [eggnogdb/eggnog-mapper#110]
Hi,
I recently used EggNOG to map the proteome of a new Atlantic cod (Gadus morhua) assembly, and are left with two questions:
1) In the resulting file, many proteins were left without a predicted name, even though a seed ortholog had been identified. Why?
2) Obviously, the seed ortholog for many of the predicted proteins were cod orthologs (as available in ENSEMBL). However, we would like to reduce bias in the annotation of the new proteome by excluding the ENSEMBL cod proteins in the fish orthology grouping - is this possible? 
Looking forward to hearing from you.

Best,
Marta

**Comment by jhcepas** [comment]
1. Predicted name is only provided is there is a minim consensus of 'common names' among all orthologs
2. Not really. You can restrict annotations to specific clades, but not excluding particular genomes.
