### ISSUE TITLE
eggNOG-mapper doesn't find GO term for SwissProt protein?

### ISSUE THREAD

**Issue by taltman** [eggnogdb/eggnog-mapper#111]
To whom it may concern at EggNOG,

I am trying to gain an understanding for how eggnog-mapper works. I tested it out using SwissProt protein P76113 (see below for FASTA formatted sequence). This protein is annotated with GO term GO:0016491 in UniProt, but the results from eggnog-mapper (see below) state that there were no associated GO terms. I'd assume that eggNOG would be able to retrieve an annotation from a well-annotated protein from SwissProt. Am I misinterpreting the results?

Thanks,

~Tomer

>sp|P76113|CURA_ECOLI NADPH-dependent curcumin reductase OS=Escherichia coli (strain K12) OX=83333 GN=curA PE=1 SV=3
MGQQKQRNRRWVLASRPHGAPVPENFRLEEDDVATPGEGQVLLRTVYLSLDPYMRGRMSD
EPSYSPPVDIGGVMVGGTVSRVVESNHPDYQSGDWVLGYSGWQDYDISSGDDLVKLGDHP
QNPSWSLGVLGMPGFTAYMGLLDIGQPKEGETLVVAAATGPVGATVGQIGKLKGCRVVGV
AGGAEKCRHATEVLGFDVCLDHHADDFAEQLAKACPKGIDIYYENVGGKVFDAVLPLLNT
SARIPVCGLVSSYNATELPPGPDRLPLLMATVLKKRIRLQGFIIAQDYGHRIHEFQREMG
QWVKEDKIHYREEITDGLENAPQTFIGLLKGKNFGKVVIRVAGDD

sp\|P76113\|CURA_ECOLI | ECDH10B_1579 (316385) | 2.5e-243 | 801.5 | YNCB |   | K00001 K00344 K07119 |   | bactNOG[38] | 05CJH@bactNOG 0QI5W@gproNOG 16Q2V@proNOG COG2130@NOG | 05CJH (score:524.750061035) | S | Alcohol dehydrogenase zinc-binding domain protein
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by jhcepas** [comment]
seems to be running well with current version: 
http://eggnog-mapper.embl.de/job_status?jobname=MM_d26f72tp
