### ISSUE TITLE
SIGTERM causes workflow manager to abort

### ISSUE THREAD

**Issue by Irsan88** [eggnogdb/eggnog-mapper#114]
When emapper.py finishes, it terminates the master and worker node and eventually returns the SIGTERM signal (143) (see shutdown_server() method). I use emapper in a workflow system which interprets the non-zero return code as error and therefore aborts any subsequent tasks/jobs/commands. What would be the best way to circumvent? Write a wrapper python script that call emapper as subprocess and catch exceptions?

**Comment by Cantalapiedra** [comment]
We would need to fix this.
Thank you!

**Comment by Cantalapiedra** [comment]
Currently, emapper should finish with code 0 if everything right.

Please, re-open or re-issue if needed.
