### ISSUE TITLE
Method for checking the version of downloaded databases

### ISSUE THREAD

**Issue by jinnjy** [eggnogdb/eggnog-mapper#115]
Hi,

I downloaded eggnog-mapper and used the following command to download the database.

download_eggnog_data.py euk bact arch viruses

I wonder if there is any way to check whether the database I downloaded is version 4.5.1 or 5.0.

Thanks!

**Comment by maxemil** [comment]
Hej jinnjy,
I am not sure if there is a proper way to do this (I am not an eggnog-mapper developer), but you can see the version you downloaded by doing 
`grep DATABASE_VERSION= download_eggnog_data.py` (currently it is using 4.5.1).

hope that helps,
Max

**Comment by maxemil** [comment]
I am actually waiting for that myself! It seems that it's not ready for use with eggnog-mapper yet, so we'll just have to be a bit more patient (maybe @jhcepas can give some more info on this)...

**Comment by jhcepas** [comment]
sorry guys, we are trying to update of eggnog-mapper (offline version) as soon as possible. This depends on eggnog 5.0, which is now officially released, but we still need to adapt the code and make some arrangments. 
For the moment, only 4.5 can be downloaded.

**Comment by jinnjy** [comment]
Thanks @jhcepas and colleagues for the hard work. Hope the 5.0 could be available soon as the data in 5.0 are really much more abundant!

**Comment by jinnjy** [comment]
Hi. I just noticed that the 5.0 and associated eggnog-mapper are available now. I hope that the other threads related to version issues could be also informed and updated when there is a newer version.
