### ISSUE TITLE
failed mapper runs from webservice

### ISSUE THREAD

**Issue by jzrapp** [eggnogdb/eggnog-mapper#116]
Hi @jhcepas 

I'm using the eggNOG mapper v5.0 webservice and all my submitted jobs are failing. I used the same input file previously for a submission to the 4.5 version and it finished quite quickly without any errors. I'm looking for viral signals in my data and therefore wanted to use the newly upgraded version that seems to have greatly improved in terms of viral coverage. Any idea what could have changed?

Thanks for your help!
Josephine

**Comment by davidbio** [comment]
The download_eggnog_data.py script also downloads version 4.5.1. 
Can we change to version 5.0 and use the script, or will it be incompatible with emapper?

**Comment by jhcepas** [comment]
not yet. the diamond and eggnog5 databases are ready for eggnog-mapper v2. We are testing them at the moment.

**Comment by jhcepas** [comment]
The online version of eggnog-mapper v2 is already open for testing: https://eggnog-mapper.embl.de

It uses eggnog-mapper code under master branch
