### ISSUE TITLE
specify path to all databases?

### ISSUE THREAD

**Issue by nick-youngblut** [eggnogdb/eggnog-mapper#117]
As far as I can tell from looking at the documentation, running the commands in the doc, and from looking at the eggnog-mapper code, it appears that at least some of the databases are hard-coded (ie., Line 81 in `eggnog-mapper/eggnogmapper/common.py`). So, if one uses conda, these databases must be located in the conda env directory. This is fine for many situations, but it's not really efficient if multiple users are creating the same eggnog-mapper conda environments on the same server. 

When would this happen??? It can easily happen when multiple users are running `snakemake` pipelines that create the conda environments within the pipeline directory. In this situation, each user running their own instance of the pipeline must download each database into their own conda environment, instead of using a pre-downloaded, centralized database.

It would be very helpful if the user could specify the path to all required databases needed for `emapper.py`. Maybe there is a way, and I've just missed it? I can't find anything in the existing Issues for this repo or in the docs. All I can find is how to specify the dmnd or hmm database path.

**Comment by nick-youngblut** [comment]
Another issue with hard-coding database files in the install directory: software install directories (eg., lib/python2.7/site-packages/data/) are not always setup for large files or large number of files. For instance, on our file server, we have strict inode limits for such directories (to allow for efficient back-ups of important files), and just the `OG_fasta` directory contains ~2 million files. This is why we have all databases (eg., UniRef) stored in a central location on our file server that allows for large numbers of files (and large file sizes). All users can then use this centralized database instead of creating their own local versions of the same databases, which could quickly balloon the number of files on the file server.

**Comment by colinbrislawn** [comment]
The flag `--data_dir` will let you point to the directory that has the databases. They could make this more clear in the docs.
```
$> ls data
eggnog.db
eggnog_proteins.dmnd
hmmdb_levels/
og2level.tsv.gz
OG_fasta/
```
