### ISSUE TITLE
Error running diamond

### ISSUE THREAD

**Issue by 473021677** [eggnogdb/eggnog-mapper#118]
Hi:
    I am using eggnog-mapper on Linux system to conduct functional annotations for my metagenomic scaffolds. The command is "python /data/data/yuanyang/softwares/eggnog-mapper-0.99.3/emapper.py -m diamond --no_annot --no_file_comments --cpu 10 -i AMD_tailings_microbial_no_viruses_scaffolds_proteins.faa -o AMD_tailings_microbial_no_viruses_scaffolds_proteins". But it abort and reports the error"Traceback (most recent call last):
  File "/data/data/yuanyang/softwares/eggnog-mapper-0.99.3/emapper.py", line 1086, in <module>
    main(args)
  File "/data/data/yuanyang/softwares/eggnog-mapper-0.99.3/emapper.py", line 215, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "/data/data/yuanyang/softwares/eggnog-mapper-0.99.3/emapper.py", line 343, in dump_diamond_matches
    raise ValueError('Error running diamond')
ValueError: Error running diamond
". I don't know how this has happened and how to solve it. And the extracted diamond binary file has been moved to a directory contained in my executable search path (PATH environment variable). Thanks.

Sincerely,
Yuan

**Comment by jhcepas** [comment]
You should not use scaffolds as input. Predict ORFs and pass the peptide version in FASTA format to the emapper.py script.

**Comment by 473021677** [comment]
Thanks for your reply very much.
 
 
------------------ Original ------------------
