### ISSUE TITLE
A way to run eggNOG-mapper on single species?

### ISSUE THREAD

**Issue by kvittingseerup** [eggnogdb/eggnog-mapper#120]
Is there a way to run the [eggNOG-mapper](http://eggnogdb.embl.de/#/app/emapper) on a single species? Say if I'm only interested in homology data from H. Sapiens?

**Comment by jhcepas** [comment]
do you mean using only one species as functional source? This is perhaps
possible (need to check current options), but orthology assignments will
still be based on trees containing all other species.

**Comment by kvittingseerup** [comment]
Sounds interesting - thanks for taking time to look into it

**Comment by Cantalapiedra** [comment]
This should be already available using the --target_taxa option (perhaps in combination with --tax_scope)
