### ISSUE TITLE
Remote I/O error when using option --override

### ISSUE THREAD

**Issue by nigiord** [eggnogdb/eggnog-mapper#121]
Hi there,

I've been running a large scale analysis using eggnog-mapper, but I have a strange bug on a single genome. When I use the --override option, I get the following error:

```
#  emapper-1.0.3-3-g3e22728
# ./emapper.py  --annotate_hits_table ./Data/Annot/DKBZ01.emapper.seed_orthologs --output_dir ./Data/Annot --output DKBZ01 --data_dir ./Src/eggnog-mapper/data --cpu 1 --override
Functional annotation of refined hits starts now
500 33.3782749176 14.98 q/s (refinement)
1000 67.0579669476 14.91 q/s (refinement)
Traceback (most recent call last):
  File "Src/eggnog-mapper/emapper.py", line 1009, in <module>
    main(args)
  File "Src/eggnog-mapper/emapper.py", line 244, in main
    annotate_hits_file(args.annotate_hits_table, annot_file, hmm_hits_file, args)
  File "Src/eggnog-mapper/emapper.py", line 749, in annotate_hits_file
    OUT.close()
IOError: [Errno 121] Remote I/O error
```
When I don't, there is no error:
```
#  emapper-1.0.3-3-g3e22728
# ./emapper.py  --annotate_hits_table ./Data/Annot/DKBZ01.emapper.seed_orthologs --output_dir ./Data/Annot --output DKBZ01 --data_dir ./Src/eggnog-mapper/data --cpu 1
Functional annotation of refined hits starts now
500 33.2804460526 15.02 q/s (refinement)
1000 68.0292150974 14.70 q/s (refinement)
 Processed queries:1340 total_time:86.435847044 rate:15.50 q/s
Done
   DKBZ01.emapper.annotations
Total time: 86.4674 secs
```

Attached is the seed_orthologs file in order to reproduce (I suspect the error is related to this file since this is the only genome for which it happens).

[DKBZ01.emapper.seed_orthologs.gz](https://github.com/jhcepas/eggnog-mapper/files/2796891/DKBZ01.emapper.seed_orthologs.gz)

Cheers,
Nils

**Comment by jhcepas** [comment]
thanks, 
do you still get this error with the new eggnog-mapper version? (master branch)
please, re-open issue if so.

**Comment by nigiord** [comment]
Problem seems to be gone. Thanks.

```
$ python2 emapper.py  --annotate_hits_table DKBZ01.emapper.seed_orthologs --output_dir ./ --output DKBZ01 --data_dir /dev/shm/ --cpu 1 --override

#  emapper-1.0.3-40-g41a8498
# ./emapper.py  --annotate_hits_table DKBZ01.emapper.seed_orthologs --output_dir ./ --output DKBZ01 --data_dir /dev/shm/ --cpu 1 --override
Functional annotation of refined hits starts now
500 23.6480967999 21.14 q/s (func. annotation)
1000 50.0461709499 19.98 q/s (func. annotation)
 Processed queries:1340 total_time:63.7400808334 rate:21.02 q/s
Done
   DKBZ01.emapper.annotations
Total time: 64.1183 secs
```

**Comment by nigiord** [comment]
In fact I'm still having the problem on some genomes with the last version on the 5.0 DB... but it does not seem to be related to the `--override` option.

The error:
```python
#  emapper-1.0.3-40-g41a8498
# ./emapper.py  --annotate_hits_table ./Data/Annot/715226_PRJNA43745.emapper.seed_orthologs --output_dir ./Data/Annot --output 715226_PRJNA43745 --data_dir /tmp/ --override
Functional annotation of refined hits starts now
500 6.40820789337 78.02 q/s (func. annotation)
1000 12.3325839043 81.09 q/s (func. annotation)
1500 20.2677810192 74.01 q/s (func. annotation)
2000 25.4786219597 78.50 q/s (func. annotation)
2500 30.2612080574 82.61 q/s (func. annotation)
3000 35.8722670078 83.63 q/s (func. annotation)
3500 42.1854579449 82.97 q/s (func. annotation)
4000 52.5740258694 76.08 q/s (func. annotation)
Traceback (most recent call last):
  File "Src/eggnog-mapper/emapper.py", line 1210, in <module>
    main(args)
  File "Src/eggnog-mapper/emapper.py", line 250, in main
    annotate_hits_file(args.annotate_hits_table, annot_file, hmm_hits_file, args)
  File "Src/eggnog-mapper/emapper.py", line 782, in annotate_hits_file
    OUT.close()
IOError: [Errno 121] Remote I/O error
```
Apparently the problem only arise when closing the file, and happen like 90% of the time on certain seed_orthologs files (if I retry often enough, it works). Attached are the related seed_orthologs file and the result file.

[remote_IO_error_eggnog5.0.zip](https://github.com/eggnogdb/eggnog-mapper/files/3251224/remote_IO_error_eggnog5.0.zip)

The end of the result file is like this:
```
# 4116 queries scanned
# Total time (seconds): 6.92473816872
# Rate: 594.39 q/s
```
So apparently everything was properly written, it's just that for some reasons the file cannot be closed properly.

I think it could be related to the filesystem that is used on the cluster (beegfs) since the problem is gone when I try to write the output on another file system (local disk or /dev/shm). Not sure why it only happens with eggnog-mapper though...

The workaround I use for now: use a local node disk as `--output_dir` then copy the result file where I want on the shared disk space. I hope this will be useful to someone else since I've lost quite a lot of time on this...

Cheers,
Nils

**Comment by jhcepas** [comment]
Hi Nils, 
are you running emapper on a shared filesystem (e.g. NFS)?

**Comment by nigiord** [comment]
Hi @jhcepas ,

Indeed it runs on a shared filesystem (BeeGFS).

**Comment by jhcepas** [comment]
Hi Nils,
was the problem solved moving to local disk?

**Comment by nigiord** [comment]
Yes, as for now I haven't encountered the problem on a local disk.
