### ISSUE TITLE
eggnog-mapper outpt for transcripts

### ISSUE THREAD

**Issue by madhubioinfo** [eggnogdb/eggnog-mapper#122]
when I am using the eggnog mapper for the transcripts i am using it against funog database and its producing following output
TRINITY_DN4657_c1_g1_i1 29850.GGTG_05669T0      9.3e-25 74.0                                    fuNOG[21]       0496X@ascNOG,0IS5P@euNOG,0Q6SA@fuNOG,0UEYT@magNOG,0ZXER@NOG,13ES5@opiNOG,19X59@sordNOG  0Q6SA|2.2e-10|41.2      S       NA
 
Do i need to use --translate option or do i need to identify the ORF's from transcripts use the ORF's for my analysis ? Help needed

**Comment by jhcepas** [comment]
eggnog-mapper expects protein sequences. The translate option will only work if you are providing coding sequences. If you have raw transcripts, you should call ORFs and then translate
