### ISSUE TITLE
Are --usemem or --servermode applicable with -m diamond?

### ISSUE THREAD

**Issue by alexdthomas** [eggnogdb/eggnog-mapper#124]
Hello, 

I really appreciate the logic, efficiency, ease of use, and valuable output of eggnog-mapper.  I'm trying to figure out how to run `emapper.py` most efficiently on many metagenomes on a shared cluster and have repeatedly read the very helpful wiki pages.  

I read on the below page that when using `-m diamond` it is better to split the process in to 1) Homology searches and 2) Orthology and functional annotation and also to split fasta files into ~1 million (1M) gene chunks.  
https://github.com/eggnogdb/eggnog-mapper/wiki/Setting-up-large-scale-analyses 

I also read on the page below that annotation can be sped up using multithreaded memory by specifying the `--usemem` and `--cpu` options for a single file, and `--servermode` if annotating multiple files. 
https://github.com/eggnogdb/eggnog-mapper/wiki/Advanced-usage-and-tips

I was therefore running the below command on each of my samples (I didn't split the samples into 1M genes, but opted to run multiple samples instead...)
`emapper.py -m diamond --no_annot --no_file_comments --cpu 48 -i file.faa -o file --output_dir /path/outdir --usemem`

I was noticing some heavy I/O usage on our shared cluster, which I attributed to loading the diamond database onto multiple nodes simultaneously for each sample.  I then though it would make more sense to load the diamond database using server mode onto a single node and just run each sample sequentially using all the cores on that node.  I then noticed in `emapper.py -h` that it appears `-d` only refers to the database for HMM searches and `--servermode` and `--usemem` would only load hmmpressed databases into memory.

```
--database , -d       specify the target database for sequence searches.
                        Choose among: euk,bact,arch, host:port, or a local
                        hmmpressed database
  --servermode          Loads target database in memory and keeps running in
                        server mode, so another instance of eggnog-mapper can
                        connect to this sever. Auto turns on the --usemem flag
  --usemem              If a local hmmpressed database is provided as target
                        using --db, this flag will allocate the whole database
                        in memory using hmmpgmd. Database will be unloaded
                        after execution.
```

Is the diamond database loaded into memory or is there a way to specify it should be? If I am experiencing heavy I/O issues running multiple samples on the cluster simultaneously wouldn't splitting each sample into 1M genes and running on more nodes make that issue worse?  If so my guess is it would be better to just run each sample sequentially on a single node, but if the diamond database is loaded into memory it would be loaded each time.  Maybe it would be better to only run emapper.py on the node with the diamond database installed? 

Thanks, 
Alex

**Comment by jhcepas** [comment]
Hi Alex,
thanks for your email. some answers below...

> I read on the below page that when using -m diamond it is better to split
> the process in to 1) Homology searches and 2) Orthology and functional
> annotation and also to split fasta files into ~1 million (1M) gene chunks.
>
>
> https://github.com/eggnogdb/eggnog-mapper/wiki/Setting-up-large-scale-analyses
>
> Yes, that's the best strategy when emapper databases (i.e. data/) cannot
be installed locally on each compute node.


> I also read on the page below that annotation can be sped up using
> multithreaded memory by specifying the --usemem and --cpu options for a
> single file, and --servermode if annotating multiple files.
> https://github.com/eggnogdb/eggnog-mapper/wiki/Advanced-usage-and-tips
>
> I was therefore running the below command on each of my samples (I didn't
> split the samples into 1M genes, but opted to run multiple samples
> instead...)
> emapper.py -m diamond --no_annot --no_file_comments --cpu 48 -i file.faa
> -o file --output_dir /path/outdir --usemem
>

diamond cannot benefit from the --usemem option, only hmm-based mapping.
--cpu is, however, fine with both strategies. So, you can remove
--usemem in your  command above.

I was noticing some heavy I/O usage on our shared cluster, which I
> attributed to loading the diamond database onto multiple nodes
> simultaneously for each sample.
>
Yes, when possible, use local temp disk or at least /scratch areas in your
cluster. shared file systems tend to act as bottlenecks when running
emapper.py at large scale.


> I then though it would make more sense to load the diamond database using
> server mode onto a single node and just run each sample sequentially using
> all the cores on that node. I then noticed in emapper.py -h that it
> appears -d only refers to the database for HMM searches and --servermode
> and --usemem would only load hmmpressed databases into memory. Is the
> diamond database loaded into memory or is there a way to specify it should
> be? If I am experiencing heavy I/O issues running multiple samples on the
> cluster simultaneously wouldn't splitting each sample into 1M genes and
> running on more nodes make that issue worse? If so my guess is it would be
> better to just run each sample sequentially on a single node, but if the
> diamond database is loaded into memory it would be loaded each time. Maybe
> it would be better to only run emapper.py on the node with the diamond
> database installed?
>

Diamond cannot use servermode nor usemem options, and disk performance is
critical for that and the subsequent steps.

eggnog-mapper performance is best if installed locally on each computing
node. In other words, the data/ folder lives in a local (fast) disk on
every node. If you can do that, you won't need to split the run in too steps
(mapping, and then annotation), just splitting your input into chunks of
~1M sequences, then running emapper.py normally on each chunk.

hope it helps,
-jaime

**Comment by alexdthomas** [comment]
Hi Jaime, 

Thank you for your prompt and informative reply.  Copying the data/ folder to the compute node seems like a reasonable solution.  I also noticed on line 781 of `emapper.py` it states "No --servermode available for diamond" (suppose it does help to just read the code sometimes).  

Best, 
Alex
