### ISSUE TITLE
diamond database issue

### ISSUE THREAD

**Issue by raw937** [eggnogdb/eggnog-mapper#127]
It can't run diamond as the diamond that I have is different then the database is formatted. Is there a link to the eggnog_proteins.faa that I can use to re-format the diamond database.

#CPU threads: 2
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /data/friesen/bin/eggnog-mapper/emappertmp_dmdn_Dl5pp5
Opening the database...  [0.001921s]
Error: Database was built with a different version of Diamond and is incompatible.
Traceback (most recent call last):
  File "emapper.py", line 1009, in <module>
    main(args)
  File "emapper.py", line 220, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "emapper.py", line 361, in dump_diamond_matches
    raise e
subprocess.CalledProcessError: Command '/home/richard.white3/DIAMOND/diamond blastp -d /data/friesen/bin/eggnog-mapper/data/eggnog_proteins.dmnd -q /data/friesen/bin/eggnog-mapper/test/p53.fa --more-sensitive --threads 2 -e 0.001000 -o /data/friesen/bin/eggnog-mapper/emappertmp_dmdn_Dl5pp5/1178813dd0bd4d859ed25f58d1f74eaa --top 3' returned non-zero exit status 1

**Comment by raw937** [comment]
never mind found the binary. But the other file would be useful to build newer eggnog tables.

**Comment by raw937** [comment]
Wait. I can't figure out how to get the emapper to point to the bin/

**Comment by PlantDr430** [comment]
Hello,

I am also having Diamond issues. I installed the lastest version eggnog-mapper (5.0.0).

```
stephenwyka@bspmgenomics:/data/wyka/final_funannotate/LM470/eggnog$ python /data/wyka/eggnog-mapper/emapper.py -i ../LM470_fun_output/predict_results/Claviceps_purpurea_LM470.proteins.fa --output LM470_euk --cpu 24 -m diamond
/data/wyka/eggnog-mapper/bin/diamond /data/wyka/eggnog-mapper
#  emapper-1.0.3-33-g70ff1ab
# ./emapper.py  -i ../LM470_fun_output/predict_results/Claviceps_purpurea_LM470.proteins.fa --output LM470_euk --cpu 24 -m diamond
  /data/wyka/eggnog-mapper/bin/diamond blastp -d /data/wyka/eggnog-mapper/data/eggnog_proteins.dmnd -q /data/wyka/final_funannotate/LM470/LM470_fun_output/predict_results/Claviceps_purpurea_LM470.proteins.fa --more-sensitive --threads 24 -e 0.001000 -o /data/wyka/final_funannotate/LM470/eggnog/emappertmp_dmdn_4q0IwY/00f2a80bec3049d188f3618ba537c864 --top 3 --query-cover 0 --subject-cover 0
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 24
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /data/wyka/final_funannotate/LM470/eggnog/emappertmp_dmdn_4q0IwY
Opening the database...  [0.000115s]
Error: Database was built with a different version of Diamond and is incompatible.
Traceback (most recent call last):
  File "/data/wyka/eggnog-mapper/emapper.py", line 1211, in <module>
    main(args)
  File "/data/wyka/eggnog-mapper/emapper.py", line 226, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "/data/wyka/eggnog-mapper/emapper.py", line 380, in dump_diamond_matches
    raise e
subprocess.CalledProcessError: Command '/data/wyka/eggnog-mapper/bin/diamond blastp -d /data/wyka/eggnog-mapper/data/eggnog_proteins.dmnd -q /data/wyka/final_funannotate/LM470/LM470_fun_output/predict_results/Claviceps_purpurea_LM470.proteins.fa --more-sensitive --threads 24 -e 0.001000 -o /data/wyka/final_funannotate/LM470/eggnog/emappertmp_dmdn_4q0IwY/00f2a80bec3049d188f3618ba537c864 --top 3 --query-cover 0 --subject-cover 0' returned non-zero exit status 1
stephenwyka@bspmgenomics:/data/wyka/final_funannotate/LM470/eggnog$

```

I checked with diamond dbinfo to check what version the diamond database was created with and the results were that it was created with version "0".

s```
tephenwyka@bspmgenomics:/data/wyka/eggnog-mapper/data$ /data/wyka/eggnog-mapper/bin/diamond dbinfo -d eggnog_proteins.dmnd
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

Database format version = 0
Diamond build = 82
Sequences = 7750086
Letters = 3144616535
stephenwyka@bspmgenomics:/data/wyka/eggnog-mapper/data$
```

**Comment by PlantDr430** [comment]
Hello,

I am also having problems with the diamond database. 

It turns out that the diamond database was created with build 82 

```
stephenwyka@bspmgenomics:/data/wyka/eggnog-mapper/data$ /data/wyka/eggnog-mapper/bin/diamond dbinfo -d eggnog_proteins.dmnd
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

Database format version = 0
Diamond build = 82
Sequences = 7750086
Letters = 3144616535
stephenwyka@bspmgenomics:/data/wyka/eggnog-mapper/data$
```

However, the diamond version that is provided in eggnog-mapper/bin/diamond is build 125 

```
stephenwyka@bspmgenomics:~$ /data/wyka/eggnog-mapper/bin/diamond help
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

Syntax: diamond COMMAND [OPTIONS]

Commands:
makedb  Build DIAMOND database from a FASTA file
blastp  Align amino acid query sequences against a protein reference database
blastx  Align DNA query sequences against a protein reference database
view    View DIAMOND alignment archive (DAA) formatted file
help    Produce help message
version Display version information
getseq  Retrieve sequences from a DIAMOND database file
dbinfo  Print information about a DIAMOND database file
```

**Comment by PlantDr430** [comment]
Working on a temporary fix and hit another snag.

For a temporary fix I started with:

Download and install the binaries for diamond version 0.8.20 (https://github.com/bbuchfink/diamond/releases/tag/v0.8.20)

Then I used the command:

```
/path/to/v0.8.20_diamond_executable getseq -d eggnog_proteins.dmnd > eggnog_proteins.fasta
/eggnog-mapper/bin/diamond makedb --in eggnog_proteins.fasta -d eggnog_proteins.dmnd
```

Essentially, I am pulling the sequences out of the database with the version that was used to create the database that is provided when using download_eggnog_data.py and making a new database in the same eggnog-mapper/data folder with the same name using the updated version of diamond provided in the eggnog-mapper package. 

However, when I run emapper.py with the -m diamond flag I do get a full completion of emapper.seed_ortholog file
[LM470_euk.emapper.seed_ortholog.txt](https://github.com/eggnogdb/eggnog-mapper/files/3180146/LM470_euk.emapper.seed_ortholog.txt)

, but I fail with the annotations step. Below are the errors I get.

```
Processing query chunk 0, reference chunk 1, shape 15, index chunk 3.
Building reference index...  [3.58456s]
Building query index...  [0.043379s]
Building seed filter...  [0.204653s]
Searching alignments...  [1.0571s]
Deallocating buffers...  [0.176491s]
Opening temporary output file...  [0.000136s]
Computing alignments...  [5.36499s]
Deallocating reference...  [0.178909s]
Loading reference sequences...  [2.3e-05s]
Deallocating buffers...  [0.001447s]
Joining output blocks...  [0.150171s]
Deallocating queries...  [0.011379s]
Loading query sequences...  [1.8e-05s]
Closing the input file...  [9e-06s]
Closing the output file...  [2.6e-05s]
Closing the database file...  [6e-06s]
Deallocating taxonomy...  [2e-06s]
Total time = 1000.92s
Reported 23830 pairwise alignments, 23859 HSPs.
7398 queries aligned.
/data/wyka/eggnog-mapper/bin/diamond /data/wyka/eggnog-mapper
#  emapper-1.0.3-33-g70ff1ab
# ./emapper.py  -i ../LM470_fun_output/predict_results/Claviceps_purpurea_LM470.proteins.fa --output LM470_euk --cpu 24 -m diamond
  /data/wyka/eggnog-mapper/bin/diamond blastp -d /data/wyka/eggnog-mapper/data/eggnog_proteins.dmnd -q /data/wyka/final_funannotate/LM470/LM470_fun_output/predict_results/Claviceps_purpurea_LM470.proteins.fa --more-sensitive --threads 24 -e 0.001000 -o /data/wyka/final_funannotate/LM470/eggnog/emappertmp_dmdn_Ae6dvt/d08464e0696846039d599e69b854a8b5 --top 3 --query-cover 0 --subject-cover 0
Functional annotation of refined hits starts now
Traceback (most recent call last):
  File "/data/wyka/eggnog-mapper/emapper.py", line 1211, in <module>
    main(args)
  File "/data/wyka/eggnog-mapper/emapper.py", line 275, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "/data/wyka/eggnog-mapper/emapper.py", line 730, in annotate_hits_file
    for result in pool.imap(annotate_hit_line, iter_hit_lines(seed_orthologs_file, args)):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
KeyError: 'ascNOG'
stephenwyka@bspmgenomics:/data/wyka/final_funannotate/LM470/eggnog$

```

I would like to try and get Diamond to work with eggnog-mapper, as even though the HMM version works it takes about 2 days with 24 cpus to run a genome consisting of 8,000+ genes. And I have 54 genomes to process.

**Comment by jhcepas** [comment]
solved? diamond binary matching the database is distributed with eggnog-mapper.

**Comment by raw937** [comment]
solved.
