### ISSUE TITLE
Update download script to EggNOG v5.0

### ISSUE THREAD

**Issue by mdehollander** [eggnogdb/eggnog-mapper#128]
Earler this month (March 2019) I noticed that EggNOG v5.0 has been released and last week (March 19), the database files for emapper have been uploaded to http://eggnogdb.embl.de/download/emapperdb-5.0.0/

Are there plans to update the download script (https://github.com/eggnogdb/eggnog-mapper/blob/master/download_eggnog_data.py#L7)? Or is this too early, since the online  eggnog-mapper is also under maintenance? Or is there somewhere a dev repo? I haven' t tried if these new db files work with the current eggnogg-mapper scripts.

**Comment by mdehollander** [comment]
I noticed the group and level files are not available yet (`OG_fasta.tar.gz` and `og2level.tsv.gz`)

**Comment by jhcepas** [comment]
it is updated now in master, but we need to clean up and review the code before the official release. thanks.
