### ISSUE TITLE
Output of EggnogMapper

### ISSUE THREAD

**Issue by MichWeb75** [eggnogdb/eggnog-mapper#129]
Hi all,
How do I interpret the IDs in the 10th column of  emapper output file ("Matching_OGs: Comma delimited list of matching eggNOG Orthologous Groups")

05CPZ@bactNOG,0QJ9E@gproNOG,16REH@proNOG,COG1737@NOG ..

Where do I find the IDs 05CPZ ?

**Comment by davidbio** [comment]
Hi,

I wasn't able to find any official documentation about this, but you can construct a URL like the following to find more information on specific orthologous groups.
E.g.:
http://eggnogdb.embl.de/#/app/results?target_nogs=05CPZ

Hope it helps for a start.

**Comment by MichWeb75** [comment]
Thanks for the hint, it means that 05CPZ refers to  ENOG4105CPZ. Remains the prefix ENOG41, 41 the EGGNOG version maybe ?

**Comment by davidbio** [comment]
It's speculation, but it would make sense when you look at the version 5 identifiers:

![image](https://user-images.githubusercontent.com/2159147/55075553-8bf4c680-5093-11e9-9e19-6cc076310f9d.png)

I would wait for an official statement.

**Comment by jhcepas** [comment]
ENOG41 and ENOG50 are tags identifying eggnog version. The actual unique ID of each OG is the 6 subsequent digits. They are unique also between versions.
