### ISSUE TITLE
implement sequence thresholds post orthology prediction

### ISSUE THREAD

**Issue by jhcepas** [eggnogdb/eggnog-mapper#13]
That would allow apply common blast filters on top of orthology restrictions. Currently only taxonomic restrictions can be applied. 

Implementation would consist on phmmer searches occurring always at the NOG level, so all orthologs are evaluated with an alignment. 

potential filters are: 
- [ ] sequence identity
- [ ] query coverage
- [ ] branch distance (average from phylogenies)

**Comment by saketkc** [comment]
Hi! Eggnog-mapper is pretty cool! 
Are there plans to add support for sequence identity/query coverage soon?

**Comment by Cantalapiedra** [comment]
Hi @saketkc ,

Thank you very much for your kind words.
If you are confortable giving a try to the "refactor" branch you will find a --query-cover option. Also, we are about to merge such branch with the "master" branch and hopefully to publish it as a new release.
An option to filter by sequence identity is not available yet, but it would be great to include it soon.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Added --pident to filter results from diamond and mmseqs searches
