### ISSUE TITLE
Error with eggnog mapper

### ISSUE THREAD

**Issue by raw937** [eggnogdb/eggnog-mapper#130]
Command
emapper.py --annotate_hits_table file.emapper.seed_orthologs --no_file_comments -o file_eggnog --cpu 24 

Error:
Output files detected in disk. Use --resume or --override to continue 

Added this:
emapper.py --annotate_hits_table file.emapper.seed_orthologs --no_file_comments -o file_eggnog --cpu 24  **--resume**

Still no output.

**Comment by jhcepas** [comment]
thanks. What version of eggnog-mapper? Latest commit in master?

**Comment by raw937** [comment]
It was a diamond issue. I fixed it.

**Comment by leilax99** [comment]
Hello, can you remember how you fixed it? I meet the same question, thank you!
