### ISSUE TITLE
Can't download bact and arch

### ISSUE THREAD

**Issue by sadvary** [eggnogdb/eggnog-mapper#133]
# python -V
Python 2.7.5

Following the install guide to download bact and arch and getting error...

# ./download_eggnog_data.py bact arch              
/data/eggnog/eggnog-mapper/bin/diamond /data/eggnog/eggnog-mapper
usage: download_eggnog_data.py [-h] [-D] [-y] [-f] [-s] [-q] [--data_dir]
download_eggnog_data.py: error: unrecognized arguments: bact arch

If I run the above without the bact and arch arguments, it does download the annotation and diamond databases.

**Comment by Russel88** [comment]
Had the same problem.
It works if you instead of the development version download the latest release:
wget https://github.com/eggnogdb/eggnog-mapper/archive/1.0.3.tar.gz

**Comment by sadvary** [comment]
Hmm.  I thought I was installing the latest release when I did the below as it says in the Installation page

git clone https://github.com/jhcepas/eggnog-mapper.git

Do the above install the development version?

Looks like I'm using emapper-1.0.3-33-g70ff1ab.

Thanks.

**Comment by Russel88** [comment]
Yes, with git clone you get the latest commit, and therefore the development version.

Two weeks ago they made a change that disabled the HMM downloads. Probably because they are working on an update

**Comment by sadvary** [comment]
Oh OK, thanks!  If we have issues I'll install the 1.0.3 version.  I was able to download the HMMs by hand.

**Comment by jhcepas** [comment]
Hi guys, 
yes, we are updating databases and code to work with eggnog5 data. The current development version should be fully functional using DIAMOND mode, which is our recommended way. HMM mapping was slower and we didn't observe any significant improvement. 
ou can download the two relevant databases from http://eggnog5.embl.de/download/emapperdb-5.0.0/
the download script should also work.

**Comment by sadvary** [comment]
Thanks to both for the replies.
