### ISSUE TITLE
database question

### ISSUE THREAD

**Issue by ucassee** [eggnogdb/eggnog-mapper#137]
Dear developer，
        I use download_eggnog_data.py (version: emapper-1.0.3-3-g3e22728) to download eggnog.db and use this database  to annotate my metagenome with diamond method. I wonder whether this database contains virus protein?
Best regards

**Comment by Cantalapiedra** [comment]
eggNOG databases include Virus proteins, I think since eggNOG 4.5: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4702882/

The last version, eggNOG 5, includes proteins from 2,502 Viruses

http://eggnog5.embl.de/
