### ISSUE TITLE
questions about the KO number and the difference between diamond and HMM search

### ISSUE THREAD

**Issue by sjtuyf** [eggnogdb/eggnog-mapper#138]
Hi，
     Thanks for your time to read my questions. I want to use eggnog to do function analysis of metagenome data. Now I meet some questions, and need your help.
     The first question is about the KO annotation number of eggnog function analysis. It output more than one KO number for each query sequence. I am not sure the differences among these KO number. Do you have an index to differentiate them?  Similarity or e-value? I  also used GhostKOALA of KEGG. GhostKOALA only output one KO number for each query sequence. And the result showed some different, so I am not sure what is the reason.
     The second questions is about the diamond or HMM search in the eggnog-mapper. I want to run the eggnog-mapper by the linux server. And I know the diamond will be faster than the HMM search. I want to use diamond to search the bacteria or archaea database, not to use all database. However, according the description in the document "Note that no target database is required when using DIAMOND", that means I can not use diamond search against specific database, such as bacteria or archaea database, must use the HMM search?
I find I can use the diamond search against some specific database by web search, however, it has the size limitation of query sequences. It bothered me so long time. So what is your suggestion about the function annotation against specific database, using metagenome data of huge sizes.
       At last, I am looking forward to your reply and good advice about your questions.
       Thanks so much.
       Best wishes to you.

Best
yafei

**Comment by Cantalapiedra** [comment]
> Hi，
> Thanks for your time to read my questions. I want to use eggnog to do function analysis of metagenome data. Now I meet some questions, and need your help.

Sorry for the delay answering.

> The first question is about the KO annotation number of eggnog function analysis. It output more than one KO number for each query sequence. I am not sure the differences among these KO number. Do you have an index to differentiate them? Similarity or e-value? I also used GhostKOALA of KEGG. GhostKOALA only output one KO number for each query sequence. And the result showed some different, so I am not sure what is the reason.

I am not familiar with GhostKOALA, but eggnog-mapper could return different KO numbers for different OGs to which the seed ortholog hit by your query belongs to, whereas GhostKOALA seems to use homology for the annotation.


> The second questions is about the diamond or HMM search in the eggnog-mapper. I want to run the eggnog-mapper by the linux server. And I know the diamond will be faster than the HMM search. I want to use diamond to search the bacteria or archaea database, not to use all database. However, according the description in the document "Note that no target database is required when using DIAMOND", that means I can not use diamond search against specific database, such as bacteria or archaea database, must use the HMM search?

Yes, there is no way to limit the search using the diamond mode. However, you could still try to limit the search with --tax_scope and --target_taxa parameters.

> I find I can use the diamond search against some specific database by web search, however, it has the size limitation of query sequences. It bothered me so long time. So what is your suggestion about the function annotation against specific database, using metagenome data of huge sizes.

You could always try to set up your own diamond database, I guess, by downloading the sequences for the specific database of interest.

> At last, I am looking forward to your reply and good advice about your questions.
> Thanks so much.
> Best wishes to you.
> 
> Best
> yafei

Best,
Carlos

**Comment by Cantalapiedra** [comment]
I am closing this.
Please, re-issue if need further help.
