### ISSUE TITLE
Error with eggnog mapper

### ISSUE THREAD

**Issue by AriaLyu** [eggnogdb/eggnog-mapper#139]
Hello,
I am trying to run python emapper.py -i test/p53.fa --output p53_maNOG -m diamond using eggNOG-mapper-v2.
get error: Traceback (most recent call last):
  File "emapper.py", line 1210, in <module>
    main(args)
  File "emapper.py", line 209, in main
    print '# ', get_version()
  File  “path/biosoft/eggnog-mapper/eggnogmapper/common.py", line 130, in get_version
    p = Popen(["git", "describe", "--tags"], stdout=PIPE, stderr=PIPE, cwd=BASE_PATH)
  File "path/miniconda3/envs/eggnogmapper/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "path/miniconda3/envs/eggnogmapper/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
Any ideas on what could fix this?

**Comment by jhcepas** [comment]
Hi @AriaLyu, it looks like a problem at the OS level: e.g. you are trying to read/write from a directory you don't have permissions, or the binary to be executed (e.g. git) does not have execution permissions...
