### ISSUE TITLE
testing databases

### ISSUE THREAD

**Issue by KeteSakharova** [eggnogdb/eggnog-mapper#140]
Hi!
I work as a software developer for MGnify at EMBL EBI. As part of our investigation for new potential pipeline tools we are looking into EggNOG mapper at the moment. We are currently describing your tool in CWL (https://www.commonwl.org/) and potentially we will publish a Docker image on top, which will make it very portable. Also we would like to set up integration tests (like on Travis) as well. The problem is that the databases you are providing are too big and therefore your tool runs for a long time. Ideally we would like to run EggNog on a smaller test databases, only a couple of KBs or MBs in size. Could you please provide smaller databases for testing EggNog with Diamond option?
Thank you

**Comment by jhcepas** [comment]
Hi @KeteSakharova , 
yes, we could provide a test database based on a few eggNOG OGs only. We will post it here when ready

**Comment by rababerladuseladim** [comment]
Hey,
I am strongly interested in testing databases as well. Are there any updates on this?

**Comment by sminot** [comment]
I wanted to add my voice to those requesting a small example database for testing purposes. Thank you!

**Comment by Cantalapiedra** [comment]
Five new files have been created within test/ in the master branch:

test_db.dmnd
test_eggnog.db
test_output.emapper.annotations
test_output.emapper.seed_orthologs
test_queries.fa

"test_queries.fa" are the queries for the test. They can be used with the "-i" option.
"test_db.dmnd" is the Diamond database for the test. It can be used with the "--dmnd_db" option.
"test_eggnog.db" is the eggNOG database for the test. It can be used by copying or linking it to the "data/" directory.
"test_output.emapper.seed_orthologs" are the results from the first mapping step, which can be used to check the results obtained with the test data.
"test_output.emapper.annotations" are the final results, with annotations for the queries, which can be used to check the results obtained with the test data.

Please, re-open issues for new comments.
