### ISSUE TITLE
Add option to keep full diamond output

### ISSUE THREAD

**Issue by colinbrislawn** [eggnogdb/eggnog-mapper#142]
Of the [raw_output_file](https://github.com/eggnogdb/eggnog-mapper/blob/master/emapper.py#L347) made by diamond alignments, only 4 columns are kept. Could we add an option similar to `--keep_mapping_files` that would preserve all the columns of the diamond aliment?

Thanks!

**Comment by jhcepas** [comment]
sounds useful and doable. Will keep it in the todo list. Feel free to send a Pull Request if you have this feature implemented in your side.

**Comment by Cantalapiedra** [comment]
Since v2.1.0, hits file from the search step (Diamond/MMseqs/Hmmer) should be among the output files.
