### ISSUE TITLE
importing eggnog-mapper as a python module

### ISSUE THREAD

**Issue by ghost** [eggnogdb/eggnog-mapper#144]
Hello,

I'd like to use eggnog-mapper in a python script, and I can successfully import it as a module but I can't figure out how to pass arguments to the main function. I thought I could call it like this:

import emapper
emapper.main(input=fastaFile,mode='diamond',output_dir=outDir,output=basename)

But this really doesn't work. Any ideas on what I could do to be able to call emapper from a python script? Subprocess works for me, but it doesn't seem like the best option in this case. 

Any help will be appreciated! Many thanks.

**Comment by Cantalapiedra** [comment]
Could you provide some info about the error you have?
Thank you

**Comment by Cantalapiedra** [comment]
Please, re-submit if still an issue.
