### ISSUE TITLE
wiki annotation columns

### ISSUE THREAD

**Issue by bartns** [eggnogdb/eggnog-mapper#145]
Hi,
Thanks for this great annotation tool!

small comment:
On the wiki of v2 you describe the columns of the output file, number 8 is in there twice. 
So in the end there are 22 columns ;)

**Comment by Cantalapiedra** [comment]
Thank you very much.
I hope this is correct now:

1. query_name
2. seed eggNOG ortholog
3. seed ortholog evalue
4. seed ortholog score
5. Predicted taxonomic group
6. Predicted protein name
7. Gene Ontology terms 
8. EC number
9. KEGG_ko
10. KEGG_Pathway
11. KEGG_Module
12. KEGG_Reaction
13. KEGG_rclass
14. BRITE
15. KEGG_TC
16. CAZy 
17. BiGG Reaction
18. tax_scope: eggNOG taxonomic level used for annotation
19. eggNOG OGs 
20. bestOG (deprecated, use smallest from eggnog OGs)
21. COG Functional Category
22. eggNOG free text description

**Comment by bartns** [comment]
Looks fine by me.  :+1: 
Thanks :)
