### ISSUE TITLE
"NameError at /submit_job" eggNOG-mapper v2 won't run with my data

### ISSUE THREAD

**Issue by korinalb** [eggnogdb/eggnog-mapper#149]
I am attempting to upload a multi-fasta file to eggNOG-mapper v2 but after I click 'submit', the page displays an error:
![eggNOGerror](https://user-images.githubusercontent.com/31319580/63616094-d338a200-c5b4-11e9-8b63-2dc29b82a852.png)

**Comment by Odditude** [comment]
I have the exact same issue. 
I have tried reformatting the fasta file, changing the headers to something simple.  

Has anyone found a solution?

**Comment by korinalb** [comment]
@Odditude do any of your sequences have N's in them? I found that the new version of eggnog-mapper won't accept a multi-fasta file that has any sequences with N's. When I removed those sequences, I stopped getting this error.

**Comment by Odditude** [comment]
@korinalb That turned out to just be the thing. It works now, thanks :)

**Comment by jhcepas** [comment]
@Cantalapiedra , could have a look at this? Maybe forcing a replacement of Ns by Xs...

**Comment by cmarnocha** [comment]
I'm also having this issue, but removing/replacing N's did not seem to solve the problem.

**Comment by amandaclare** [comment]
We see the same issue for sequences containing Ns. Expanding the sections of the Django debug error page suggests that web_return called from emapper.py is not defined, and the 'errormsg' in the 'data' variable says 'Invalid characters detected in nucleotide sequence.' 'scaffold_1341:58955-60809: N' 
The 'letters' variable for me held  {'C', 'T', 'G', 'N', 'A'}.

**Comment by cmarnocha** [comment]
Thank you, that helped me pinpoint the problem nucleotides and their location!

**Comment by Cantalapiedra** [comment]
Hi everyone,

would you mind sending some sequence to reproduce the problem?

Thank you

**Comment by amandaclare** [comment]
[RUG180.orfs.fa.txt](https://github.com/eggnogdb/eggnog-mapper/files/3945266/RUG180.orfs.fa.txt)

**Comment by Cantalapiedra** [comment]
Thank you for the file.
It should work now for nucleotide files with N's.
