### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zhangycbnu** [eggnogdb/eggnog-mapper#151]
Hi there,

When I run eggNOG-Mapper but it crashed with an error sometimes.
python eggnog-mapper-1.0.3/emapper.py -i test/test.fa -d bact --usemem --cpu 10 --ouput test

\# emapper-1.0.3
\# emapper.py -i test/test.fa -d bact --usemem --cpu 10 --ouput test
eggnog-mapper-1.0.3/data/hmmdb_levels/bact_50/bact_50.hmm
[[1;34mLoading server at localhost, port 51500-51501^[[0m
Waiting for server to become ready... localhost 51500
[[1;34mReading idmap /n/home00/yancong/usr/eggnog-mapper-1.0.3/data/hmmdb_levels/bact_50/bact_50.hmm.idmap^[[0m
159207 names loaded
[[32mSequence mapping starts now!^[[0m
[[1;34m Processed queries:10001 total_time:5748.778198 rate:1.74 q/s^[[0m
[[32mHit refinement starts now^[[0m
[[1;34m Processed queries:9743 total_time:907.780759096 rate:10.73 q/s^[[0m
[[32mReading HMM matches^[[0m
[[32mFunctional annotation of refined hits starts now^[[0m
...
Traceback (most recent call last):
  File "\~/eggnog-mapper-1.0.3/emapper.py", line 1001, in <module>
    main(args)
  File "\~/eggnog-mapper-1.0.3/emapper.py", line 261, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "\~/eggnog-mapper-1.0.3/emapper.py", line 693, in annotate_hits_file
    for result in pool.imap(annotate_hit_line, iter_hit_lines(seed_orthologs_file, args)):
  File "\~/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
IndexError: list index out of range

python version: Python 2.7.13

Thanks in advance!

Regards.

**Comment by jhcepas** [comment]
sorry, I cannot reproduce this error. Please try the latest version and, if the problem persists, reopen with some instructions on how to reproduce the problem.
