### ISSUE TITLE
column names are not complete

### ISSUE THREAD

**Issue by xyz1396** [eggnogdb/eggnog-mapper#152]
![image](https://user-images.githubusercontent.com/17617241/63990786-dd5c2280-cb17-11e9-94f2-802476ed62f4.png)
I got the annotation result from the website, and my job link is [link](http://eggnog-mapper.embl.de/job_status?jobname=MM_7ch2lbu9). But it seems that the column names of the annoation file have only 17 items not 22.

**Comment by zoujiayun** [comment]
I also got the same problem, have you solved it?

**Comment by jhcepas** [comment]
sorry, not yet in the online version. The correct header is here https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2#v200
