### ISSUE TITLE
Can the eggnog-mapper annotate the RNA sequences FASTA file?

### ISSUE THREAD

**Issue by Huangyizhong** [eggnogdb/eggnog-mapper#153]
Hi,
    I am so happy to find the eggnog-mapper is useful to conduct the GO and KEGG annotation. I wonder that whether the eggnog-mapper can annotate the RNA sequences or not? Since I found that the eggnog-mapper online can do that. I have tried to do the same work in LINUX with the RNA sequences, but it seems no results? But why?
Hope to receive from you! Thanks so much.
sincerely,
Tony

**Comment by jhcepas** [comment]
yes, you can use CDS sequences as input. emapper will translate assuming they are in the correct frame, etc.
