### ISSUE TITLE
v2 on bioconda

### ISSUE THREAD

**Issue by nick-youngblut** [eggnogdb/eggnog-mapper#154]
Is there a timeline for getting eggnog-mapper v2 on bioconda? Currently, the [version is 1.0.3](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/eggnog-mapper/meta.yaml)

**Comment by jhcepas** [comment]
done. Please keep in mind that this version is diamond-only, no HMMs yet. That was the main reason to delay de release, but it will take a while and we could add that feature in the upcoming version.

**Comment by SilasK** [comment]
Did you thought about using mmseqs instead of diamond and/or hmmer. It should scale much better.

**Comment by jhcepas** [comment]
yes, we are considering several options, including MMseq2. Benchmarks are needed, so it will take a while. 

Anyways, as people were requesting a new release, we decided to release v2.0.0 with basic functionality (but at least based on eggnog v5.0) and build improvements from there.
