### ISSUE TITLE
Is v2 available?

### ISSUE THREAD

**Issue by ganiatgithub** [eggnogdb/eggnog-mapper#155]
Hi,

I followed the installation on the eggnog mapper v2 page:
https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2#Installation
And did the git clone installation.

However, when I run ./emapper.py --version
It gives me: emapper-1.0.3-40-g41a8498

And the mapper also have hmm search available:
diamond search_options:
  --dmnd_db DMND_DB     Path to DIAMOND-compatible database
  --matrix {BLOSUM62,BLOSUM90,BLOSUM80,BLOSUM50,BLOSUM45,PAM250,PAM70,PAM30}
                        Scoring matrix
  --gapopen GAPOPEN     Gap open penalty
  --gapextend GAPEXTEND
                        Gap extend penalty
  --query-cover QUERY_COVER
                        Report only alignments above the given percentage of
                        query cover. Default=0
  --subject-cover SUBJECT_COVER
                        Report only alignments above the given percentage of
                        subject cover. Default=0

To my understanding, hmm is disabled in v2, so what I have should be v1. 

Then, I cannot find installation information for v2.

It's confusing, could you help?

Cheers

**Comment by jhcepas** [comment]
use branch v2 in this repository.

**Comment by ganiatgithub** [comment]
Hello,

Maybe I'm wrong, can you give a link to branch v2?

I used this link for installation, which is supposed to be v2, but it actually installed v1.
https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2#v200
