### ISSUE TITLE
KOs and ECs

### ISSUE THREAD

**Issue by PedroMTQ** [eggnogdb/eggnog-mapper#157]
I was curious how you were collecting the KOs and connecting it to the ECs?
Since I wanted both information, I found it quite useful that eggnog mapper gave it by default, however by looking at a line from my output; e.g.:
> NZ_AMPG01000001.1_2	1229780.BN381_290004	4.3e-40	170.2	Actinobacteria			2.3.1.15	ko:K08591,ko:K19159	ko00561,ko00564,ko01100,ko01110,map00561,map00564,map01100,map01110	M00089	R00851,R09380	RC00004,RC00039,RC00041	ko00000,ko00001,ko00002,ko01000,ko01004,ko02048				Bacteria	2GRC8@201174,COG2161@1,COG2161@2	NA|NA|NA	D	Antitoxin component of a toxin-antitoxin (TA) module)

It doesn't seem like the EC number 2.3.1.15 (https://www.genome.jp/dbget-bin/www_bget?ec:2.3.1.15) actually coincides with the corresponding KOs?

**Comment by tseemann** [comment]
I agree they don't seem related?

https://enzyme.expasy.org/EC/2.3.1.15
Glycerol-3-phosphate O-acyltransferase.

https://www.ncbi.nlm.nih.gov/Structure/cdd/COG2161
Antitoxin component of a toxin-antitoxin (TA) module)

**Comment by jhcepas** [comment]
Hi guys, 
thanks for reporting this and sorry for the slow response times. 
The EC number 2.3.1.15 seems to match the associated KEGG pathways e.g. `map00564,map01100,map01110.` 
  https://www.genome.jp/kegg-bin/show_pathway?map00561+2.3.1.15

the annotation should be comming from at least one ortholog in the eggnog tree that was confidently mapped to a kegg reference sequence.

**Comment by jhcepas** [comment]
I am closing this, please reopen if you find any further inconsistency. 
thanks
