### ISSUE TITLE
Output - several COG categories

### ISSUE THREAD

**Issue by CatiaMM** [eggnogdb/eggnog-mapper#160]
I used the web version of eggnog-mapper for the first time and I am confused with the output.
Sometimes, I have several letters within the column "COG cat". When I was checking for what this meant I found that some COGs or KOGs have more than one category, which would fit, however not always the categories returned by COG id search in http://eggnogdb.embl.de/ match the output of eggnog-mapper. what could be the reason for this? Example below:

KOG1057@1,KOG1057@2759 | NA\|NA\|NA | KLT
-- | -- | --

KOG0915@1,KOG0915@2759 | NA\|NA\|NA | DTZ
-- | -- | --

COG0477@1,KOG1330@2759 | NA\|NA\|NA | EGP
-- | -- | --

Thank you!

**Comment by jhcepas** [comment]
Hi Catia,
yes, three-letters-category means that the KOG is assigned to the three
functional categories they represent.
The examples you show look OK when searching ing eggnog v5 database.
(perhaps you were searching for KOGs in eggnog v4.5?)
