### ISSUE TITLE
predicted_gene_name and predicted protein name

### ISSUE THREAD

**Issue by Jinke233** [eggnogdb/eggnog-mapper#163]
Hello ,I am confused about the name. I noticed one of column name is predicted_gene_name when the version is 1.0 ,but one of column name is predicted protein name, when the version is v2.0 furthermore, my the v2.0 result is Preferred_name.So are they all correct?
Thank you!

**Comment by Jinke233** [comment]
yean,now i know the answer.The gene_name is the same as protein_name,only the formmer is italic,the latter is not italic.

**Comment by Cantalapiedra** [comment]
Sorry for the confusion and inconveniences.
