### ISSUE TITLE
[conda env] eggnog mapper doesn't find diamond 

### ISSUE THREAD

**Issue by SilasK** [eggnogdb/eggnog-mapper#164]
I installed eggnog-mapper v2 using the conda package an run:

```
emapper.py -m diamond --no_annot --no_file_comments             --data_dir /home/kiesers/scratch/Atlas/databases/EggNOGV2 --cpu 8 -i Genecatalog/subsets/genes/subset1.faa             -o Genecatalog/subsets/genes/subset1 --override

```

I got the error:
```
/bin/sh: /home/kiesers/scratch/Atlas/databases/conda_envs/e2c75db2/lib/python2.7/site-packages/bin/diamond: No such file or directory
```

I checked the diamond was installed using conda and is found in:
`/home/kiesers/scratch/Atlas/databases/conda_envs/e2c75db2/bin/diamond/home/kiesers/scratch/Atlas/databases/conda_envs/e2c75db2/bin/diamond`

I think as usually diamond ships with eggnog mapper there is some problem with the path.

**Comment by SilasK** [comment]
#28

**Comment by SilasK** [comment]
I fixed this in my branch. 
No w I have the diamond problem `Error: Invalid option: subject-cover`

**Comment by jhcepas** [comment]
the conda package is handled by bioconda. Not sure what diamond version they are linking, but we built the database with diamond  0.9.24

**Comment by SilasK** [comment]
Yes they  use an old version of diamond.

**Comment by SilasK** [comment]
@jhcepas 
I want to highlight that the [alternative path](https://github.com/SilasK/eggnog-mapper/blob/0f0971b1eb407bd3d25cba2589e11e9df9f84835/eggnogmapper/common.py#L93) in for diamond is not correct either.

**Comment by jhcepas** [comment]
I think the diamond version in this repo (bin/diamond) is the 0.9.24 and should work fine. Did you try it? Maybe a problem with the path in the conda package?

**Comment by SilasK** [comment]
> I fixed this in my branch.
> No w I have the diamond problem `Error: Invalid option: subject-cover`

Ok, I saw there is a diamond.

**Comment by SilasK** [comment]
The problem is during the conda installation, the executable `emapper.py` is placed in 
`condaenv/bin/`

so the absolute path defined in the files.

**Comment by cmfield** [comment]
Could it be line 93 in common.py?

`DIAMOND = pjoin(BASE_PATH, 'bin', 'diamond')
`
The other executables use find_executable() to first check $PATH ..

**Comment by SilasK** [comment]
Yes, and no. I solved it in #165 . Waiting for aproval. 

But the `pjoin(BASE_PATH, 'bin', 'diamond')` is still wrong.

**Comment by VGalata** [comment]
> I think the diamond version in this repo (bin/diamond) is the 0.9.24 and should work fine. Did you try it? Maybe a problem with the path in the conda package?

After fixing the issue with the path, there is a problem with the DIAMOND version. As mentioned above, using the version installed by conda (`0.8.22`) throws the error `Error: Invalid option: subject-cover`. However, I also run into issues when trying to install DIAMOND `0.9.24`.

```bash
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package icu conflicts for:
diamond==0.9.24 -> boost[version='>=1.67.0,<1.67.1.0a0,>=1.68.0,<1.68.1.0a0'] -> py-boost==1.67.0=py27h04863e7_4 -> libboost[version='>=1.67.0,<1.67.1.0a0'] -> icu[version='>=58.2,<59.0a0']
diamond==0.9.24 -> boost[version='>=1.67.0,<1.67.1.0a0,>=1.68.0,<1.68.1.0a0'] -> py-boost==1.67.0=py36h04863e7_4 -> libboost[version='>=1.67.0,<1.67.1.0a0'] -> icu[version='>=58.2,<59.0a0']
Package boost conflicts for:
diamond==0.9.24 -> boost[version='>=1.67.0,<1.67.1.0a0,>=1.68.0,<1.68.1.0a0']
eggnog-mapper==2.0.0 -> diamond=0.8.22 -> boost=1.60
Package diamond conflicts for:
eggnog-mapper==2.0.0 -> diamond=0.8.22
diamond==0.9.24
```

My YAML:
```yaml
channels:
    - conda-forge
    - bioconda
dependencies:
    - diamond==0.9.24
    - eggnog-mapper==2.0.0
```

**Comment by SilasK** [comment]
Yes, the diamond version will be updated, in the conda version  Everything waits on @jhcepas  to do tow clicks an make a new release. I cannot do more.

**Comment by SilasK** [comment]
Keep a look at the [PR](https://github.com/bioconda/bioconda-recipes/pull/18601)
