### ISSUE TITLE
KEGG Release version

### ISSUE THREAD

**Issue by tamatamako** [eggnogdb/eggnog-mapper#168]
Now I'm using eggnog-mapper v2.0.0. And I want to annotate kegg-gene detail information to my eggnog-mapper result. But I cannot find the date when the eggnog database used KEGG for annotation. Where can I find the date of KEGG database which was used in the latest eggnog-mapper tools? I'm sorry, if you have already explained it.

**Comment by Sasakawamiwa** [comment]
Have you solved this problem?
