### ISSUE TITLE
Batch run through bash script fails for some queries

### ISSUE THREAD

**Issue by somakchowdhury** [eggnogdb/eggnog-mapper#169]
Hi @jhcepas , 

First of many thanks for the great tool. Its my go to for all annotations! :) 

I installed eggnog-mapper via a conda install (version = 2.0.0) and subsequently corrected the diamond version to that of the downloaded databases. 
(Side Note: It would be nice to have the version of diamond dbs in the FAQ so that conda based installations could be managed quickly.) 

I then ran emapper.py on a batch of 25 aa.fasta files using the following bash script:

#######BASH-SCRIPT-START########
#!/bin/bash -x

#Make directory to store results

mkdir eggnog_annotation

#Eggnog script for annotation

for F in path/to/directory/with/assSeqs_files/*.fa; do 
  N=$(basename $F .fa) ;
  emapper.py -i $F --output $N --output_dir eggnog_annotation -m diamond --cpu 12 --tax_scope bactNOG ;
done
######BASH-SCRIPT-END######

I get the following error for some of the query(14 of 25) files and not in any predictable order:

`Functional annotation of refined hits starts 
Traceback (most recent call last):
  File "/Users/somakchowdhury/miniconda3/envs/EGGNOG_MAPPERv2/bin/emapper.py", line 1001, in <module>
    main(args)
  File "/Users/somakchowdhury/miniconda3/envs/EGGNOG_MAPPERv2/bin/emapper.py", line 261, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "/Users/somakchowdhury/miniconda3/envs/EGGNOG_MAPPERv2/bin/emapper.py", line 693, in annotate_hits_file
    for result in pool.imap(annotate_hit_line, iter_hit_lines(seed_orthologs_file, args)):
  File "/Users/somakchowdhury/miniconda3/envs/EGGNOG_MAPPERv2/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
TypeError: 'NoneType' object has no attribute '__getitem__'`

For the remaining files the command runs till its logical conclusion. 

Am I doing something wrong interms of flags in the bash script?

Any help is much appreciated! 

Cheers,
Somak

**Comment by Cantalapiedra** [comment]
Sorry for the delay answering.

It is weird that it was failing for some input files and not for others.
Could you provide at least one of the files which is failing?

Thank you
Carlos

**Comment by Cantalapiedra** [comment]
"It would be nice to have the version of diamond dbs in the FAQ so that conda based installations could be managed quickly."

Thank you for the suggestion!

**Comment by marcomeola** [comment]
Any follow-up on this?

**Comment by somakchowdhury** [comment]
Hi @marcomeola and @Cantalapiedra..

Apologies for the late response, I noticed my last run was on symlinks and not original files. (this tells me probably some of the symlinks were broken)

I reran the script but this time pointed it to the original files and not the symlink. 

The process is running as I write. 

Will touch base as soon as the run completes. 

Thanks for following up.

**Comment by somakchowdhury** [comment]
So the run has already failed for one of the files already with the same error message right after it starts Functional annotation. 

```Traceback (most recent call last):
  File "/Users/somakchowdhury/miniconda3/envs/EGGNOG_MAPPERv2/bin/emapper.py", line 1001, in <module>
    main(args)
  File "/Users/somakchowdhury/miniconda3/envs/EGGNOG_MAPPERv2/bin/emapper.py", line 261, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "/Users/somakchowdhury/miniconda3/envs/EGGNOG_MAPPERv2/bin/emapper.py", line 693, in annotate_hits_file
    for result in pool.imap(annotate_hit_line, iter_hit_lines(seed_orthologs_file, args)):
  File "/Users/somakchowdhury/miniconda3/envs/EGGNOG_MAPPERv2/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Here is the link to the example file:
https://www.dropbox.com/s/mfh3bzk7hxoviux/FailedEmapperExample-aaseq.fa?dl=0

**Comment by Cantalapiedra** [comment]
Hi,

Sincerely, I've not been able to run eggnog-mapper 2.0.0 from conda. My apologies.
I tried eggnog-mapper 2.0.1 from conda and it was running ok: i) for the first of your sequences, ii) for the first 500 of your sequences (495 with diamond hit and annotation).

Thus, I can only recommend you to upgrade conda eggnog-mapper to 2.0.1 and run the file you shared above. Maybe the error arises for another sequence beyond the first 500. If so, please tell me so that I can take a look again.

Thank you.

Best,
Carlos

**Comment by marcomeola** [comment]
@Cantalapiedra, I get the error with conda eggnog-mapper version 2.0.1

``` 
Traceback (most recent call last):
  File "/media/ags/Disk1/ags/miniconda3/envs/emapper/bin/emapper.py", line 1213, in <module>
    main(args)
  File "/media/ags/Disk1/ags/miniconda3/envs/emapper/bin/emapper.py", line 279, in main
    dump_orthologs(seed_orthologs_file, orthologs_file, args)
  File "/media/ags/Disk1/ags/miniconda3/envs/emapper/bin/emapper.py", line 812, in dump_orthologs
    for result in pool.imap(find_orthologs_per_hit, iter_hit_lines(seed_orthologs_file, args)):
  File "/media/ags/Disk1/ags/miniconda3/envs/emapper/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
TypeError: 'NoneType' object has no attribute '__getitem__'
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/media/ags/Disk1/ags/miniconda3/envs/emapper/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
``

**Comment by Cantalapiedra** [comment]
Dear @marcomeola ,

thank you for reporting.
Unfortunately, I've not been able to reproduce the problem.
Could you please send me the command line you are running, along with a dataset which is failing?
Also some output lines before the error could perhaps be of help.

Thank you again.

Carlos

**Comment by marcomeola** [comment]
By inspecting the faa files I realized that it happens with faa files with no chronological enumeration of the proteins e.g. jumping from 0001 to 0004 lacking 0002 and 0003. This might cause the error. Need to regenerate them again with prokka

**Comment by somakchowdhury** [comment]
I have run version 2.0.1 on the file that was giving an error. The program has run completely without any error and has processed all the queries in the fasta file provided. I will try this next in a bash script as well to check if it performs as it did for the single file. 

Thank you @Cantalapiedra for the suggestion!

**Comment by somakchowdhury** [comment]
So the bash script failed with the following error message
```
Processing query chunk 0, reference chunk 4, shape 15, index chunk 3.
Building reference index...  [1.28607s]
Building query index...  [0.005745s]
Building seed filter...  [0.051654s]
Searching alignments...  [0.232171s]
Deallocating buffers...  [0.068075s]
Opening temporary output file...  [0.000243s]
Computing alignments...  [1.03152s]
Deallocating reference...  [0.017769s]
Loading reference sequences...  [1.7e-05s]
Deallocating buffers...  [0.000307s]
Joining output blocks...  [0.069261s]
Deallocating queries...  [0.084984s]
Loading query sequences...  [1.2e-05s]
Closing the input file...  [1.6e-05s]
Closing the output file...  [0.000206s]
Closing the database file...  [9e-06s]
Deallocating taxonomy...  [3e-06s]
Total time = 2627.64s
Reported 19771 pairwise alignments, 19774 HSPs.
5006 queries aligned.
Traceback (most recent call last):
  File "/Users/somakchowdhury/miniconda3/envs/EGGNOG_MAPPERv2/bin/emapper.py", line 1213, in <module>
    main(args)
  File "/Users/somakchowdhury/miniconda3/envs/EGGNOG_MAPPERv2/bin/emapper.py", line 226, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "/Users/somakchowdhury/miniconda3/envs/EGGNOG_MAPPERv2/bin/emapper.py", line 350, in dump_diamond_matches
    OUT = open('%s' %seed_orthologs_file, 'w')
IOError: [Errno 2] No such file or directory: 'eggnog_annotation_newRun/PssHS191-aaseq.emapper.seed_orthologs'
```
The command used was the following:
```
for F in CONTIG_db_aaGeneCalls/aa_seqs_out/*.fa; do 
  N=$(basename $F .fa) ;
  emapper.py -i $F --output eggnog_annotation_newRun/$N --output_dir eggnog_annotation_newRun -m diamond --cpu 12 ;
done
```
Suggestions to overcome?

**Comment by Cantalapiedra** [comment]
> th faa files with no chronological enumeration of the proteins e.g. jumping from 0001 to 0004 lacking 0002 and 0003. This might cause the error. Need to regenerate them again w

Please, could you report back once you test this? Thank you

**Comment by Cantalapiedra** [comment]
> So the bash script failed with the following error message
>     OUT = open('%s' %seed_orthologs_file, 'w')
> IOError: [Errno 2] No such file or directory: 'eggnog_annotation_newRun/PssHS191-aaseq.emapper.seed_orthologs'
> ```
> for F in CONTIG_db_aaGeneCalls/aa_seqs_out/*.fa; do 
>   N=$(basename $F .fa) ;
>   emapper.py -i $F --output eggnog_annotation_newRun/$N --output_dir eggnog_annotation_newRun -m diamond --cpu 12 ;
> done
> ```
> 
> Suggestions to overcome?

Hi,

Could you try `--output "$N"` ?

Note that --output option should be a basename, not including directory:
` --output , -o         base name for output files`

Carlos

**Comment by somakchowdhury** [comment]
Thank you @Cantalapiedra (Carlos) That completely solved the problem. I have successfully now run through the batch script with multiple input files. 

Leaving the issue open so Marco's problems are also solved. 

Thanks again!

**Comment by Cantalapiedra** [comment]
Glad it helped!
