### ISSUE TITLE
is pinning diamond=0.8.22 required?

### ISSUE THREAD

**Issue by nextgenusfs** [eggnogdb/eggnog-mapper#171]
Curious about the `diamond=0.8.22` pin in the bioconda package. In my other version of `emapper.py` I just rebuilt the database with a newer version of `diamond`. I realize this gets a little bit difficult because there are now 3 different version of the `diamond` database which are not cross-compatible. Asking because there are some errors with XML output in older versions of diamond that were fixed in v>0.9, thus where I use `eggnog-mapper` in my eukaryotic genome annotation pipeline I need to use a new version of diamond.  Thus currently what is on bioconda conflicts because of the `diamond=0.8.22` pin in eggnog-mapper.

**Comment by jhcepas** [comment]
Hi, 
for version v2.0, diamond 0.9.4 is required. Not sure what are the dependencies in the bioconda package.

**Comment by nextgenusfs** [comment]
Okay it’s still pinned to the old diamond. version. I can update it. Is it specific to that diamond version or just that has to be diamond database version 2?

**Comment by nextgenusfs** [comment]
Okay, so actually looks like for diamond database versions currently something like:
database version 1: < 0.9.10
database version 2: 0.9.10 - 0.9.24
database version 3: > 0.9.24

**Comment by jhcepas** [comment]
I am not sure if diamond versions will break the compatibility with the emapper diamond database. For the current release, we used diamond 0.9.24, but it might work with newer versions.

**Comment by nextgenusfs** [comment]
Yeah I think it will break, ie databases built with 0.9.24 won’t work if using v0.9.25 to run the query, so I will see if we can pin the versions that use database version 2 to the conda recipe.

**Comment by jhcepas** [comment]
I see. thanks a lot

**Comment by nextgenusfs** [comment]
I just recently learned this the “hard way”, so essentially then built a check for checking the database version with the querying version to make sure they are the same. The error is informative however since I’m running diamond in a pipeline the error isn’t always properly captured.

**Comment by nextgenusfs** [comment]
Just for completeness, I double checked the diamond database version from eggnog-mapper 2.0.1:
```
$ diamond dbinfo --db eggnog_proteins.dmnd 
diamond v0.9.21.122 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

Database format version = 2
Diamond build = 125
Sequences = 21841973
Letters = 8413303269
```

**Comment by nextgenusfs** [comment]
Looks like it was just updated yesterday for pinning diamond=0.9.24 https://github.com/bioconda/bioconda-recipes/pull/18601, although might want to make that a little bit more broad depending on response from bbuchfink/diamond#313.

**Comment by bbuchfink** [comment]
Sorry for the incompatibility issues. I will try to keep database format changes to a minimum in the future and maintain backward compatibility. For Bioconda I would not recommend pinning to a particular version but allowing the latest version so your users can benefit quickly from future improvements.

The slowdown in version 0.9.28 is due to the on-the-fly reference masking, which does not matter much for large query files, but will make things slower if you run only one query, especially on only 2 cores. The efficiency of Diamond is best using large query files and as many cores as possible.

**Comment by nextgenusfs** [comment]
So in this case, since the eggnog db was built with v0.9.24 (db version 2), then it is actually compatible with all diamond versions >0.9?  So for Bioconda we should just do something like diamond>=0.9?

**Comment by bbuchfink** [comment]
Yes, that's what I'd recommend.
