### ISSUE TITLE
error with hmmer mode

### ISSUE THREAD

**Issue by sjtuyf** [eggnogdb/eggnog-mapper#174]
Hi,
    I try to use emapper to annotate predicted gene in linux.  I success to run with the parameter '-m diamond'. However, I always failed with the hmmer mode. The command is 'emapper.py -i test.fa --output aaa -d arch', the error shows as below:
Error: Parse failed (sequence file /lustre/home/acct-clslj/clslj/softwares/eggnog/data/OG_fasta/arNOG/02T04.fa):
Line 1: unexpected char 

Traceback (most recent call last):
  File "/lustre/home/acct-clslj/clslj-3/ChangYafei/softwares/eggnog_lns/emapper.py", line 1009, in <module>
    main(args)
  File "/lustre/home/acct-clslj/clslj-3/ChangYafei/softwares/eggnog_lns/emapper.py", line 232, in main
    refine_matches(args.input, seed_orthologs_file, hmm_hits_file, args)
  File "/lustre/home/acct-clslj/clslj-3/ChangYafei/softwares/eggnog_lns/emapper.py", line 533, in refine_matches
    base_tempdir=args.temp_dir)):
  File "/lustre/home/acct-clslj/clslj-3/ChangYafei/softwares/eggnog_lns/emapper.py", line 593, in process_nog_hits_file
    for r in pool.imap(search.refine_hit, cmds):
  File "/lustre/home/acct-clslj/share/mypython2/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value

   Then I check the 02T04.fa file in the path '/lustre/home/acct-clslj/clslj/softwares/eggnog/data/OG_fasta/arNOG/' , the 02T04.fa file is empty. So I delete the 02T04.fa , and run the command 'emapper.py -i test.fa --output bbb -d arch' again. The error information shows as below:

error: Failed to open target sequence database /lustre/home/acct-clslj/clslj/softwares/eggnog/data/OG_fasta/arNOG/02T04.fa for reading

851 17.6939737797 48.10 q/s (refinement)
876 17.6941487789 49.51 q/s (refinement)
901 17.6942698956 50.92 q/s (refinement)
926 17.694414854 52.33 q/s (refinement)
951 17.6945297718 53.75 q/s (refinement)
976 17.6946899891 55.16 q/s (refinement)
1001 17.6948168278 56.57 q/s (refinement)
1026 17.6949248314 57.98 q/s (refinement)
1051 17.6950488091 59.40 q/s (refinement)
1076 17.6951589584 60.81 q/s (refinement)
1101 17.6952807903 62.22 q/s (refinement)
1126 17.6954088211 63.63 q/s (refinement)
1151 17.6955168247 65.04 q/s (refinement)
1176 17.6956470013 66.46 q/s (refinement)
1201 17.6957747936 67.87 q/s (refinement)
1226 18.0834658146 67.80 q/s (refinement)
1251 18.0837168694 69.18 q/s (refinement)
1276 18.0838868618 70.56 q/s (refinement)
1301 18.0840318203 71.94 q/s (refinement)
1326 18.1029567719 73.25 q/s (refinement)
1351 18.1031529903 74.63 q/s (refinement)
1376 19.3977088928 70.94 q/s (refinement)
1401 19.3978879452 72.22 q/s (refinement)
1426 19.3980529308 73.51 q/s (refinement)
1451 20.4652450085 70.90 q/s (refinement)
1476 20.465462923 72.12 q/s (refinement)
1501 20.4656238556 73.34 q/s (refinement)
1526 20.4658629894 74.56 q/s (refinement)
1551 20.4660549164 75.78 q/s (refinement)
Traceback (most recent call last):
  File "/lustre/home/acct-clslj/clslj-3/ChangYafei/softwares/eggnog_lns/emapper.py", line 1009, in <module>
    main(args)
  File "/lustre/home/acct-clslj/clslj-3/ChangYafei/softwares/eggnog_lns/emapper.py", line 232, in main
    refine_matches(args.input, seed_orthologs_file, hmm_hits_file, args)
  File "/lustre/home/acct-clslj/clslj-3/ChangYafei/softwares/eggnog_lns/emapper.py", line 533, in refine_matches
    base_tempdir=args.temp_dir)):
  File "/lustre/home/acct-clslj/clslj-3/ChangYafei/softwares/eggnog_lns/emapper.py", line 593, in process_nog_hits_file
    for r in pool.imap(search.refine_hit, cmds):
  File "/lustre/home/acct-clslj/share/mypython2/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
ValueError: Error running PHMMER

    Is it the problem with the 02T04.fa file in the path of 'data/OG_fasta/arNOG/', or some error exist in my command?
    Hope to get your reply.

Best
Yafei

**Comment by Cantalapiedra** [comment]
Sorry for the delay answering.

The file I have is not empty. Could it be that your download was interrupted or corrupted?
I would try downloading the OG_fasta files again:
http://eggnog5.embl.de/download/emapperdb-4.5.1/OG_fasta.tar.gz

Just in case you need just this file, its contents are:
>269797.Mbar_A0039
MLREKYSEETEKQMKSFFDSLNEKDRRRYAAIEAIKLGHGGQKYISSVLGCHFQTVMAGINEITNGIKTPDDRIRKPGGGKKKIIDTVENIDEVFFEILKDHTAGSSMDEEIKWTNLSFKEISNAFKSRDVNISYIRQVDISFSILFADGDFEMMNPYCV
>990316.MCON_0602
MESEVDYEPFLKALSGADPIQARRFAAAKALELGWGGVSKVSAITGFSRTTINKGIQELESNEDLKPPERLRKPGGGRKRVADREPNLLNDLEKIMEESTAGDPMSLLKWTYKSTYAIAEELQSRGHKVSHDTVRRLLKESGYSLQANRKNLEGKSGPERDTQFRYVSSQAAKFIDAGDPVISVDAKKKELVGNYKNSGRTWRQKGQPELVNVYDFPSKAIGAAIPYGVYDPKRNEGVVNIGKSHNTAEFAVESIRQWWNLVGKYRYAGCKNLLICADGGGSNGSRNRGWKFFLQQLADEIGITITVSHFPPGTSKWNKIEHCMFSFISMNWRGKPLSSYETIIKLIGSTKTKKGLRIEARLDDRDYETGIKILDEDMARLKISVHELYPMWNYSIEPRLTTSK
>990316.MCON_1743
MDNDADYGPFLKALSGADPIQARRFAAAKALEIGWGGVSKVSAITGFSRTTINKGIQELESNEDLKPPERLRKPGGGRKRVADREPNLLNDLEKIMEESTAGDPMSLLKWTYKSTYAIAEELQSRGYKVSHDTVRRLLKESGYSLQANRKNLEGKSGPERDTQFRYVSSQAAKFIDAGDPVISVDAKKKELVGNYKNSGRTWRQKGQPELVNVYDFPSKAIGAAIPYGVYDPKRNEGVVNIGKSHNTAEFAVESIRQWWNLVGKYRYAGCKNLLICADGGGSNGSRNRGWKFFLQQLADEIGITITVSHFPPGTSKWNKIEHCMFSFISMNWRGKPLSSYETIIKLIGSTKTKKGLRIEARLDDRDYETGIKILDEDMARLKISVHELYPMWNYSIEPRLTTSK
>990316.MCON_2860
MDNEADYGPFLKALSGADPIQARRFAAAKALELGWGGVSKVSAITGFSRTTINKGIQELESNEDLKPPERLRKPGGGRKRVADREPNLLNDLEKIMEESTAGDPMSLLKWTYKSTYAIAEELQSRGHKVSHDTVRRLLKESGYSLQANRKNLEGKSGPERDTQFRYVSSQAAKFIDAGDPVISVDAKKKELVGNYKNSGRTWRQKGQPELVNVYDFPSKAIGAAIPYGVYDPKRNEGVVNIGKSHNTAEFAVESIRQWWNLVGKYRYAGCKNLLICADGGGSNGSRNRGWKFFLQQLADEIGITITVSHFPPGTSKWNKIEHCMFSFISMNWRGKPLSSYETIIKLIGSTKTKKGLRIEARLDDRDYETGIKILDEDMARLKISVHELYPMWNYSIEPRLTTSK
>990316.MCON_3317
MESEVDYEPFLKALSGADPIQARRFAAAKALELGWGGVSKVSAITGFSRTTINKGIQELESNEDLKPPERLRKPGGGRKRVADREPNLLNDLEKIMEESTAGDPMSLLKWTYKSTYAIAEELQSRGHKVSHDTVRRLLKESGYSLQANRKNLEGKSGPERDTQFRYVSSQAAKFIDAGDPVISVDAKKKELVGNYKNSGRTWRQKGQPELVNVYDFPSKAIGAAIPYGVYDPKRNEGVVNIGKSHNTAEFAVESIRQWWNLVGKYRYAGCKNLLICADGGGSNGSRNRGWKFFLQQLADEIGITITVSHFPPGTSKWNKIEHCMFSFISMNWRGKPLSSYETIIKLIGSTKTKKGLRIEARLDDRDYETGIKILDEDMARLKISVHELYPMWNYSIEPRLTTSK
