### ISSUE TITLE
Multiple OGs for one protein

### ISSUE THREAD

**Issue by asafpr** [eggnogdb/eggnog-mapper#175]
I ran a protein with eggnog-mapper, both locally and on the webservice and resulted with two potential OG (at @1 and @2 level) and only one of them is correct.
The results are here: http://eggnog-mapper.embl.de/MM_nher5bfa/
Two OGs are COG0073@1,COG0143@1
And BLAST results for the same protein: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=XD4UVPS5015 Showing it's MetG (COG0073)
I suspect it's a bug.

**Comment by jameslz** [comment]
The same case for KEGG annotation fileds, with multi KO annotation, and just one of them id correct.

**Comment by SarahIsme** [comment]
Could someone answer?

**Comment by mlbonatelli** [comment]
Hi, having the same issue here. And some of them are even specified like this:
Two OGs: COG1028@1,COG1028@2 (as you can see, they are the same)
But with COG functional category as: IQ



IQ
--

**Comment by fujch7** [comment]
Somebody help! I have a lot of questions.....
Why there are 4 OGs in column “matching ogs” like **2JIJ5@204432,3Y2GP@57723,COG0477@1,COG0477@2**?
And why multiple letters were found in column COG cat，such as EGP, NU, CH...
Why the same letters correspond to different description?
Why the column best OG was NA NA NA?
![screenshot](https://user-images.githubusercontent.com/61663166/79124651-5c644980-7dcf-11ea-9f56-33a570e8d3ee.png)

**Comment by Cantalapiedra** [comment]
> I ran a protein with eggnog-mapper, both locally and on the webservice and resulted with two potential OG (at @1 and @2 level) and only one of them is correct.
> The results are here: http://eggnog-mapper.embl.de/MM_nher5bfa/
> Two OGs are COG0073@1,COG0143@1
> And BLAST results for the same protein: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Get&RID=XD4UVPS5015 Showing it's MetG (COG0073)
> I suspect it's a bug.

I checked PGN_0281 in http://eggnog5.embl.de/ and the OGs are those. Therefore, I understand is not a bug of eggnog-mapper. Is it something related with the nature of the protein or a bug in eggnog5 annotation? I am not sure. I cannot reach the blast results anymore. Sorry for the delay answering to this.

**Comment by Cantalapiedra** [comment]
> Hi, having the same issue here. And some of them are even specified like this:
> Two OGs: COG1028@1,COG1028@2 (as you can see, they are the same)
> But with COG functional category as: IQ

This is not the same case. Here, the same OG is found at 2 tax levels (root and bacteria), which is common in eggnog DB.

**Comment by Cantalapiedra** [comment]
> Somebody help! I have a lot of questions.....
> Why there are 4 OGs in column “matching ogs” like **2JIJ5@204432,3Y2GP@57723,COG0477@1,COG0477@2**?

Because the protein hit by your query belongs to different OGs.

> And why multiple letters were found in column COG cat，such as EGP, NU, CH...

For example EGP: Amino acid transport and metabolism, Carbohydrate transport and metabolism, Inorganic ion transport and metabolism. I guess the proteins in the OGs are annotated as such.

> Why the same letters correspond to different description?

The description is not directly related with the COG categories, but with the most specific OG. Check 2JKWX at http://eggnog5.embl.de/, for example.

> Why the column best OG was NA NA NA?

This column has been a source of confusion. It is used when eggnog-mapper is/was run in hmmer mode. However, eggnog-mapper v2 (hence, the web version too) uses diamond mode, and this column is always annotated as NA/NA/NA. Sorry for the inconveniences.

> see the screenshot
> Any help will be appreciated
> ![screenshot](https://user-images.githubusercontent.com/61663166/79124651-5c644980-7dcf-11ea-9f56-33a570e8d3ee.png)

I hope this helps

**Comment by Cantalapiedra** [comment]
Please, re-issue if need to discuss any of these questions.
Thank you
