### ISSUE TITLE
Merging results from eggnog and Interproscan

### ISSUE THREAD

**Issue by aberaslop** [eggnogdb/eggnog-mapper#176]
Dear all,
I am annotating a genome using the Maker2 pipeline. In order to add functional annotations, I have used Blast and Interproscan. Maker2 provides a script to merge the results of those two methods. I was wondering if there is a way to merge the results of eggnog to those of blast and Interproscan. Any help is greatly appreciated.

Thanks!

L.

**Comment by Cantalapiedra** [comment]
Sorry, I am not sure how to help with this, and maybe it is too late to answer.
Please, re-issue, sending an example of result from Maker2, if you still need help with this.
