### ISSUE TITLE
Using hmmer eggnog- not using sql.db

### ISSUE THREAD

**Issue by PedroMTQ** [eggnogdb/eggnog-mapper#177]
Using ```m hmmer -d bact``` leads to the error ```Database bact not present. Use download_eggnog_database.py to fetch it``` even though download_eggnog_database.py has been run before and the databases are present.
Even though the eggnog.db sql file is present, when using -d bact the code will check for the individual hmm (e.g. ```data/hmmdb_levels/bact_50/bact_50.hmm```)....
I assume this is not intended behavior? 

Thanks

**Comment by jhcepas** [comment]
Are you using eggnog V2? Then hmmer mode is not available. Use diamond mode
instead.
Thx,
-jaime

**Comment by PedroMTQ** [comment]
Yes, so there is no plan to  keep supporting HMMER even though we should use diamond by default?

**Comment by Cantalapiedra** [comment]
So far, we have not seen much advantage on using the HMMER databases.
Therefore, we are keeping the code and the ability to use the hmmer mode for custom databases, but we are not providing the eggnog databases, and encourage to use diamond instead.
