### ISSUE TITLE
Database version in output

### ISSUE THREAD

**Issue by bartns** [eggnogdb/eggnog-mapper#178]
```
# emapper version: emapper-2.0.1 emapper DB: 2.0
# command: ./emapper.py  -m diamond --cpu 40 -i 2019_filtered_proteins.fasta -o 2019_filtered_proteins
```
The output of emapper states that the V2.0 database is used. However the the download script seems to download version 5.0. 

What is correct?

**Comment by Cantalapiedra** [comment]
If you mean the download script which retrieves the eggNOG database, then the 5.0 refers to the database version, whereas 2.0 refers to the eggNOG-mapper tool version.

**Comment by bartns** [comment]
Thank you for your command. But I mean the part of the first line of the output that says: 

**DB: 2.0**  where as DB stands for DataBase I assume?
(and emapper-**2.0.1** is the is version of the tool) 

So downloading this database:
http://eggnogdb.embl.de/download/emapperdb-5.0.0/eggnog.db.gz

And running the query:
select * from version;

Results in: 2.0

**Comment by Cantalapiedra** [comment]
Yes, you are right.
We hopefully fix this and upload a new version of the database file.
