### ISSUE TITLE
cannot use ./download_eggnog_data.py euk to download euk organiams

### ISSUE THREAD

**Issue by wuxiaopei0509** [eggnogdb/eggnog-mapper#179]
Hi ,When I use ./download_eggnog_data.py to download the euk database, it occurs 'download_eggnog_data.py: error: unrecognized arguments: euk' 
what's this problem ?
Thank you!

**Comment by Cantalapiedra** [comment]
Which version of eggnog-mapper are you using?

**Comment by wuxiaopei0509** [comment]
The latest

**Comment by Cantalapiedra** [comment]
In the latest version, there is a single database, because only Diamond mappings are being used. Therefore, the argument "euk" is unrecognized because it is not used.
I hope this makes sense.

**Comment by pgonzale60** [comment]
That makes sense, but the default mode is hmmer. It would make more sense if hmmer mode was no longer an option.

**Comment by jhcepas** [comment]
yes, you are right that we need to update the defaults. 
eggnog-mapper v2 is still a work in progress (only available from cloning the master branch). If you want to use the official stable version, you can still get it here: https://github.com/eggnogdb/eggnog-mapper/releases
