### ISSUE TITLE
select the best OG 

### ISSUE THREAD

**Issue by MichaelAngelou** [eggnogdb/eggnog-mapper#181]
Hello eggnog mapper developers. 

Thank you for this amazing tool. I recently used Eggnog-mapper v2.0.0  to functionally annotate my 4 metagenomics data. I am now summarizing my data using COG, OG and KO ID however, not all entries in the 'query_name' have a COG, OG and KO ID. So i decided to  summarize the results  based on the "eggNOG OGs".  However, I am not sure  how i can select the best OG. 

I read some post (listed below) here in your  github on how to chose the best OG. In the https://github.com/eggnogdb/eggnog-mapper/issues/42 you recommend to "You could take the most specific one (i.e.the one belonging to the most specific taxonomic level). The last one in
the list if I recall correctly".  Does still hold true to this time? 
Where do I get that data that correspond to the "taxonomic ID" listed before the "@" in the "eggNOG OGs" column in the text file. 
[cog_Hamb89_right full data.xlsx](https://github.com/eggnogdb/eggnog-mapper/files/4162946/cog_Hamb89_right.full.data.xlsx)

https://github.com/eggnogdb/eggnog-mapper/issues/170
https://github.com/eggnogdb/eggnog-mapper/issues/146
https://github.com/eggnogdb/eggnog-mapper/issues/42

Any clarification would be appreciated. Thank you. 

Here's some examples of the results (sheet name: cog_Hamb711_right original).

**Comment by Cantalapiedra** [comment]
Hi,

sorry for the delay.
Could "best_tax_level" be the column you are looking for?
It should be giving you the most specific taxon from your list of "eggNOG OGs"

**Comment by Cantalapiedra** [comment]
Please, re-issue if need to discuss about this.
Thank you
