### ISSUE TITLE
Functional annotation error

### ISSUE THREAD

**Issue by slaperriere** [eggnogdb/eggnog-mapper#182]
Hello, 

I am getting an error when running the following: 

`python ~/software/src/eggnog-mapper/emapper.py -m diamond \
                                                             --cpu ${threads} \
                                                             --dmnd_db $EGGNOG_diamond_DB \
                                                             --output ${prefix}_emapper \
                                                             --output_dir ${OUTPUT_GENOME_DIR} \
                                                             --report_orthologs \
                                                             -i ${prodigal_faa} \
                                                             --override`

The error is:

`Functional annotation of refined hits starts now
Traceback (most recent call last):
  File "/home/shengwei/software/src/eggnog-mapper/emapper.py", line 1213, in <module>
    main(args)
  File "/home/shengwei/software/src/eggnog-mapper/emapper.py", line 275, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "/home/shengwei/software/src/eggnog-mapper/emapper.py", line 753, in annotate_hits_file
    print >>ORTHOLOGS, '\t'.join(map(str, (query_name, ','.join(orthologs))))
TypeError: can only join an iterable`

Do you know what could be causing this error?  Thank you!

**Comment by Cantalapiedra** [comment]
Thank you for reporting this error.
The "report_orthologs" option should be working fine in the next version, which is currently being developed in the "refactor" branch.

**Comment by selveyad** [comment]
Any ETA on a patch for the current version or update to the next version?

**Comment by Cantalapiedra** [comment]
If you need that feature you could try the version under the "refactor" branch, which is currently under development.
