### ISSUE TITLE
TypeError: can only join an iterable

### ISSUE THREAD

**Issue by housw** [eggnogdb/eggnog-mapper#184]
Hi, 

I got the following error, but still got the `.annotations`, `.annotations.orthologs` and `.seed_orthologs` files. 

```
... 
Reported 434089 pairwise alignments, 434643 HSPs.
86542 queries aligned.
Functional annotation of refined hits starts now
Traceback (most recent call last):
  File "/home/shengwei/software/src/eggnog-mapper/emapper.py", line 1213, in <module>
    main(args)
  File "/home/shengwei/software/src/eggnog-mapper/emapper.py", line 275, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "/home/shengwei/software/src/eggnog-mapper/emapper.py", line 753, in annotate_hits_file
    print >>ORTHOLOGS, '\t'.join(map(str, (query_name, ','.join(orthologs))))
TypeError: can only join an iterable
```

Any idea? 

Thanks!

**Comment by sestaton** [comment]
This appears to be the same issue as #182. 

I'm having this problem as well. I think the issue lies in the call to `--report_orthologs` and/or `--predict_ortho`.  

Unfortunately that's all I can say about it right now but I'll update if I find a solution.

**Comment by housw** [comment]
Yes, just realized our colleague Sarah had posted this issue, I'll close this one. 

Thanks for your response.

**Comment by jlli6t** [comment]
I got the same issue,  it looks like because the call of --report_orthologs though
