### ISSUE TITLE
Error when downloading database

### ISSUE THREAD

**Issue by MeiyuanJi** [eggnogdb/eggnog-mapper#186]
Hello,

I encounter a problem when using the command "./downlad_eggnog_data.py". Does anyone have the same problem?

I just do the installation according to the document. 

<img width="717" alt="Screen Shot 2020-03-01 at 11 50 27 AM" src="https://user-images.githubusercontent.com/33933620/75631778-df7c6800-5bb2-11ea-9045-84e2dd918aed.png">

Need your help. Thans in advance.

Meiyuan

**Comment by jhcepas** [comment]
I cannot see the error in your screenshot. Could it be you are using Python3?

**Comment by Cantalapiedra** [comment]
Please, re-submit the issue with the eggnog-mapper and python versions being used.

Thank you

Best,
Carlos
