### ISSUE TITLE
Taxonomy IDs

### ISSUE THREAD

**Issue by clairemcwhite** [eggnogdb/eggnog-mapper#187]
Hi, 

Happy users of eggnog mapper here. 

It would be nice to clarify in the eggnogmapper instructions that the Taxonomic identifier number in the .annotations file (ex. XXXXX@2579, XXXXX@2, etc) corresponds to an NCBI [taxid](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=2759&lvl=3&lin=f&keep=1&srchmode=1&unlock) taxonomy ID.

This question of what that number is, and what number corresponds to what taxonomic level keeps coming up for us. 

Thanks, 
Claire

**Comment by jhcepas** [comment]
Hi Claire!
you are totally right. We definitely need to work on the documentation @Cantalapiedra
