### ISSUE TITLE
Sometimes error: ImportError: No module named ete3

### ISSUE THREAD

**Issue by jlli6t** [eggnogdb/eggnog-mapper#189]
Hi,

I am using eggnog-mapper-v2.0.0 with python 2.7.5, I encountered an error message like No moudle named ete3. I am pretty sure that I have installed package ete3, and I ran succefully sometimes.

For commands that I tested return with errors, they share one commen parameter is "--target_taxa".  
I fed "--target_taxa" with taxid. 

Am I using this parameter in a wrong way?

Error message I got is below:
Traceback (most recent call last):
  File "/root/eggnog-mapper-v2.0.0/emapper.py", line 1213, in <module>
    main(args)
  File "/root/eggnog-mapper-v2.0.0/emapper.py", line 275, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "/root/eggnog-mapper-v2.0.0/emapper.py", line 732, in annotate_hits_file
    for result in pool.imap(annotate_hit_line, iter_hit_lines(seed_orthologs_file, args)):
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 655, in next
    raise value
ImportError: No module named ete3

Thanks
Irene

**Comment by jlli6t** [comment]
Solved.

**Comment by selveyad** [comment]
I am interested in how you were able to solve this issue. I am having the same set of error codes populate!

**Comment by jlli6t** [comment]
Hi I guess it's due to multi command run at the same time thing, therefore I run just one emapper at a time, and seems it worked good.
