### ISSUE TITLE
v1 Error loading data

### ISSUE THREAD

**Issue by shelbyLanda** [eggnogdb/eggnog-mapper#192]
Hello, I am trying to run a file with 66,600 sequences with Diamond, and I am getting an "Error loading data" message. I saw in the closed issues that the program should be able to handle 70k sequences. Is there a particular file heading that I need to adhere to? Or has the sequence limit changed?

Any insight is appreciated. Thanks!

**Comment by jhcepas** [comment]
do you need v1? eggnog mapper v2 should be more reliable, as it runs in more servers and got bug fixes and updates...

**Comment by shelbyLanda** [comment]
Well, I saw that v2 is still in testing, and wanted to go with something with solid documentation. Either way,  with v2 I get a "413 Request Entity too large" message.

**Comment by Cantalapiedra** [comment]
Dear shelbyLanda,

I would ask you to use v2 or master versions if possible.
If not, please, send a detailed output including the error you find.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Please, re-issue if needed
