### ISSUE TITLE
Error in emapper-2.0.1, kernel

### ISSUE THREAD

**Issue by LinXuZJU** [eggnogdb/eggnog-mapper#194]
I tried to perform an annotation of an amino acid fasta file, while it did not work. And I updated kernel, it did not work either.

/home/sun/software/diamond/diamond /home/sun/software/eggnog-mapper-2.0.1
#  emapper-2.0.1
# ./emapper.py  -i P001.faa --output P001.output -m diamond
  /home/sun/software/diamond/diamond blastp -d /home/sun/software/eggnog-mapper-2.0.1/data/eggnog_proteins.dmnd -q /home/sun/file/Pseudomonas/eggnog/P001.faa --more-sensitive --threads 2 -e 0.001000 -o /home/sun/file/Pseudomonas/eggnog/emappertmp_dmdn_OzT0q0/3edf430aa6da4963828bd30f3a74611e --top 3 --query-cover 0 --subject-cover 0
FATAL: kernel too old
Traceback (most recent call last):
  File "/home/sun/software/eggnog-mapper-2.0.1/emapper.py", line 1213, in <module>
    main(args)
  File "/home/sun/software/eggnog-mapper-2.0.1/emapper.py", line 226, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "/home/sun/software/eggnog-mapper-2.0.1/emapper.py", line 380, in dump_diamond_matches
    raise e
subprocess.CalledProcessError: Command '/home/sun/software/diamond/diamond blastp -d /home/sun/software/eggnog-mapper-2.0.1/data/eggnog_proteins.dmnd -q /home/sun/file/Pseudomonas/eggnog/P001.faa --more-sensitive --threads 2 -e 0.001000 -o /home/sun/file/Pseudomonas/eggnog/emappertmp_dmdn_OzT0q0/3edf430aa6da4963828bd30f3a74611e --top 3 --query-cover 0 --subject-cover 0' returned non-zero exit status -6

**Comment by Cantalapiedra** [comment]
Dear LinXuZJU,

could be related with the diamond version being used?
I would recommend using the one included in the bin folder of eggnog-mapper, or a valid version (e.g. 0.9.24) with some virtual env, conda, or setting the path.

I hope this helps.

Best,
Carlos
