### ISSUE TITLE
Typos in Descriptions

### ISSUE THREAD

**Issue by davidbio** [eggnogdb/eggnog-mapper#195]
I identified 288 entries in http://eggnog5.embl.de/download/eggnog_5.0/e5.og_annotations.tsv
that have a description starting with a single quotation. The quotation is not "closed" and the descriptions also appear in other entries without any quotation.
Here is an example:
```bash
awk -F'\t' '{if ($4 ~ /Phosphotransferase$/) print $0}' e5.og_annotations.tsv
1236    1RY9U   S       Phosphotransferase
1239    1V2UV   S       Phosphotransferase
1762    233CQ   J       Phosphotransferase
91061   4HDHF   GT      Phosphotransferase
119065  1KJBW   S       Phosphotransferase
201174  2I5PG   S       'Phosphotransferase
5653    3XT0B   JL      Phosphotransferase
85009   4DSFT   S       'Phosphotransferase
```
This command identifies all of them:
```bash
awk -F'\t' 'BEGIN {OFS=FS} {if ($4 ~ /^'\''[^'\'']+$/) print $0}' e5.og_annotations.tsv > single_quotation.txt
```
These entries also show as such on the eggnog webpage.
Is this intentional?

**Comment by Cantalapiedra** [comment]
Hi davidbio,

thank you very much for reporting.
This is a eggnogdb issue. I will report it.

Best,
Carlos
