### ISSUE TITLE
Inconsistencies in Descriptions on Website Compared to the Database File

### ISSUE THREAD

**Issue by davidbio** [eggnogdb/eggnog-mapper#196]
COG categories, as well as descriptions, seem to be summarized on the webpage when compared to the database file.

a)
awk -F'\t' 'BEGIN {OFS=FS} {if ($2 ~ /COG5323/) print $0}' e5.og_annotations.tsv
1       COG5323 S       Terminase RNaseH-like domain
2       COG5323 M       Terminase RNaseH-like domain
vs
![image](https://user-images.githubusercontent.com/2159147/79223488-b7db1980-7e59-11ea-83d2-ede6546962dd.png)

b)
awk -F'\t' 'BEGIN {OFS=FS} {if ($2 ~ /COG3004/) print $0}' e5.og_annotations.tsv
1       COG3004 P       regulation of pH
2       COG3004 P       Na( ) H( ) antiporter that extrudes sodium in exchange for external protons
vs
![image](https://user-images.githubusercontent.com/2159147/79223510-c4f80880-7e59-11ea-9fa6-750790c40ab4.png)

There are more cases of these, I have not identified all. I guess it is not intentional?

**Comment by Cantalapiedra** [comment]
Dear davidbio,

we are working on the consistency between eggnogdb, eggnog-mapper cli and web.
I hope we can get all this fixed and documented soon.

Thank you very much for reporting.

Best,
Carlos
