### ISSUE TITLE
Efficiency considerations for OG_fasta

### ISSUE THREAD

**Issue by meren** [eggnogdb/eggnog-mapper#20]
Hi,

OG_fasta.tar.gz contains tens of thousands of small FASTA files, which is very hard to decompress. In fact I had to skip this simply because it has been hours and only a fraction of the files were decompressed.

Looking at the code and trying to figure out how it is used, it became clear to me that the current solution is to improve the random access efficiency during the processing of the hits file (i.e., https://github.com/jhcepas/eggnog-mapper/blob/master/emapper.py#L559).

I assume only a fraction of these FASTA files are in fact used to process hits for an average run. If I am correct, then I think it may be worthwhile to try to avoid the tremendous I/O overhead and file system stress by describing the contents of these FASTA files in an HDF5 file, and by creating necessary reads on-the-fly.

My 2 cents.

Best,

**Comment by jhcepas** [comment]
@meren thanks. You are right. The file decompresses well and fast when I tested it in our servers, but I agree this can be improved a lot. 
The main problem is that `phmmer` searches against those fasta files are very very fasta (current bottle neck is just reading the file from disk). If every file needs to be created on the fly, I am afraid it might add even more time to the process.
... Unless I can find a way to `phmmer` against a subset of sequences without having to create the actual fasta files, or using memory-based file objects. I will explore it, thanks

**Comment by meren** [comment]
I see. So my assumption about the refinement using a very small fraction of these FASTA files was not correct.

Maybe implementing a Python binding for phmmer could be an option to call it natively without having to go through the file system :/ It would have been great if the developers of phmmer were to consider doing that.

In any case, thank you very much!

**Comment by jhcepas** [comment]
We have avoided the use of OG_fasta in current version. thanks!
