### ISSUE TITLE
Standard parameters?

### ISSUE THREAD

**Issue by tnn111** [eggnogdb/eggnog-mapper#201]
We're trying to annotate a large collection of metagenomes. We've tried some runs with emapper using all defaults. This appears to generate a lot of annotations, but in a number of cases, we think we are pulling in more too much.

Does anyone have a good set of suggested parameter values to get a "conservative" metagenomic annotation?

**Comment by Cantalapiedra** [comment]
Could you please provide an example? Command run, eggnog-mapper version and
database version, result obtained and expected.
Thank you
