### ISSUE TITLE
Lost question

### ISSUE THREAD

**Issue by jmeppley** [eggnogdb/eggnog-mapper#206]
Hi, the following was inserted into the Wiki _Footer by user @WeiSong-bio 

"Can eggnog-mapper be used for the genome annotation  of plant or animal? thanks"

I deleted it so the wiki wasn't as confusing, but I thought I'd throw it up here in case someone wants to give a formal answer.

My non-expert answer is that eggnog mapper is not a genome annotator. It takes in gene sequences. 

It could be a good tool as part of an annotation pipeline, though. If you have gene sequences from animals or plants, eggnog mapper should be able to tell you quite a bit of information about those genes.

**Comment by Cantalapiedra** [comment]
Hi,

thank you very much for rescuing this question from the wiki.
You are right, it is currently a CDS/protein annotator.
Also, we are working to include the posibility to annotate genomes directly.

Hope to have news on this soon.
