### ISSUE TITLE
sqlite3.OperationalError: disk I/O error

### ISSUE THREAD

**Issue by suxiaoxing123** [eggnogdb/eggnog-mapper#207]
Hi, I install 1.0.3/v2/2.0.1 version, and download eggnog.db and eggnog_proteins.dmnd, place these files in data/. 
run "python emapper.py -i test/p53.fa --output p53_maNOG -m diamond".

log file is:
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 2
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /var/data/suxx/COG_test/emappertmp_dmdn_AlNZQO
Opening the database...  [0.002889s]
Percentage range of top alignment score to report hits: 3
Opening the input file...  [0.000709s]
Opening the output file...  [0.000846s]
Loading query sequences...  [6.6e-05s]
Masking queries...  [0.000678s]
Building query seed set...  [0.000284s]
Algorithm: Query-indexed
Building query histograms...  [0.000233s]
Allocating buffers...  [2.4e-05s]
Loading reference sequences...  [5.27758s]
Building reference histograms...  [2.66697s]
Allocating buffers...  [8.7e-05s]
Initializing temporary storage...  [0.060843s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [4.54663s]
Building query index...  [0.0006s]
Building seed filter...  [0.185952s]
Searching alignments...  [7.33905s]
Deallocating buffers...  [0.104897s]
Opening temporary output file...  [0.002931s]
Computing alignments...  [0.073274s]
Deallocating reference...  [0.177836s]
Loading reference sequences...  [5.56448s]
Building reference histograms...  [2.51934s]
Allocating buffers...  [0.000164s]
Initializing temporary storage...  [0.040405s]
Processing query chunk 0, reference chunk 1, shape 0, index chunk 0.
Building reference index...  [4.21523s]
Building query index...  [0.000841s]
Building seed filter...  [0.134949s]
Searching alignments...  [4.7999s]
Deallocating buffers...  [0.081185s]
Opening temporary output file...  [0.002206s]
Computing alignments...  [0.059988s]
Deallocating reference...  [0.141647s]
Loading reference sequences...  [3.9946s]
Building reference histograms...  [2.55452s]
Allocating buffers...  [4.7e-05s]
Initializing temporary storage...  [0.041347s]
Processing query chunk 0, reference chunk 2, shape 0, index chunk 0.
Building reference index...  [4.36236s]
Building query index...  [0.00066s]
Building seed filter...  [0.133855s]
Searching alignments...  [6.14901s]
Deallocating buffers...  [0.099406s]
Opening temporary output file...  [0.002328s]
Computing alignments...  [0.065267s]
Deallocating reference...  [0.163321s]
Loading reference sequences...  [5.57065s]
Building reference histograms...  [2.52235s]
Allocating buffers...  [4.4e-05s]
Initializing temporary storage...  [0.037167s]
Processing query chunk 0, reference chunk 3, shape 0, index chunk 0.
Building reference index...  [4.09189s]
Building query index...  [0.00037s]
Building seed filter...  [0.125061s]
Searching alignments...  [4.49756s]
Deallocating buffers...  [0.090431s]
Opening temporary output file...  [0.002116s]
Computing alignments...  [0.060796s]
Deallocating reference...  [0.150639s]
Loading reference sequences...  [1.15615s]
Building reference histograms...  [0.537184s]
Allocating buffers...  [8.7e-05s]
Initializing temporary storage...  [0.038656s]
Processing query chunk 0, reference chunk 4, shape 0, index chunk 0.
Building reference index...  [0.793382s]
Building query index...  [0.000471s]
Building seed filter...  [0.0231s]
Searching alignments...  [0.922505s]
Deallocating buffers...  [0.023934s]
Opening temporary output file...  [0.001602s]
Computing alignments...  [0.049263s]
Deallocating reference...  [0.026087s]
Loading reference sequences...  [7.4e-05s]
Deallocating buffers...  [3.8e-05s]
Joining output blocks...  [0.015547s]
Deallocating queries...  [0.012486s]
Loading query sequences...  [6.6e-05s]
Closing the input file...  [0.00036s]
Closing the output file...  [0.002487s]
Closing the database file...  [0.000229s]
Deallocating taxonomy...  [1.7e-05s]
Total time = 76.3368s
Reported 11 pairwise alignments, 11 HSPs.
1 queries aligned.
/home/eggnog-mapper-2.0.1/bin/diamond /home/eggnog-mapper-2.0.1
#  emapper-2.0.1
# ./emapper.py  -m diamond -i test/polb.fa --output polb_bact --output_dir ./test_result50/
  /home/eggnog-mapper-2.0.1/bin/diamond blastp -d /home/eggnog-mapper-2.0.1/data/eggnog_proteins.dmnd -q /var/data/suxx/COG_test/test/polb.fa --more-sensitive --threads 2 -e 0.001000 -o /var/data/suxx/COG_test/emappertmp_dmdn_AlNZQO/fb3a1df65c7f47af92b5ab47a05eb487 --top 3 --query-cover 0 --subject-cover 0
Traceback (most recent call last):
  File "/home/eggnog-mapper-2.0.1/emapper.py", line 1213, in <module>
    main(args)
  File "/home/eggnog-mapper-2.0.1/emapper.py", line 275, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "/home/eggnog-mapper-2.0.1/emapper.py", line 714, in annotate_hits_file
    seq2annotOG = annota.get_ogs_annotations(set([v[0] for v in seq2bestOG.itervalues()]))
  File "/home/eggnog-mapper-2.0.1/eggnogmapper/annota.py", line 34, in get_ogs_annotations
    if db.execute(cmd):
sqlite3.OperationalError: disk I/O error

No matter how I do it, keep reporting this error.

Can someone give me a hand? thank you very much~

**Comment by suxiaoxing123** [comment]
I get it!  eggnog.db cannot be a soft link in the data/!!!!!!

**Comment by Cantalapiedra** [comment]
Hi,
I am happy that it is working for you now.
However, you solution surprises me, since I am actually testing the app using data/eggnog.db as a soft link to another folder.
