### ISSUE TITLE
Incompatible database version

### ISSUE THREAD

**Issue by ChenJianyongNJAU** [eggnogdb/eggnog-mapper#208]
What's wrong with my database? 
the two files: eggnog.db and eggnog_proteins.dmnd
here is my error:
Error: Incompatible database version
Traceback (most recent call last):
  File "emapper.py", line 1001, in <module>
    main(args)
  File "emapper.py", line 216, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "emapper.py", line 353, in dump_diamond_matches
    raise e
subprocess.CalledProcessError: Command '/mnt/e/anaconda3/envs/py2/bin/diamond blastp -d /mnt/e/linux/emapper/eggnog-mapper-1.0.3/data/eggnog_proteins.dmnd -q /mnt/e/linux/emapper/eggnog-mapper-1.0.3/rye/hcs1-3_transcripts_MIPS_PROT_v3_final_mar14.fa --more-sensitive --threads 2 -e 0.001000 -o /mnt/e/linux/emapper/eggnog-mapper-1.0.3/emappertmp_dmdn_pwH8tP/c13e20dab3134bfeacc30bdfc4067352 --top 3' returned non-zero exit status 1

**Comment by Cantalapiedra** [comment]
Hi,

you are using "/mnt/e/anaconda3/envs/py2/bin/diamond"

It would be better if you try running it with the diamond included in your eggnog-mapper dist under "bin/diamond". 

You could do it running emapper.py within an environment in which "bin/diamond" is the "diamond" in the PATH. One way to check the one found in the current path: running in your command line "which diamond".

**Comment by Cantalapiedra** [comment]
Please, re-issue in case you need further help with this
