### ISSUE TITLE
submitting job through an HPC scheduler 

### ISSUE THREAD

**Issue by clb21565** [eggnogdb/eggnog-mapper#209]
Dear eggNOG support, thank you for your great tool. 

I am trying to annotate a collection of sequences using my institution's HPC system by submitting the job through the slurm scheduler, and I am getting an error I have not seen before: 

slurmstepd: error: execve(): /var/spool/slurmd/job277790/slurm_script: Not a directory

note that the job runs successfully just inputting it as a direct command seen below: 

emapper.py --cpu 1 -m diamond -i /work/cascades/clb21565/eggnog.workdir/eggnog-mapper/ys_0.97.fasta ---output YRs

What could be happening here?

Thanks for the assist. 

Warmest Regards, 

Connor

**Comment by Cantalapiedra** [comment]
Hi,

It looks like a problem with your slurm job, not related with eggnog-mapper (?).

Could it be a misconfiguration of Slurm? The quick attempt to fix it could be restarting the slurmd daemons... but not sure how to help with this, sorry.

**Comment by Cantalapiedra** [comment]
Please, re-open if you find that we could further help with this
