### ISSUE TITLE
emapperdb-5.0.0: GO_freq, KEGG_freq, SMART_freq, and proteins in og table?

### ISSUE THREAD

**Issue by selveyad** [eggnogdb/eggnog-mapper#211]
Howdy,

I was wondering if there was a way to get the GO_freq, KEGG_freq, SMART_freq, and proteins columns within the og table that appear in the v4.5.1 database, but not in the v5.0.0 database? I am using EnTAP for transcriptome annotation, which utilizes EggNOG for GO annotations and it requires the values within these columns. I would like to utilize the most up-to-date information that EggNOG has to offer, instead of the older versions that EnTAP currently utilizes. If they were removed from v5.0.0 (probably for good reason), are there equivalents to these categories in v5.0.0? I can just modify the SQL commands to select the equivalent categories if they exist. 

Many Thanks,

Alex

**Comment by Cantalapiedra** [comment]
Hi,

I am a bit confused. Is not EnTap using eggnog5 database? https://onlinelibrary.wiley.com/doi/full/10.1111/1755-0998.13106

**Comment by Cantalapiedra** [comment]
Hi Alexander,

if they use version 4.5.1 and will not update to 5.0.0 there is little we could do from our side.
If you really want to have the annotation from eggnog5 then maybe you could annotate your sequences with both EnTap and eggnog-mapper, and merge them afterwards.

I am not that familiar with version 4.5.1, but I guess that those missing fields were a way to easily retrieve the annotation data for a given orthologous group.

Maybe you could retrieve those GOs from eggnog5 DB by first obtaining all the seed orthologs which are part of a given orthologous group ("eggnog" table), then retrieving all the GOs for those seeds ("gene_ontology" table). If you want to retrieve the GOs for a different orthology scheme (co-orthologs one2one, many2one, etc) you would need to go first through the "event" and "orthologs" tables path.

However, I am not completely sure that this was the information held in the GO_freq fields.

Best,
Carlos

**Comment by selveyad** [comment]
Howdy, 

Thanks for the workaround! I thought I might give you and example of the information found in each of the *_freq columns to see if you have any other suggestions.

GO_freq: {"Molecular Function":[["GO:0097159","organic cyclic compound binding","IEA",4,"100","100"],["GO:0000166","nucleotide binding","IEA",4,"100","100"],["GO:0036094","small molecule binding","IEA",4,"100","100"],["GO:0005488","binding","IEA",4,"100","100"],["GO:1901363","heterocyclic compound binding","IEA",4,"100","100"],["GO:1901265","nucleoside phosphate binding","IEA",4,"100","100"],["GO:0003676","nucleic acid binding","IEA",3,"75","98.4"],["GO:0003723","RNA binding","IEA",1,"25","92.5"]]}

KEGG_freq: [["Oocyte meiosis (04114)",4,"100","100"],["Natural killer cell mediated cytotoxicity (04650)",4,"100","100"],["Alzheimer's disease (05010)",4,"100","100"],["Calcium signaling pathway (04020)",4,"100","100"],["Dopaminergic synapse (04728)",4,"100","100"],["VEGF signaling pathway (04370)",4,"100","100"],["T cell receptor signaling pathway (04660)",4,"100","100"],["Wnt signaling pathway (04310)",4,"100","100"],["Apoptosis (04210)",4,"100","100"],["Amyotrophic lateral sclerosis (ALS) (05014)",4,"100","100"],["HTLV-I infection (05166)",4,"100","100"],["Glutamatergic synapse (04724)",4,"100","100"],["Axon guidance (04360)",4,"100","100"],["MAPK signaling pathway (04010)",4,"100","100"],["Tuberculosis (05152)",4,"100","100"],["Long-term potentiation (04720)",4,"100","100"],["Osteoclast differentiation (04380)",4,"100","100"],["Amphetamine addiction (05031)",4,"100","100"],["B cell receptor signaling pathway (04662)",4,"100","100"]]

SMART_freq: {"PFAM":[["Metallophos",4,"100","100"]],"SMART":[["PP2Ac",4,"100","100"]]}

proteins: 9598.ENSPTRP00000004567,9601.ENSPPYP00000002711,9606.ENSP00000378306,9593.ENSGGOP00000027171

Does your line of reasoning produce a similar outcome? I do like the idea of utilizing both EnTAP with dbv4.5.1 and eggnog-mapper with dbv5.0.0. Do you think that the results would be easily combined? I guess I could combine by transcript name and see how that fairs. Might need a little finagling.

Thanks for getting back to me!

Best Regards,

Alex

**Comment by Cantalapiedra** [comment]
Thank you for the examples Alex. I already saw them in the sqlite3 DB though :)

I guess it would give a very similar output, if not identical, but a) I am not sure b) there won't be descriptions. You can try, for example:

select name from eggnog where groups LIKE "%0RWQ4%";
9601.ENSPPYP00000014337
9606.ENSP00000331211
9593.ENSGGOP00000008646
9598.ENSPTRP00000021421

select * from gene_ontology where name="9601.ENSPPYP00000014337";
# Repeat for all the orthologs and merge results
The list of terms you obtain should be similar (identical?) to that in the "og" table for 0RWQ4 group:
{"Molecular Function":[["GO:0097159","organic cyclic compound binding","IEA",4,"100","100"],["GO:0000166","nucleotide binding","IEA",4,"100","100"],["GO:0036094","small molecule binding","IEA",4,"100","100"],["GO:0005488","binding","IEA",4,"100","100"],["GO:1901363","heterocyclic compound binding","IEA",4,"100","100"],["GO:1901265","nucleoside phosphate binding","IEA",4,"100","100"],["GO:0003676","nucleic acid binding","IEA",3,"75","98.4"],["GO:0003723","RNA binding","IEA",1,"25","92.5"]]}


About merging the EnTap and eggnog5 results, unfortunately I am not sure what does EnTap actually do (post-processing I mean) with the eggnog-mapper results. But if it is something you could mimick it should be ok I guess.

Best,
Carlos

**Comment by selveyad** [comment]
Carlos,

You're the man! I'll give it a swing and see if I can jury-rig it to make EnTAP happy.

Thanks for the help!

Best Regards,

Alex
