### ISSUE TITLE
Command Exit Non-zero exit status -11

### ISSUE THREAD

**Issue by MichWeb75** [eggnogdb/eggnog-mapper#215]
The following call ended with an error:
`emapper.py -i subset.fna" --translate --output eggnog -m diamond`

`emappertmp_dmdn_yNtuJE: No such file or directory`

`diamond blastx -d /opt/miniconda3/envs/eggnog/lib/python2.7/site-packages/data/eggnog_proteins.dmnd -q subset.fna --more-sensitive --threads 2 -e 0.001000 -o emappertmp_dmdn_yNtuJE/582b3bc55f9b4b50a75b5cfca603eae9 --top 3 --query-cover 0 --subject-cover 0' returned non-zero exit status -11`

I am wondering why it is unable to create the directory ?

**Comment by Cantalapiedra** [comment]
Hi,

what OS are you using?
Do you have permissions to create a directory there?

**Comment by MichWeb75** [comment]
Hi, I am using CentOS 7 and I created eggnog inside a conda repository on /opt/conda. Actually I granted all permissions to all users, I am wondering if I need to run as sudo ?

**Comment by Cantalapiedra** [comment]
Could you try running emapper specifying the --temp_dir?

**Comment by MichWeb75** [comment]
Thank you, solved! --temp_dir is a good solution to redirect temporal files.

**Comment by Cantalapiedra** [comment]
Hi,
Glad it worked for you.
Best,
Carlos
