### ISSUE TITLE
EGGNOG vs KEGG Pathway

### ISSUE THREAD

**Issue by bagaraj** [eggnogdb/eggnog-mapper#221]
I am very new to Bio R&D from IT side... So bear with me on some fundamental question. 

We are trying to get KEGG Pathway license for BIO R&D applications.  We would like to use KEGG DB as centralized DB, not sure we should be able to achieve it as I was told that EGGNOG Mapper comes with KEGG DB, hence we don't need to procure separate KEGG DB license. Here is KEGG link where we are purchasing the license material.  

https://www.genome.jp/kegg/pathway.html

**Comment by Cantalapiedra** [comment]
Hi @bagaraj ,

eggnog-mapper includes KEGG annotation of the sequences within its orthologous groups.
This is not the same as including the KEGG DB, but instead that KEGG DB was used as a reference to annotate those sequences.
Therefore, you can use the KEGG DB to annotate your own sequences, through homology search I guess, or you could use eggnog-mapper to annotate your sequences by transferring the KEGG annotation from orthologs groups which are related to your sequences.

I hope this is of help.

Best,
Carlos
