### ISSUE TITLE
Outdated NCBI database decompress error from zlib

### ISSUE THREAD

**Issue by milnus** [eggnogdb/eggnog-mapper#222]
Hello,
I have wrestled a bit with getting Eggnog-mapper running. I get: `Downloading taxdump.tar.gz from NCBI FTP site (via HTTP)...` multiple times after functional annotation of refined hits starts. It says 'Done. parsing...' a matching number of times. Then Eggnog-mapper starts updating the database: `Updating database: /home/mjespersen/.etetoolkit/taxa.sqlite ...`

At some point after updating the database a couple of times it throws the following error:

Traceback (most recent call last):
  File "/data/projects/punim1089/eggnog-mapper/emapper.py", line 1213, in <module>
    main(args)
  File "/data/projects/punim1089/eggnog-mapper/emapper.py", line 275, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "/data/projects/punim1089/eggnog-mapper/emapper.py", line 732, in annotate_hits_file
    for result in pool.imap(annotate_hit_line, iter_hit_lines(seed_orthologs_file, args)):
  File "/home/mjespersen/.conda/envs/Eggnog-mapper/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
zlib.error: Error -3 while decompressing: invalid distance code

I cannot find a reason for this error. Do you have any explanation or fix?
The command i used to run: `python /data/projects/eggnog-mapper/emapper.py
   -i $input_pan
   --output $output_folder
   -m diamond
   --scratch_dir /tmp/$SLURM_JOB_ID
   --target_taxa 2
   --cpu 16
   --resume
`

**Comment by Cantalapiedra** [comment]
Hi @milnus ,

which eggnog-mapper version are you trying to use?

**Comment by milnus** [comment]
I'm using emapper-2.0.1b

**Comment by Cantalapiedra** [comment]
Hi,

sorry for the delay answering.
Did you manage to fix it?

**Comment by milnus** [comment]
All good,
I downloaded a new version of emapper and the database, that seemed to fix the problem, and some other small things I ran into

**Comment by Cantalapiedra** [comment]
Glad to read that. Thank you for reporting.
Best,
Carlos
