### ISSUE TITLE
Jobs stuck (?) after diamond

### ISSUE THREAD

**Issue by gprezza** [eggnogdb/eggnog-mapper#223]
Hi all, first of all congratulations for this great tool.

I'm having troubles with running any job to completion in version 2.0.1b. Any job that I submit seems to get stuck after the diamond run. 
e.g. `python emapper.py --cpu 8 -i input.fa --output out --output_dir eggnog_annotations -m diamond -d none --go_evidence non-electronic --target_orthologs all --override --temp_dir temp`

Everything runs fine during the diamond alignment, until the line ```xyz queries aligned.``` gets printed. After this nothing happens (I let it run for hours, and I am working with very small input files of ~20-30 sequences). Ctrl+C doesn't kill the job at this point and I have to do `kill -9 pid`.

I also tried the test script and also that seems to get stuck. It prints the first command:
```
Running eggnog-mapper...
./emapper.py -m diamond -i tests/fixtures/test_queries.fa --data_dir tests/fixtures --output_dir tests/out -o test
```
and then nothing happens. If I Ctrl+C I get:
```
^CTraceback (most recent call last):
  File "tests/test.py", line 145, in <module>
    unittest.main()
  File "/home/gprezza/anaconda3/envs/eggnog/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/home/gprezza/anaconda3/envs/eggnog/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/home/gprezza/anaconda3/envs/eggnog/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/home/gprezza/anaconda3/envs/eggnog/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/home/gprezza/anaconda3/envs/eggnog/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/home/gprezza/anaconda3/envs/eggnog/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/home/gprezza/anaconda3/envs/eggnog/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/home/gprezza/anaconda3/envs/eggnog/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/home/gprezza/anaconda3/envs/eggnog/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "tests/test.py", line 125, in test_emapper_cmd
    st, out, err = run(cmd)
  File "tests/test.py", line 24, in run
    out, err = process.communicate()
  File "/home/gprezza/anaconda3/envs/eggnog/lib/python2.7/subprocess.py", line 483, in communicate
    return self._communicate(input)
  File "/home/gprezza/anaconda3/envs/eggnog/lib/python2.7/subprocess.py", line 1124, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/home/gprezza/anaconda3/envs/eggnog/lib/python2.7/subprocess.py", line 1178, in _communicate_with_poll
    ready = poller.poll()
KeyboardInterrupt
```

**Comment by Cantalapiedra** [comment]
Hi,

could you try run in it with python 3 and share the stderr output you get?

Thank you.
Best,
Carlos

**Comment by gprezza** [comment]
Hi Carlos, thanks for the reply.

If I run it with python 3 it complains of the python 2 formatting:

``` 
File "emapper.py", line 64
    print dbpath
               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(dbpath)?
```

Or did you mean to try something else?

**Comment by Cantalapiedra** [comment]
Hi @gprezza ,

sorry, I was wrong. I sometimes got confused among branches and tags.
Could you try running the following commands and writing back the output?

mkdir tests/out
./emapper.py -m diamond -i tests/fixtures/test_queries.fa --data_dir tests/fixtures --output_dir tests/out -o test

Thank you.

Best,
Carlos

**Comment by gprezza** [comment]
mkdir tests/out :
'''
mkdir: cannot create directory 'tests/out': File exists
'''
./emapper.py -m diamond -i tests/fixtures/test_queries.fa --data_dir tests/fixtures --output_dir tests/out -o test :

**Comment by gprezza** [comment]
(Sorry, I closed the issue by mistake.)

Here the outputs:

mkdir tests/out :

```
mkdir: cannot create directory ‘tests/out’: File exists
```
 ./emapper.py -m diamond -i tests/fixtures/test_queries.fa --data_dir tests/fixtures --output_dir tests/out -o test :
```
/vol/projects/gprezza/srna_folding/eggnog-mapper-2.0.1b/bin/diamond /vol/projects/gprezza/srna_folding/eggnog-mapper-2.0.1b
Output files detected in disk. Use --resume or --override to continue
```
If I rerun with --override it runs until "2 queries aligned" and then hangs as usual.

**Comment by gprezza** [comment]
Thanks for the help!

/usr/bin/env python2 --version :

```
Python 2.7.18 :: Anaconda, Inc.
```

After aborting, inside tests/out I only have the file "test.emapper.seed_orthologs" and this is its content:
```
# Thu Sep  3 09:23:29 2020
# emapper-2.0.1
# ./emapper.py -m diamond -i tests/fixtures/test_queries.fa --data_dir tests/fixtures --output_dir tests/out --override -o test
#
# /vol/projects/gprezza/srna_folding/eggnog-mapper-2.0.1b/bin/diamond blastp -d /vol/projects/gprezza/srna_folding/eggnog-mapper-2.0.1b/tests/fixtures/eggnog_proteins.dmnd -q /vol/projects/gprezza/srna_folding/eggnog-mapper-2.0.1b/tests/fixtures/test_queries.fa --more-sensitive --threads 2 -e 0.001000 -o /vol/projects/gprezza/srna_folding/eggnog-mapper-2.0.1b/emappertmp_dmdn_ZJ4MUw/f67046644fd148cbbbb3da782f77238b --top 3 --query-cover 0 --subject-cover 0
1000565.METUNv1_03812	1000565.METUNv1_03812	1.9e-207	716.8
362663.ECP_0061	362663.ECP_0061	0.0	1636.3
```
I guess this is the normal output?

Anyways, the emappertmp_dmdn dir is neither in the path you mentioned nor in the one present in the ouput above (/vol/projects/gprezza/srna_folding/eggnog-mapper-2.0.1b).

**Comment by Cantalapiedra** [comment]
Hi,

In your output it is shown "emapper-2.0.1", but I have "emapper-2.0.1b". Then, it seems that you are not using 2.0.1b but 2.0.1? Could you please confirm this? 
Also, how did you install eggnog-mapper?

**Comment by gprezza** [comment]
Oh, I didn't notice that.

I downloaded everything with `wget https://github.com/eggnogdb/eggnog-mapper/archive/2.0.1b.tar.gz` and then untarred.
Actually, I just re-downloaded it and `./emapper.py --version` still gives me `emapper-2.0.1`.

**Comment by Cantalapiedra** [comment]
Would you mind trying with git clone?

git clone --branch 2.0.1b https://github.com/eggnogdb/eggnog-mapper.git

**Comment by gprezza** [comment]
Well, the fact that wget gives problems when downloading specific versions is new to me, thanks for making me realize it!

I re-downloaded with git clone, but the issue still persist.
The content of tests/out/test.emapper.seed_orthologs is now:
```
# Thu Sep  3 14:55:57 2020
# emapper-2.0.1b
# ./emapper.py -m diamond -i tests/fixtures/test_queries.fa --data_dir tests/fixtures --output_dir tests/out --override -o test
#
# /vol/projects/gprezza/srna_folding/eggnog-mapper/bin/diamond blastp -d /vol/projects/gprezza/srna_folding/eggnog-mapper/tests/fixtures/eggnog_proteins.dmnd -q /vol/projects/gprezza/srna_folding/eggnog-mapper/tests/fixtures/test_queries.fa --more-sensitive --threads 2 -e 0.001000 -o /vol/projects/gprezza/srna_folding/eggnog-mapper/emappertmp_dmdn_3VcJ8a/46d57ef341e94de48f7d50be3205b783 --top 3 --query-cover 0 --subject-cover 0
1000565.METUNv1_03812	1000565.METUNv1_03812	1.9e-207	716.8
362663.ECP_0061	362663.ECP_0061	0.0	1636.3
```

**Comment by Cantalapiedra** [comment]
The seed_orthologs file contains the hits of your queries found by diamond.
Therefore, the search step runs just fine.
Then, it seems that emapper gets stuck before starting the annotation step, using that seed_orthologs file.
Because of this, we are going to try to annotate directly the seed_orthologs file you have, to see whether this way we can "force" eggnog-mapper to run the annotation step. Could you try running:

./emapper.py --annotate_hits_table tests/out/test.emapper.seed_orthologs --data_dir tests/fixtures --output_dir tests/out -o test --override

thanks

**Comment by gprezza** [comment]
The command only prints the first lines:
```
/vol/projects/gprezza/srna_folding/eggnog-mapper/bin/diamond /vol/projects/gprezza/srna_folding/eggnog-mapper
#  emapper-2.0.1b
# ./emapper.py  --annotate_hits_table tests/out/test.emapper.seed_orthologs --data_dir tests/fixtures --output_dir tests/out -o test --override
```
and then hangs.

**Comment by Cantalapiedra** [comment]
So weird.
I guess that you have a the database file, of around 14MB: "ls -lh tests/fixtures/eggnog.db"

Also, what is the output of
`conda list | grep sqlite`
Mine is:
`sqlite                    3.32.3               hcee41ef_1    conda-forge`

Also, check the output of:

`which sqlite3`

And also, try:

`sqlite3 tests/fixtures/eggnog.db`

and within the sqlite3 interpreter type:

`.schema`

You should see several tables. For example:

`
CREATE TABLE eggnog(
name VARCHAR(32) PRIMARY KEY,
groups TEXT);
`

My guess now is that the error could be when the sqlite3 database connection is established. But just guessing...

**Comment by gprezza** [comment]
Yes, the database is there: ls -lh tests/fixtures/eggnog.db :  `-rw-r--r-- 1 gprezza clusers 14M  3. Sep 14:07 tests/fixtures/eggnog.db`

 conda list | grep sqlite:
`sqlite                    3.32.3               h62c20be_0`

which sqlite3:
`~/anaconda3/envs/eggnog/bin/sqlite3`

Now, within the sqlite3 interpreter, after typing `.schema` nothing happens (so no tables printed) and it seems to hang there. Looks like your guessing was right after all...!

**Comment by gprezza** [comment]
Oh, I found the issue. The drive where the database is has an nfs filesystem, and sqlite doesn't like that. Moving the database on a drive with another filesystem solves the issue.

Thanks for the help anyways! Still weird that everything was just freezing without throwing any error; I saw from other (now closed) issues that usually people in my situation get some type of I/O errors.

**Comment by Cantalapiedra** [comment]
Hi,

nice that you found it.
Yes, it is weird that there was no error at all. Also that the test database was failing was misleading, so I guess that the whole eggnog-mapper install is within the nfs?

Glad to help. Ask if you need further help.

Best,
Carlos

**Comment by gprezza** [comment]
Correct, everything was in the nfs drive.

Thanks for your help and time!
-Gianluca
