### ISSUE TITLE
Run EggNOG on precomputed orthogroups

### ISSUE THREAD

**Issue by lalalagartija** [eggnogdb/eggnog-mapper#224]
Hi, 
Is it possible to run EggNOG on pre-computed metagenomic orthogroups ? That way I would ensure that the annotation is in phase with the rest of the analysis.

thank you very much in advance, 
Sofia

**Comment by Cantalapiedra** [comment]
Hi,

I am not sure what do you mean with metagenomic orthogroups.
In the current version, the input should consist of coding sequences (DNA) or protein sequences.
If your metagenomic orthogroups fit into this requirement you could run eggnog-mapper to annotate them.

Best,
Carlos

p.s.: You mean running eggnog-mapper.
