### ISSUE TITLE
Different output local and web version

### ISSUE THREAD

**Issue by PedroMTQ** [eggnogdb/eggnog-mapper#225]
Hello,
I was doing some benchmarking with the local and online version of eggnog mapper and noticed the output is different?

![image](https://user-images.githubusercontent.com/22548082/89910407-7d5b7080-dbf0-11ea-890d-2d47ef3b0754.png)

On the left you can see the output from the local version and on the right the web version.
For the web version I used the "auto-adjust per query" for taxonomic scope, whereas for the local version I used the ncbi id of each organism.

I then compared the identifiers between these two to the reference proteome annotations. Strangely, they are very different... any reason why that would be? Also, why is eggnog mapper barely outputting identifiers for some organisms?

Thanks

command for local version:
`python emapper.py -i bacillus_subtilis.faa -o annotation_output --target_taxa '1423' -m diamond`

**Comment by jhcepas** [comment]
Hi @PedroMTQ , are you using eggnog-mapper v2 also in your local runs?

**Comment by PedroMTQ** [comment]
So this is from the local output:
# emapper version: emapper-2.0.1-14-gbf04860 emapper DB: 2.0
# command: ./emapper.py  -i bacillus_subtilis.faa -o annotation_output --target_taxa 1423 -m diamond

and then from the web output:
# emapper version: emapper-1.0.3-35-g63c274b emapper DB: 2.0
# command: ./emapper.py  --cpu 6 -i /data/shared/emapper_jobs/user_data/MM_g7jnz166/query_seqs.fa --output query_seqs.fa --output_dir /data/shared/emapper_jobs/user_data/MM_g7jnz166 -m diamond -d none --tax_scope auto --go_evidence non-electronic --target_orthologs all --seed_ortholog_evalue 0.001 --seed_ortholog_score 60 --query-cover 20 --subject-cover 0 --override --temp_dir /data/shared/emapper_jobs/user_data/MM_g7jnz166
--

**Comment by jhcepas** [comment]
then the differences are because 1) the backend eggnog database use (eggnog 4.5 in your local version eggnog v5 in the online version), and 2) you are restricting annotation a lot more in your local run using target_taxa
hope it helps

**Comment by PedroMTQ** [comment]
So, in order to have more complete annotations I'd have to locally run eggnogmapper with and without taxa?

**Comment by jhcepas** [comment]
yes, use v2 if possible, and use automatic taxonomic scope (it is already
enabled by default)
