### ISSUE TITLE
Why does my query_seqs.fa have many more sequences than the "queries scanned" number in .annotations file?

### ISSUE THREAD

**Issue by dominicev** [eggnogdb/eggnog-mapper#226]
I am trying to match up my library with the annotations and am wondering why not all sequences in the query have been scanned. Were they filtered out before the scan (i.e., non-protein coding sequences were removed)?  Thank you.

**Comment by Cantalapiedra** [comment]
Hi,

In general terms, eggnog-mapper carries out 2 steps: seed ortholog search using sequence alignment (currently using diamond), and annotation based on those seed ortholog hits.

It could be your case that not all your queries had a seed ortholog hit, and thus not all of them have been scanned looking for annotations. Is this the case?

Best,
Carlos

**Comment by dominicev** [comment]
Thank you for the clarification.

The output files from the online mapper tool don't specify how many sequences were lacking a hit. My input file has 49295 sequences and the .annotations file says 1663 queries scanned. I don't believe the remaining queries are mentioned.

**Comment by Cantalapiedra** [comment]
Hi,

in the online folder corresponding to your job you should have several output files.
One of them is the .seed_orthologs file, which contains the diamond hits of your queries.
How many lines (not starting with "#") do you have in such file?

**Comment by dominicev** [comment]
1663 lines in that file

**Comment by Cantalapiedra** [comment]
Then, the rest of the sequences are not having a diamond hit to the eggnog sequences.
What kind of sequences are you using? Are those CDS or proteins? transcripts?

**Comment by dominicev** [comment]
The vast majority are likely non-target hits from my anchored hybrid enrichment protocol.

**Comment by dominicev** [comment]
I think you answered my question sufficiently in the first response. The wording from the output made it seem like the vast majority of sequences were ignored (i.e., not scanned) but based on your response I see that the number of sequences scanned is only in reference to a downstream step and not the initial search for a seed ortholog. Thank you!

**Comment by Cantalapiedra** [comment]
Glad to help.
Thank you.
Best,
Carlos
