### ISSUE TITLE
Sequences returning zero queries scanned, zero annotations matched

### ISSUE THREAD

**Issue by TalithaR** [eggnogdb/eggnog-mapper#227]
Hello
I am very new to programming to please forgive any really obvious oversights here.
I have attempted to run both nt and AA fasta files through the web-based emapper for a Paraburkholderia strain. I have pretty much tried all things I can think of and I am still getting returns that say zero queries were scanned. 
I have also tried downloading eggnog and running it myself with no luck.
What am I missing here?

*Note: the sequences I am using have been translated (or exported directly for trying nt seq) in Geneious and exported and saved as fasta

**Comment by Cantalapiedra** [comment]
Hi,

it seems like you finally fixed your issue?
Could you share what was the problem and how you solved it?

Thank you
