### ISSUE TITLE
Error: annotation went wrong 

### ISSUE THREAD

**Issue by slaperriere** [eggnogdb/eggnog-mapper#228]
Hello - 

When running the test, I do not get any errors. But when running it on my own test fasta I get an error. 

```
/home/sarah/eggnog-mapper/eggnog-mapper-2.0.2-rf1/emapper.py -i  test.faa \
                            --output test3 --cpu 20 --override \
                            --output_dir /home/sarah/ESP_NCLDV/61_emapper_hq_bins 

#  emapper-2.0.1 / eggNOG DB version: 2.0
# emapper.py  -i test.faa --output test3 --cpu 20 --override --output_dir /home/sarah/ESP_NCLDV/61_emapper_hq_bins
  /home/sarah/eggnog-mapper/eggnog-mapper-2.0.2-rf1/bin/diamond blastp -d /home/sarah/eggnog-mapper/eggnog-mapper-2.0.2-rf1/data/eggnog_proteins.dmnd -q /home/sarah/ESP_NCLDV/61_emapper_hq_bins/test.faa --more-sensitive --threads 20 -e 0.001 -o /home/sarah/ESP_NCLDV/61_emapper_hq_bins/emappertmp_dmdn_fm7mak2p/6c2549e35cb24610bb7054a981b8d708 --query-cover 0 --subject-cover 0 --top 3 
Functional annotation of refined hits starts now
Error: annotation went wrong for line "ESPAEMG04_S40.maxbin2.bin.5.fna_viral_region_10_3	1137745.H6WG84_9CAUD	2.1e-22	111.7". database disk image is malformed
```

Do you know what could be causing this error?

Thanks, 
Sarah

**Comment by Yorks0n** [comment]
I ran into the same problem today. It seems that there is something wrong with the database file, so I re-downloaded it but couldn't fix it. 
I turned to version 2.0.1b (the latest before refactor) with the same database file, and the issue didn't occur again.

**Comment by yan123-yang** [comment]
if you want use the version 2.0.1 (refactor branch), you have to create a environment of python37, and Modify some codes makes it runing, 
I get erro1 : AttributeError: module 'eggnogmapper.annotation.db_sqlite' has no attribute 'close': modify ./eggnog-mapper-2.0.1-rf1/eggnogmapper/annotation/annotator.py: add '#' to  line 281 db_sqlite.close();
erro 2 : File "/nfs-test/yangyan/software/EggNog/eggnog-mapper-2.0.1-rf1/eggnogmapper/annotation/annotator.py", line 127, in _annotate
    print(f"{pq} {total_time} {(float(qn) / total_time):.2f} q/s (func. annotation)", file=sys.stderr)
NameError: name 'pq' is not defined : add # to line127 :print(f"{pq} {total_time} {(float(qn) / total_time):.2f} q/s (func. annotation)", file=sys.stderr)

**Comment by Cantalapiedra** [comment]
Dear all,

the refactor branch is under development and unfortunately the proper database used by this version is currently not available.
We recommend using the master branch.

Best,
Carlos
