### ISSUE TITLE
Question: the preferred database

### ISSUE THREAD

**Issue by alimayy** [eggnogdb/eggnog-mapper#233]
Hi all,

First of all many thanks for developing eggnog-mapper2 (and possibly eggNOG 5 too).

I have a question about the default/preferred database for eggnog-mapper2. In the following link
https://github.com/eggnogdb/eggnog-mapper/wiki/FAQ---Frequently-Asked-Questions
There is a section titled "Why I cannot choose HMMer search mode in version 2.0?", explaining that Diamond search is preferred against an HMM search based on a benchmark. I think this conflicts with default execution option of the emapper.py script (or I am missing something)?

```
emapper.py --help |grep -a2 Execution
                        .Default = per_species

Execution options:
  -m {hmmer,diamond}    Default:hmmer
  -i                    Input FASTA file containing query sequences
```

**Comment by Cantalapiedra** [comment]
Hi.

Which version of emapper.py are you running?

**Comment by alimayy** [comment]
Hi @Cantalapiedra, I'm running emapper-2.0.1b-2-g816e190

**Comment by Cantalapiedra** [comment]
Hi @alimayy 

you are completely right. The default mode in such version should be diamond. Actually, it should be the only option. Please, use `-m diamond` in your commands.

Thank you.

Best,
Carlos
