### ISSUE TITLE
eggnog-mapper for Orthology fish- Rodentia

### ISSUE THREAD

**Issue by StavBiton** [eggnogdb/eggnog-mapper#234]
Hi!
I want to find orthologs between fish to Rodentia. The input file was a Fasta file of Fish. The output file is attached. 
I uploaded a fasta file and I selected Rodentia in the Taxonomic Scope dropdown. All the other parameters have their default values. After submit to annotation I didn't expected to see an empty cells as preferred name (happen for most of the rows). 

[job_MM_vk6a0bcv_annotations.xlsx](https://github.com/eggnogdb/eggnog-mapper/files/5305425/job_MM_vk6a0bcv_annotations.xlsx)

Thanks

**Comment by Cantalapiedra** [comment]
Hi,

In the version running currently in the web, the Taxonomic Scope will limit the annotations obtained to only those hits whose seed ortholog is within that scope. This is why you only get annotations for those hits for which the seed ortholog is of a tax level within the Rodentia group (check column "best_tax_lvl" in your data).

However, if I understood correctly, what you are looking for is to use a wider scope (above both Fish and Rodentia), but then get only the annotations from orthologs belonging to the Rodentia group. You should be able to do this combining the Taxonomic Scope (a group common to Fish and Rodentia, to retrieve orthologs) and Target Taxa (Rodentia) arguments. However, I am afraid that the Target Taxa is not available in the current web version, and it is only in the command line version of eggnog-mapper.

Best,
Carlos
