### ISSUE TITLE
Fetch databases failed

### ISSUE THREAD

**Issue by limin321** [eggnogdb/eggnog-mapper#235]
Hi,  
I followed the following instruction to fetch the database, 
```
download_eggnog_data.py 
```
This will fetch and decompress all precomputed eggNOG data into the data/ directory.

And run into some issue:
<img width="663" alt="Screen Shot 2020-10-07 at 4 50 06 PM" src="https://user-images.githubusercontent.com/42760669/95399483-28b93680-08bd-11eb-9f16-9275a8a70e9e.png">

Does anyone have any suggestion on what may go wrong to fetch the database?

Thanks.

**Comment by Cantalapiedra** [comment]
Hi,

which version of eggnog-mapper are you using?

**Comment by limin321** [comment]
> Hi,
> 
> which version of eggnog-mapper are you using?

Thank you for the reminder. It works now. 
The problem was:
If I download eggnog following this:
Download and decompress the latest version of eggnog-mapper from
```
  https://github.com/jhcepas/eggnog-mapper/releases. The program does not
  require compilation nor installation.
```
Then I will have issue download the database. However, I use 
```
git clone https://github.com/jhcepas/eggnog-mapper.git
```
No error occurs when downloading the database.

Thanks.

**Comment by Cantalapiedra** [comment]
Hi,

yes, sorry about that. We did some fixes for the current master branch, but we didn't want to do a new release, because the refactor branch will include a lot more changes.

Glad that you were able to cope with it and avoid the confusion.

Best,
Carlos
