### ISSUE TITLE
argument --dmnd_evalue: unrecognized arguments

### ISSUE THREAD

**Issue by qiao-xin** [eggnogdb/eggnog-mapper#236]
Hi,

I am using `emapper-2.0.1b-2-g816e190` and want to define the `--dmnd_evalue`. However, the command

```
emapper.py --cpu 10 -i Ath.pep --output Ath --output_dir ./test -m diamond --dmnd_evalue 1e-5 --seed_ortholog_evalue 1e-5 --override --temp_dir ./test
```

gives me the error:

```
emapper.py: error: unrecognized arguments: --dmnd_evalue 1e-5
```

**Comment by Cantalapiedra** [comment]
Hi,

--dmnd_evalue is not available in version 2.0.1b-2-g816e190. You should be fine using --seed_ortholog_evalue

**Comment by qiao-xin** [comment]
Hi,

Thank you for your reply. I hope the argument `--dmnd_evalue` will be available in the future release of eggNOG-mapper.

Best wishes

**Comment by Cantalapiedra** [comment]
Hi,

it will, hopefully very soon.
Thank you.
Best,
Carlos
