### ISSUE TITLE
I can't understand the  parameters --target_orthologs?

### ISSUE THREAD

**Issue by 1010stone** [eggnogdb/eggnog-mapper#237]
Which is the default selection for the parameters "--target_orthologs"? When I use emapper.py to annotate Brassica napus proteins,    I can get so  many GO annotations (more than 2 million), this result is much larger than interproscan . I want to decrease the result, so I set the e-value(1e-5) and --go_evidence (experimental),but the GO annotations are still  more than 1.7 million, will  the parameters "--target_orthologs" be helpful for  this question
` ./emapper.py  -i all.v0.simply.pep -o ann_go_new --data_dir ~/miniconda3/envs/rna/lib/python2.7/site-packages/data -m diamond --cpu 80 --dmnd_db ~/miniconda3/envs/rna/lib/python2.7/site-packages/data/eggnog_proteins.dmnd --seed_ortholog_evalue 1e-5 --keep_mapping_files --go_evidence experimental`

**Comment by Cantalapiedra** [comment]
Hi,

you could try --target_orthologs one2one
Also, you may try with --tax_scope , using a tax ID (check the ID for plants, Brassica, or whatever level fits you data) to limit the taxonomic scope used to retrieve annotations.
