### ISSUE TITLE
Fatal exception

### ISSUE THREAD

**Issue by TUANNN518** [eggnogdb/eggnog-mapper#239]
Hello,
I installed the eggnog-mapper-master and i got the fatal exception below, befor i installed the eggnog-mapper-1.0.3 and i got the same error. please help me, very thanks.

Sequence mapping starts now!
**Fatal exception (source file ../../../src/impl_sse/vitfilter.c, line 105):
Fast filter only works for local alignment**
 Processed queries:1 total_time:44.7708318233 rate:0.02 q/s
Hit refinement starts now
 Processed queries:1 total_time:4.80825805664 rate:0.21 q/s
Reading HMM matches
Functional annotation of refined hits starts now
 Processed queries:0 total_time:0.13599395752 rate:0.00 q/s
Done
   test.emapper.hmm_hits
   test.emapper.seed_orthologs
   test.emapper.annotations
Total time: 49.9008 secs

**Comment by Cantalapiedra** [comment]
Hi,

which specific command-parameters are you running?
Also, can you run emapper.py --version
Note that current eggnog-mapper version at master branch should use '-m diamond' only.
hmmer search is not supported in such version.

Thank you
Carlos

**Comment by TUANNN518** [comment]
> Hi,
> 
> which specific command-parameters are you running?
> Also, can you run emapper.py --version
> Note that current eggnog-mapper version at master branch should use '-m diamond' only.
> hmmer search is not supported in such version.
> 
> Thank you
> Carlos

Thank you for your reply.
I have used the eggnog-mapper-1.0.3 '-m diamond', and got the result. It still not work using hmmer search, probably because the file is not downloaded completely.
Anyway, the problem was temporarily solved using '-m diamond'.

**Comment by Cantalapiedra** [comment]
Hi,

nice if it was solved. Please, issue again or re-open in case you have further problems.

Best,
Carlos
