### ISSUE TITLE
annotate_hits_table does not recognize bactNOG fields?

### ISSUE THREAD

**Issue by sapuizait** [eggnogdb/eggnog-mapper#242]
Hi 
I am using a local bactNOG databases to produce annotations for multiple fasta files
using the output of the above I pass them to emapper in order to create annotation tables

$emapper.py --annotate_hits_table /home/sauron/tmp/whaaaat --no_file_comments --override -o output_file --cpu 2

the bactNOG fields look like this
k127_277842_2	bactNOG.ENOG4105C0Z.clustalo_raw	2.7e-33	118.1
k127_277843_1	bactNOG.ENOG4105C3P.meta_raw	8.6e-36	126.9
k127_277844_1	bactNOG.ENOG4107ICE.meta_raw	9.7e-83	279.7
k127_277844_2	bactNOG.ENOG4105IXE.meta_raw	7.6e-118	397.0
k127_277844_3	bactNOG.ENOG4105FHF.meta_raw	2.1e-31	112.3
k127_277844_4	bactNOG.ENOG4107IZ8.meta_raw	1.1e-46	159.1
k127_277844_6	bactNOG.ENOG4106QZV.meta_raw	0.0047	18.5
k127_277844_7	bactNOG.ENOG4107R2X.meta_raw	1.1e-51	178.8
k127_277845_1	bactNOG.ENOG4108R6K.meta_raw	1.4e-81	277.0
k127_277846_1	bactNOG.ENOG41086KK.meta_raw	3.3e-37	131.4
k127_277848_1	bactNOG.ENOG4108MB8.meta_raw	4.8e-62	212.7
k127_277848_2	bactNOG.ENOG4105C1B.meta_raw	4.3e-49	170.3
k127_277849_1	bactNOG.ENOG41065J2.meta_raw	0.0081	17.9

however emapper does not recognize these bactNOG fields but it will recognize the following:
k127_3_1	350688.Clos_1159	6.6e-38	163.7
k127_4_1	1203602.HMPREF1527_01027	1.3e-44	186.0

therefore my question is: which database do I have to use (instead of bactNOG) in order to get emapper to recognize the fields? or alternatively is there an option for bactNOG?

**Comment by Cantalapiedra** [comment]
Hi @sapuizait ,

the identifiers on the second column should be identifiers of eggNOG proteins, with the format:
tax_ID.eggnog_prot_ID

That is why "1203602.HMPREF1527_01027" it is working, since:
1203602 is a tax ID
and
HMPREF1527_01027 is a valid eggnog5 protein ID

You can find such protein at http://eggnog5.embl.de/

Best,
Carlos
