### ISSUE TITLE
Is one2one giving too many matches or am I interpreting output wrong?

### ISSUE THREAD

**Issue by dominicev** [eggnogdb/eggnog-mapper#243]
I am noticing that eggNOG mapper gives the same ortholog prediction for multiple contigs in a single assembly even with the one2one option. My understanding of a one2one ortholog is that the database and the query should both have a single copy of that ortholog in order for it to be annotated. The way I am interpreting my output is that the `seed_eggNOG_ortholog` column is the predicted name of the ortholog for the specified contig in the assembly. Am I misunderstanding the definition, my output, or is something else going on?

**Comment by Cantalapiedra** [comment]
Hi @dominicev ,

one2one means that annotations will be transferred to your query only from those orthologs with a one2one relationship with the seed_ortholog. In this sense, one2one means that there is no other ortholog from the same species. Note that depending on the taxonomic scope and the specific orthologous group, there will be cases where the one2one or one2many or all, whichever option makes no difference at all. However, in some cases you could expect less annotations from one2one relationships in comparison with retrieving all orthologs (including in-paralogs). Maybe @jhcepas could add something or correct in case I am being not completely accurate.

The seed_ortholog is the hit that was found when aligning your query to the eggnog5 proteins DB. Therefore, it can be considered as homolog. However, the seed_ortholog is used to retrieve the orthologs from the same orthologs group, tha latter chosen depending on taxonomic scope.

I hope this makes sense.

Best,
Carlos
