### ISSUE TITLE
MMseqs2 --sub-mat option

### ISSUE THREAD

**Issue by genomewalker** [eggnogdb/eggnog-mapper#244]
Hi
I have been trying the new refactor branch, and it looks awesome! Any plans to add the `--sub-mat` option for MMseqs2 to use alternative substitution matrices?

Thanks
Antonio

**Comment by jhcepas** [comment]
We didn't think about it, but it actually sounds useful for metaG annotations... @Cantalapiedra should be easy to implement.

**Comment by Cantalapiedra** [comment]
Hi,

thank you @genomewalker for your kind words and your advice.
You should find the option already available in the refactor branch.
I did not tested though.

Best,
Carlos

**Comment by genomewalker** [comment]
Super @Cantalapiedra! I will try it and come back to you. It is excellent you included MMseqs2! 

Do you have plans to include profile searches as well?


Thanks!
Antonio

**Comment by Cantalapiedra** [comment]
Glad that the MMseqs2 search is useful for you @genomewalker !

About profile searches, it could be a nice addition for next releases. However, we not for the incoming release, since we are about to ... release it yet.

Best,
Carlos

**Comment by genomewalker** [comment]
> Glad that the MMseqs2 search is useful for you @genomewalker !

Super useful! I already was using MMseqs2 instead of diamond with the v2.0. Better sensitivity and speed (I was using the MPI version). Milot added an [option](https://github.com/soedinglab/MMseqs2/issues/249) to the `filterdb` module similar to the diamond's `--top` to replicate the eggnog-mapper behaviour. Having MMseqs2 now natively is awesome. Many thanks!

> About profile searches, it could be a nice addition for next releases. However, we not for the incoming release, since we are about to ... release it yet.

Indeed for certain applications, the profile search would be great. 

> You should find the option already available in the refactor branch.
I did not tested it though.

I tested it, and it worked. I also have seen that you fixed `download_eggnog_data.py`. [Here](https://github.com/eggnogdb/eggnog-mapper/blob/refactor/download_eggnog_data.py#L36-L46) it still will fail when using `-f` as the `gunzip_flag()` doesn't work with `tar`.

Again, many thanks!
Antonio

**Comment by Cantalapiedra** [comment]
> > Glad that the MMseqs2 search is useful for you @genomewalker !
> 
> Super useful! I already was using MMseqs2 instead of diamond with the v2.0. Better sensitivity and speed (I was using the MPI version). Milot added an [option](https://github.com/soedinglab/MMseqs2/issues/249) to the `filterdb` module similar to the diamond's `--top` to replicate the eggnog-mapper behaviour. Having MMseqs2 now natively is awesome. Many thanks!

If you were using the MPI version, then maybe you will prefer to use eggnog-mapper just for annotation. I am also considering adding the option --db-load-mode 2 (or --db-load-mode 3, not sure yet), for the emapper --usemem option. What are your thoughts on both MPI use and --db-load-mode?

> 
> > About profile searches, it could be a nice addition for next releases. However, we not for the incoming release, since we are about to ... release it yet.
> 
> Indeed for certain applications, the profile search would be great.
> 

I have checked MMseqs2 docs, and I would expect emapper running using a profile file as input, although I have not tried it yet. Also, a good option would be to add the "--num-iterations 2" option from MMseqs2. Maybe you meant the latter.

> > You should find the option already available in the refactor branch.
> > I did not tested it though.
> 
> I tested it, and it worked. I also have seen that you fixed `download_eggnog_data.py`. [Here](https://github.com/eggnogdb/eggnog-mapper/blob/refactor/download_eggnog_data.py#L36-L46) it still will fail when using `-f` as the `gunzip_flag()` doesn't work with `tar`.

Thank you very much! Already fixed that also. I will upload it to the github repo soon.

> 
> Again, many thanks!
> Antonio

Many thanks to you. Very helpful indeed.

Best,
Carlos

**Comment by genomewalker** [comment]
> If you were using the MPI version, then maybe you will prefer to use eggnog-mapper just for annotation. I am also considering adding the option --db-load-mode 2 (or --db-load-mode 3, not sure yet), for the emapper --usemem option. What are your thoughts on both MPI use and --db-load-mode?

This is what we were doing... search with MMseqs2, massage the results like emapper does and then annotate.  Regarding the `--db-load-mode` it will depend on the needs of the user and how many queries one wants to search, if the indices will be reused... In our case, we have an extremely large number of queries and the MPI version of MMseqs2 speeds up the whole process. I am sure @martin-steinegger can provide better insights here :-)

> I have checked MMseqs2 docs, and I would expect emapper running using a profile file as input, although I have not tried it yet. Also, a good option would be to add the "--num-iterations 2" option from MMseqs2. Maybe you meant the latter.

I was thinking on using a profile DB, similar to what the module `database` from MMseqs2 does [here](https://github.com/soedinglab/MMseqs2/blob/master/data/workflow/databases.sh#L175-L184) and [here](https://github.com/soedinglab/MMseqs2/blob/master/data/workflow/databases.sh#L303-L317) using the eggNOG alignments you created for the HMMs. The `--num-iterations` also can be useful for a PSI-BLAST search

Thanks @Cantalapiedra 
Antonio

**Comment by Cantalapiedra** [comment]
> > If you were using the MPI version, then maybe you will prefer to use eggnog-mapper just for annotation. I am also considering adding the option --db-load-mode 2 (or --db-load-mode 3, not sure yet), for the emapper --usemem option. What are your thoughts on both MPI use and --db-load-mode?
> 
> This is what we were doing... search with MMseqs2, massage the results like emapper does and then annotate. Regarding the `--db-load-mode` it will depend on the needs of the user and how many queries one wants to search, if the indices will be reused... In our case, we have an extremely large number of queries and the MPI version of MMseqs2 speeds up the whole process. I am sure @martin-steinegger can provide better insights here :-)
> 

Yes, the --db-load-mode could be interesting mainly for us (for the web, for example), but I was wondering if other users could find it useful too. Regarding MPI, yes, I meant that, that if you are currently using MPI and have many queries then current MMseqs2 implementation within eggnog-mapper maybe is not so helpful.

> > I have checked MMseqs2 docs, and I would expect emapper running using a profile file as input, although I have not tried it yet. Also, a good option would be to add the "--num-iterations 2" option from MMseqs2. Maybe you meant the latter.
> 
> I was thinking on using a profile DB, similar to what the module `database` from MMseqs2 does [here](https://github.com/soedinglab/MMseqs2/blob/master/data/workflow/databases.sh#L175-L184) and [here](https://github.com/soedinglab/MMseqs2/blob/master/data/workflow/databases.sh#L303-L317) using the eggNOG alignments you created for the HMMs. The `--num-iterations` also can be useful for a PSI-BLAST search

OK. This is something that we could address if we decide to offer again the eggnog HMM databases to download. However, I would need to figure out how to identify a proper seed ortholog, I guess.

> 
> Thanks @Cantalapiedra
> Antonio

Thank you very much for the ideas and for reporting bugs :D 

Best,
Carlos
