### ISSUE TITLE
Map KEGG pathway

### ISSUE THREAD

**Issue by lalalagartija** [eggnogdb/eggnog-mapper#251]
Hi, 
It is very convinient that you give the kegg pathway directly in the output but how can I map it on KEGG pathways to visualize it  and how to understand the format ?
I get for example this output : ko03013,ko03440,ko04214,map03013,map03440,map04214
 Why does it has several KO and map ?

Thank you !

**Comment by Cantalapiedra** [comment]
Hi @lalalagartija ,

Maybe this could be of help:
https://www.genome.jp/kegg/kegg3a.html

and also you could compare:

https://www.genome.jp/kegg-bin/show_pathway?map03013
https://www.genome.jp/kegg-bin/show_pathway?ko03013

And you could wish to take a look at:

https://pubmed.ncbi.nlm.nih.gov/31423653/
https://www.genome.jp/kegg/mapper.html

Best,
Carlos

**Comment by lalalagartija** [comment]
Thank you ! I manage to view my gene in a pathway not through the KEGG pathway output but just the individual ko per gene entered in KEGG mapper. Nevertheless, this tool is not really appropriate for metagenomics to I will have to consider another way.
