### ISSUE TITLE
MMseqs sens parameters type

### ISSUE THREAD

**Issue by genomewalker** [eggnogdb/eggnog-mapper#252]
Hi @Cantalapiedra 
the [--start_sens](https://github.com/eggnogdb/eggnog-mapper/blob/refactor/emapper.py#L147-L148) and [--final_sens](https://github.com/eggnogdb/eggnog-mapper/blob/refactor/emapper.py#L150-L154) parameters should be float instead of int.

Many thanks!
Antonio

**Comment by Cantalapiedra** [comment]
Hi Antonio,

you are completely right! Thank you!

Best,
Carlos
