### ISSUE TITLE
Diamond database compatibility

### ISSUE THREAD

**Issue by urihs** [eggnogdb/eggnog-mapper#253]
Hi, I've been using eggNOG-mapper and I find it very useful, thank you

I've recently been having a problem with the tool though. For compatibility with another tool, I need to load a different Diamond version to my PATH. For some reason, the moment I do so emapper.py takes it as the default. This creates an incompatibility error with the database, so I need to create and select a compatible one with --dmnd_db when calling eggnog.

However, when I try to select the database, I need to specify the absolute path. If I use a relative path, it returns an error. This happens both when I launch the job with Slurm and when I launch it at the terminal, and it even affects the original diamond version and database:

> -bash-4.2$ eggnog-mapper-master/emapper.py -m diamond --no_annot --no_file_comments --cpu 24 -i ./protein_faa_reps/bacteria/RS_GCF_002752555.1_protein.faa -o RS_GCF_002752555.1 --output_dir consensus_models/Node35562/annotated_genomes/ --temp_dir /dev/shm **--dmnd_db eggnog-mapper-master/data/eggnog_proteins.dmnd** --override
/lustre/proyectos/microbioma/Silvia/SCRIPT/eggnog-mapper-master/bin/diamond /lustre/proyectos/microbioma/Silvia/SCRIPT/eggnog-mapper-master
> _#_  emapper-2.0.1
> _#_ ./emapper.py  -m diamond --no_annot --no_file_comments --cpu 24 -i ./protein_faa_reps/bacteria/RS_GCF_002752555.1_protein.faa -o RS_GCF_002752555.1 --output_dir consensus_models/Node35562/annotated_genomes/ --temp_dir /dev/shm --dmnd_db eggnog-mapper-master/data/eggnog_proteins.dmnd --override
>  /lustre/proyectos/microbioma/Silvia/SCRIPT/eggnog-mapper-master/bin/diamond blastp -d eggnog-mapper-master/data/eggnog_proteins.dmnd -q /lustre/proyectos/microbioma/Silvia/SCRIPT/protein_faa_reps/bacteria/RS_GCF_002752555.1_protein.faa --more-sensitive --threads 24 -e 0.001000 -o /dev/shm/emappertmp_dmdn__N2Sbl/d52e7227bdcc4529b485b441cd0c4291 --top 3 --query-cover 0 --subject-cover 0
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

> #CPU threads: 24
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /dev/shm/emappertmp_dmdn__N2Sbl
Opening the database... No such file or directory
 [0.000368s]
Error: Error opening file eggnog-mapper-master/data/eggnog_proteins.dmnd
Traceback (most recent call last):
  File "eggnog-mapper-master/emapper.py", line 1216, in <module>
    main(args)
  File "eggnog-mapper-master/emapper.py", line 226, in main
    dump_diamond_matches(args.input, seed_orthologs_file, args)
  File "eggnog-mapper-master/emapper.py", line 380, in dump_diamond_matches
    raise e
subprocess.CalledProcessError: Command '/lustre/proyectos/microbioma/Silvia/SCRIPT/eggnog-mapper-master/bin/diamond blastp -d eggnog-mapper-master/data/eggnog_proteins.dmnd -q /lustre/proyectos/microbioma/Silvia/SCRIPT/protein_faa_reps/bacteria/RS_GCF_002752555.1_protein.faa --more-sensitive --threads 24 -e 0.001000 -o /dev/shm/emappertmp_dmdn__N2Sbl/d52e7227bdcc4529b485b441cd0c4291 --top 3 --query-cover 0 --subject-cover 0' returned non-zero exit status 1

However, when I use the absolute path everything works perfectly:

> -bash-4.2$ eggnog-mapper-master/emapper.py -m diamond --no_annot --no_file_comments --cpu 24 -i ./protein_faa_reps/bacteria/RS_GCF_002752555.1_protein.faa -o RS_GCF_002752555.1 --output_dir consensus_models/Node35562/annotated_genomes/ --temp_dir /dev/shm --dmnd_db **$PWD**/eggnog-mapper-master/data/eggnog_proteins.dmnd --override
> /lustre/proyectos/microbioma/Silvia/SCRIPT/eggnog-mapper-master/bin/diamond /lustre/proyectos/microbioma/Silvia/SCRIPT/eggnog-mapper-master
> _#_  emapper-2.0.1
> _#_ ./emapper.py  -m diamond --no_annot --no_file_comments --cpu 24 -i ./protein_faa_reps/bacteria/RS_GCF_002752555.1_protein.faa -o RS_GCF_002752555.1 --output_dir consensus_models/Node35562/annotated_genomes/ --temp_dir /dev/shm --dmnd_db /home/silviatm/SCRIPT/eggnog-mapper-master/data/eggnog_proteins.dmnd --override
>   /lustre/proyectos/microbioma/Silvia/SCRIPT/eggnog-mapper-master/bin/diamond blastp -d /home/silviatm/SCRIPT/eggnog-mapper-master/data/eggnog_proteins.dmnd -q /lustre/proyectos/microbioma/Silvia/SCRIPT/protein_faa_reps/bacteria/RS_GCF_002752555.1_protein.faa --more-sensitive --threads 24 -e 0.001000 -o /dev/shm/emappertmp_dmdn_eifLgY/55e50f58c60e44b184213c9b6cedbce0 --top 3 --query-cover 0 --subject-cover 0
> diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
> Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
> Check http://github.com/bbuchfink/diamond for updates.
> 
> #CPU threads: 24
> Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
> Temporary directory: /dev/shm/emappertmp_dmdn_eifLgY
> Opening the database...  [0.002093s]
> Percentage range of top alignment score to report hits: 3
> Opening the input file...  [0.008875s]
> Opening the output file...  [6e-05s]
> Loading query sequences...  [0.048514s]
> Masking queries...  [0.045257s]
> Building query seed set...  [0.000465s]
> Algorithm: Double-indexed
> Building query histograms...  [0.028293s]
> Allocating buffers...  [0.000579s]

I think this behaviour might be a bug, and if it is it might be worth reporting.

Also, is it possible to mannually specify what version of Diamond I want to use? I would prefer not to switch databases.

Thank you

**Comment by Cantalapiedra** [comment]
Hi @urihs ,

Thank you for reporting this.

You are right, this looks like a bug in 2.0.1 version, since I tested something similar to this:

i) in the "2.0.1b" version, and it fails 
ii) in the "refactor" branch version, and it seems to work fine

It seems that version 2.0.1 is changing current working dir to the output dir, whereas the refactor version does not do this. I guess that the script is looking for your relative path from "consensus_models/Node35562/annotated_genomes/", which is wrong, of course.

However, your workaround using the absolute path looks fine to me. Other options could be changing PATH when running emapper.py and the other tool, or using a different environment, with different diamond version on it. Another option I can think of is using the PATH to a directory where you have a link to the diamond binary, and you change this link for the different diamond versions. Unfortunately, there is no way to specify manually the version of diamond to use within eggnog-mapper.

I hope this is of help, and thanks again.

Best,
Carlos

**Comment by urihs** [comment]
Ok, thank you for your answer :)
