### ISSUE TITLE
There is any problem to use basta taxonomic annotation  ?

### ISSUE THREAD

**Issue by EulleSA** [eggnogdb/eggnog-mapper#259]
I'm developing a pipeline for metagenomics analysis and I'm using eggnog for functional annotation and next, I accomplish the taxonomic annotation with BASTA software. There is any problem to use with the output of the eggnog functional annotation to accomplish taxonomic annotation with another software?

Thanks in advance.

**Comment by Cantalapiedra** [comment]
I am not familiar with BASTA. I guess if you could create the input tabular file from the taxonomic ID of OGs from emapper annotations you could try to use it.

Best,
Carlos
