### ISSUE TITLE
How to download version2

### ISSUE THREAD

**Issue by lufuhao** [eggnogdb/eggnog-mapper#260]
Hi, I can see in the wiki, version2 support python3, but can not find the access to it. 

currently the codes on github is still based on python2. And latest ubuntu 20's python is python3 by default. So the Shebang will use python3 rather than python2 to interpret.

Is there any chance we can get the python3 support asap?

**Comment by Cantalapiedra** [comment]
Hi @lufuhao ,

You could clone the version under the "refactor" branch.

Best,
Carlos

**Comment by lufuhao** [comment]
Yes, I can see that. Thank you so much.

**Comment by Cantalapiedra** [comment]
Anytime.
Best,
Carlos

**Comment by 0xaf1f** [comment]
Hi, @Cantalapiedra , is it possible for you to cut a release based on the Python 3 version so that a bioconda package could be built from it? They won't package arbitrary Git snapshots.

Many thanks and regards

**Comment by Cantalapiedra** [comment]
Hi @0xaf1f ,

we are working on it. Sorry for the inconveniences.

Best,
Carlos
