### ISSUE TITLE
Why --subject-cover is 0 by default  (diamond search) ?

### ISSUE THREAD

**Issue by matrs** [eggnogdb/eggnog-mapper#262]
Hello, 
first, thanks for this free software.

I have a question, when using `emapper.py -m diamond`,  the "subject coverage" is 0 by default. What's the rationale behind it?  In which circumstances changing this setting can improve my results?

Regards

Jose Luis

**Comment by Cantalapiedra** [comment]
Hi @matrs ,

I guess the parameters and thresholds used to filter out the results from an analysis are not a clear line. If you think/feel/believe that your results will be best using subject coverage as a parameter it is ok. I often use query coverage myself, along with percentage identity. By default, eggnog-mapper is configured to use e-value mainly, but it gives you the option to change this.

Regarding subject coverage specifically, I guess that the larger the value the more confident you will be on the similarity between your query and the subject. However, you could miss some true positives, for example if using subject coverage to 1.0 (or 100%), which is just not realistic unless you try to identify exact or almost exact hits.

I hope all this makes sense.

Best,
Carlos
