### ISSUE TITLE
empty eggNOG free text desc.

### ISSUE THREAD

**Issue by chenyj8** [eggnogdb/eggnog-mapper#264]
Hi,

In the output file there are some queries with empty eggNOG free text desc. What does that mean? Does that mean those queries are functionally unknown?

**Comment by Cantalapiedra** [comment]
Hi @chenyj8 ,

what eggnog-mapper version are you using? web? standalone 1.0, 2.0 or refactor?
In some cases the description will be empty when no enough orthologs support the same description.

Best,
Carlos
