### ISSUE TITLE
`best_og_name` isn't the one from "narr_og_name"/"tax_scope"

### ISSUE THREAD

**Issue by matrs** [eggnogdb/eggnog-mapper#265]
Hello,
sorry for this, i believed I had found a bug related to  `best_og_name`  "narr_og_name"/"tax_scope"  options, but I had an error en i code, so this isn't an actual problem/bug
```
# emapper-2.0.4-rf1
# /home/jmaturana/Sofware/eggnog-mapper/emapper.py --cpu 24 -i core_genes.fasta --output blau_all \
--output_dir  dir -m diamond --data_dir  ggmapper_dbs  --tax_scope 572511 \
--go_evidence non-electronic --target_orthologs all --seed_ortholog_evalue 0.001 \
--seed_ortholog_score 60 --query_cover 20 --subject_cover 0 --usemem --override
```
In the annotation file, I noticed  multiple lines like  `COG2972@1|root,COG2972@2|Bacteria,1TPVR@1239|Firmicutes,247XB@186801|Clostridia,3Y1P8@572511|Blautia`, 	
`narrow_og_name` `3Y1P8@572511|Blautia` , but all the `best_og_name`	have Firmicutes in it, like `1TPVR@1239|Firmicutes`. I tried this because i got the same result using `--tax_scope 572511,186801,1239,2`, so i wanted to check if I didn't understand properly how `tax_scope` works. From the list of tax ids, I expect to get the left-most one as the `best_og_name`, but I'm only getting "Firmicutes" or "Bacteria". I'm using the the latest eggnog db downloaded with `download_eggnog_data.py`

```python
taxa_blau['best_og_name'].str.split('|', expand=True)[1].value_counts()
Firmicutes    302
Bacteria        1
Name: 1, dtype: int64
```

Regards,

Jose Luis

**Comment by Cantalapiedra** [comment]
Hi @matrs ,

Certainly, what you described looked like a bug. I am glad it seems that is finally not, and that you were able to figure it out.

In general, --tax_scope works as you described. Note however, that there could be some cases in which your best_OG is not the one left-most one, even when it is included in the list of OGs. This should happen only when the OG from the left-most one is not yielding a valid set of orthologs, but this should only happen on rare occasions.

Best,
Carlos
