### ISSUE TITLE
How to count map pathway?

### ISSUE THREAD

**Issue by zckoo007** [eggnogdb/eggnog-mapper#266]
Hi  Cantalapiedra,

I found one gene matches several KEGG_pathway, 
When I start counting, should I choose the first one, or do I count every one？

![image](https://user-images.githubusercontent.com/25576334/103520424-1a75b900-4eb2-11eb-830c-5f1e132b7246.png)

For example
#### eggnog output file
```
Name	KEGG_Pathway
gene1	map00001,map00002,map00003
gene2	map00004
gene3	map00001,map00005
gene4	map00005	
gene5	map00001	
```
#### gene cout file
```
Name	Samp1	Samp2	Samp3	Samp4
gene1	1	1	1	1
gene2	1	1	1	1
gene3	1	1	1	1
gene4	1	1	1	1
gene5	1	1	1	1
```
--------------------------------------------------------------------------------------------
# count by sum

```
ID	Samp1	Samp2	Samp3	Samp4
map00001   3   3   3   3
map00002   1  1   1   1  
map00003   1   1   1   1
map00004   1   1   1   1   
map00005   2   2   2   2
```

# count by first one

```
ID	Samp1	Samp2	Samp3	Samp4
map00001   3   3   3   3
map00002   0   0   0   0 
map00003   0   0   0   0
map00004   1   1   1   1   
map00005   1    1   1   1
```

**Comment by Cantalapiedra** [comment]
Hi,

I am not expert on (enrichment?) this. I guess the most straightforward would be counting all of them, but it will depend on the analyses you are carrying out.

Best,
Carlos

**Comment by Lix1993** [comment]
Rather than count them manually, I think you can use gsva instead.

**Comment by Cantalapiedra** [comment]
Please, re-open or re-issue if needed.

Best,
Carlos
