### ISSUE TITLE
disk I/O error while  annotating seed_orthologs

### ISSUE THREAD

**Issue by Lix1993** [eggnogdb/eggnog-mapper#267]
error message:

```python
Traceback (most recent call last):
  File "/share/software/eggnog-mapper/emapper.py", line 1216, in <module>
    main(args)
  File "/share/software/eggnog-mapper/emapper.py", line 275, in main
    annotate_hits_file(seed_orthologs_file, annot_file, hmm_hits_file, args)
  File "/share/software/eggnog-mapper/emapper.py", line 750, in annotate_hits_file
    og_cat, og_desc = annota.get_best_og_description(match_nogs)
  File "/share/software/eggnog-mapper/eggnogmapper/annota.py", line 45, in get_best_og_description
    for og, nm, desc, cat in db.fetchall():
sqlite3.OperationalError: disk I/O error
```

my command：
```bash
python2 /share/software/eggnog-mapper/emapper.py -i unigene.fa --output_dir eggnog --output unigene --temp_dir eggnog_tmp --data_dir emapperdb-5.0.0/ -m diamond --cpu 80 --translate
```

**Comment by Lix1993** [comment]
here is the seed_orthologs file,

[unigene.emapper.seed_orthologs,txt](https://github.com/eggnogdb/eggnog-mapper/files/5786323/unigene.emapper.seed_orthologs.txt)

**Comment by Lix1993** [comment]
it works for a smaller gene set, 
and program seems break randomly

i run the command  2 times, 

first i get 33040 lines annotation ,
while second there are only 105 lines

**Comment by Cantalapiedra** [comment]
Hi @Lix1993 ,

sorry for the delay answering.
What eggnog-mapper version are you using? (emapper.py --version)
Also, are the eggnog-mapper databases in a NFS? Specially, the sqlite3 database (eggnog.db) often leads to problems when in a NFS.

**Comment by Lix1993** [comment]
When i copy the database to local dir,  it works. 

So this may be a nfs I/O problem with sqlite3.

Thanks for your reply.
