### ISSUE TITLE
release based on Python 3

### ISSUE THREAD

**Issue by 0xaf1f** [eggnogdb/eggnog-mapper#272]
I saw https://github.com/eggnogdb/eggnog-mapper/issues/260 where it's pointed out that the `refactor` branch has a Python3-compatible version of the code. I commented there, but perhaps this is better as its own issue.

We're doing a Python3 migration for software that we wrote that uses eggnog-mapper and we can't simply pass the same dependency list after switching because eggnog-mapper has to be manually pulled out of a snapshot. This also causes issues for us for distributing our software from conda.

Would you create an official release of eggnog-mapper using the Python 3 version of the code?

**Comment by Cantalapiedra** [comment]
Related to / same actions to be taken than #250
