### ISSUE TITLE
Use DIAMOND output file as input for eggnog-mapper

### ISSUE THREAD

**Issue by MazzaMezze** [eggnogdb/eggnog-mapper#273]
Hi, 

Thanks for developing eggnog-mapper, it's a super useful tool! 

I have a question: is it possible to use a DIAMOND output file as input for eggnog-mapper? I'd like to run DIAMOND externally, but still use Eggnog-mapper for functional annotation starting from DIAMOND's `.m8` output file. 

I am aware of the parameters to start eggnog-mapper from the `.seed_orthologs` file, or to run eggnog-mapper from an input fasta file to generate the `.seed_orthologs` file, but is there any way to provide a DIAMOND output file itself as input? 

Cheers, 
M.

**Comment by Cantalapiedra** [comment]
Hi @MazzaMezze ,

glad that emapper is useful for you!
It is not possible to use the diamond output file directly as parameter for --annotate_hits_table. It would be a nice thing to have though. In the meanwhile you would need to transform your diamond's file to a seed_orthologs file, which should be rather straightforward:

An example of seed_orthologs file format:

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2-*refactor*#Seed_orthologs_file

You only need to extract 4 fields from diamond: query, target, evalue, bitscore. So, something like this would suffice (untested):

`cat diamond.out | cut -f 1,2,11,12 > diamond.seed_orthologs`

I hope it helps.

Best,
Carlos

**Comment by MazzaMezze** [comment]
Hi, 

Thanks for the quick reply! If I use your solution, should I also apply some filtering on the DIAMOND output (keep best hit only, e-value/bit score filter) or can I just dump it all?

**Comment by Cantalapiedra** [comment]
Hi @MazzaMezze ,

good question. I guess the safer would leaving a single hit per query. I have never tested the annotation step using more than one hit per query, so some features (pfam denovo alignment comes to my mind) may fail.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Currently, this could be approached also using the --resume option, including the file with Diamond hits in the output directory.
However, using --resume no filters will be applied in the search phase. Only those from the annotation phase (--seed_orthologs_score, for instance) will be applied. The user may wish to filter the Diamond hits file previous to run emapper though.

Best,
Carlos
