### ISSUE TITLE
Loading the eggNOG database onto SGC

### ISSUE THREAD

**Issue by shubavarshini** [eggnogdb/eggnog-mapper#277]
Hi,
I'm creating functional annotations for ~24K pangenomes. So for one set of genes to finish emapper.py takes 3-4 hour. They run faster if each gene set is assigned to different clustering machines. But they are very slow (takes more than a day)  if 10 (or so) gene sets are run simultaneous on one cluster machine. For each gene set I'm assigning cpu=10 (~30GB). Now I know there is a option to keep the database uploaded in ram (sorry if I'm saying it wrong). Can you please help me out and tell me what can I include to increase the run time of emapper.py.
Here is my script (modified) conditions that gets submitted to a SGC:
 #!/bin/bash

#$ -V
#$ -l vf=3G
#$ -pe multislot 10
#$ -b n
#$ -i /dev/null
#$ -cwd

emapper.py --cpu 10 -i $inFasta --translate --data_dir $dbPath --output $outPrefix --output_dir $outDir -m diamond -d none --tax_scope auto --go_evidence non-electronic --target_orthologs all --seed_ortholog_evalue 0.001 --seed_ortholog_score 60 --query-cover 20 --subject-cover 0 --override --temp_dir /tmp/

Thank you.

**Comment by Cantalapiedra** [comment]
Hi @shubavarshini ,

this depends a lot on the computers that are available to you. For example, you your compute nodes have a lot (>200 GB) RAM you could use -m mmseqs instead of -m diamond. Also, you could modify the sensitivity of the search, both with diamond and with mmseqs, with the different parameters available for them. Take a look at:

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.0.2-v2.0.6#search-options

Regardless of the previous, I would recommend you skipping the annotation step with --no_annot, and running the annotation step afterwards, as a second emapper.py run, using -m no_search --annotate_hits_table FILE, where "FILE" is the "emapper.seed_orthologs" file obtained from the first step (the diamond or mmseqs step). Also, this annotation step will benefit for having the eggnog.db loaded into memory, which you can do using --dbmem. This requires ~40GB RAM.

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.0.2-v2.0.6#annotation-options

Of course, if the DB is in a fast storage will be better than if it is a slower net storage. You can also modify the place where emapper.py writes the output using --output_dir, --temp_dir, and --scratch_dir.

In all the cases, you will benefit from sending as much sequences as possible to every node, to take advantage of the time spent loading the data into memory (either the MMseqs indexes, or the sqlite3 database with --dbmem).

Finally, there is currently another option. Depending on your input (for example, if working only with Bacteria data), you have the option to create smaller DBs with the create_dbs.py script. Having smaller DBs will make the search faster, and also will allow using MMseqs in computers with no so much RAM as what it is needed for the whole eggnog DB. You can find info about this here:

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.0.2-v2.0.6#setup

I hope any of this makes sense.

Best,
Carlos

**Comment by shubavarshini** [comment]
Thank you for the suggestions @Cantalapiedra. I'll try them but I have one quick question: I've already run half my gene sets using the parameters mentioned in my first message. Now hanging diamond to mmseqs or two step annotations (your second suggestion), would the results be very different? I'm only concerned if I have to rerun all the gene sets again to keep the parameters of run the same.

**Comment by Cantalapiedra** [comment]
Hi @shubavarshini ,

if you change diamond to mmseqs there will be some differences, but in our tests if you use similar sensitivity parameters the results, specially the annotations, will be very similar.

Running in one or two steps will change nothing.
I personally would run just the remaining gene sets, unless you really want to change sensitivity, cutoffs, taxonomic scope, etc.

Best,
Carlos

**Comment by shubavarshini** [comment]
Hey @Cantalapiedra,

Sorry to reopen the issue again. In my question I forgot to mention the version of emapper I'm using and it is emapper-2.0.1. This version does not have --dbmem option. 

Coming back to your suggestions. Below I have explained the various ways I could increase the query search for annotations but no matter which location the database is present the no. of queries processed is less than one per second. I also see that the database does not completely get onto memory even after suggesting it to (not sure I used the wrong parameter) as stated in this issue https://github.com/eggnogdb/eggnog-mapper/issues/74. I do not see a -c1 parameter in emapper help as the log file keeps indicating.
So as you suggested I did the following:
1. Included --usemem option (which seemed close to the description of --dbmem option) and put the eggnog.db on a SSD. Following is an example of the time take for annotation:
EXAMPLE 1:
Total time = 2516.98s
Reported 9149 pairwise alignments, 9149 HSPs.
3827 queries aligned.
The host system is detected to have 135 GB of RAM. It is recommended to use this parameter for better performance: -c1
500 54.1971650124 9.23 q/s (func. annotation)
1000 99.751458168 10.02 q/s (func. annotation)
1500 170.481554031 8.80 q/s (func. annotation)
2000 233.030315161 8.58 q/s (func. annotation)
2500 322.251776218 7.76 q/s (func. annotation)
3000 351.954100132 8.52 q/s (func. annotation)
3500 371.949692011 9.41 q/s (func. annotation)
EXAMPLE 2
Total time = 2941.09s
Reported 34861 pairwise alignments, 34861 HSPs.
6633 queries aligned.
The host system is detected to have 135 GB of RAM. It is recommended to use this parameter for better performance: -c1
500 24.1006889343 20.75 q/s (func. annotation)
1000 76.7370841503 13.03 q/s (func. annotation)
1500 134.182770967 11.18 q/s (func. annotation)
2000 159.310642958 12.55 q/s (func. annotation)
2500 200.023893118 12.50 q/s (func. annotation)
3000 256.116297007 11.71 q/s (func. annotation)
3500 290.809000015 12.04 q/s (func. annotation)
4000 313.343295097 12.77 q/s (func. annotation)
4500 337.025798082 13.35 q/s (func. annotation)
5000 377.14941597 13.26 q/s (func. annotation)
5500 410.662472963 13.39 q/s (func. annotation)
6000 439.065439939 13.67 q/s (func. annotation)
6500 462.704167128 14.05 q/s (func. annotation)

2.  Only put the eggnog.db on a SSD. Following is an example of the time take for annotation:
EXAMPLE 1:
Total time = 9508.67s
Reported 3178 pairwise alignments, 3178 HSPs.
1835 queries aligned.
The host system is detected to have 1964 GB of RAM. It is recommended to use this parameter for better performance: -c1
500 2422.60839415 0.21 q/s (func. annotation)
1000 2977.51131105 0.34 q/s (func. annotation)
1500 3848.49451804 0.39 q/s (func. annotation)
EXAMPLE 2:
Total time = 7049.09s
Reported 2129 pairwise alignments, 2129 HSPs.
1182 queries aligned.
The host system is detected to have 1964 GB of RAM. It is recommended to use this parameter for better performance: -c1
500 1064.48220396 0.47 q/s (func. annotation)
1000 2415.33953214 0.41 q/s (func. annotation)

3. Followed https://github.com/eggnogdb/eggnog-mapper/issues/80. Following is an example of the time take for annotation:
EXAMPLE 1:
Total time = 2695.67s
Reported 19046 pairwise alignments, 19046 HSPs.
7646 queries aligned.
The host system is detected to have 811 GB of RAM. It is recommended to use this parameter for better performance: -c1
500 832.357953072 0.60 q/s (func. annotation)
1000 1712.91443086 0.58 q/s (func. annotation)
1500 2701.83414507 0.56 q/s (func. annotation)
2000 4185.68198895 0.48 q/s (func. annotation)
2500 4777.89802098 0.52 q/s (func. annotation)
3000 5896.07213807 0.51 q/s (func. annotation)
3500 7160.33796287 0.49 q/s (func. annotation)
4000 8370.58011794 0.48 q/s (func. annotation)
4500 9280.40227699 0.48 q/s (func. annotation)
5000 10243.260679 0.49 q/s (func. annotation)
5500 11158.2268279 0.49 q/s (func. annotation)
EXAMPLE 2:
Total time = 2710.27s
Reported 28327 pairwise alignments, 28327 HSPs.
7521 queries aligned.
The host system is detected to have 811 GB of RAM. It is recommended to use this parameter for better performance: -c1
500 1088.10660195 0.46 q/s (func. annotation)
1000 1908.42817402 0.52 q/s (func. annotation)
1500 3173.41540098 0.47 q/s (func. annotation)
2000 4456.79085684 0.45 q/s (func. annotation)
2500 5042.87183595 0.50 q/s (func. annotation)
3000 5575.31319594 0.54 q/s (func. annotation)
3500 7028.57794094 0.50 q/s (func. annotation)
4000 8089.7774539 0.49 q/s (func. annotation)
4500 9554.01904297 0.47 q/s (func. annotation)
5000 10753.790652 0.46 q/s (func. annotation)

I'm trying to split the process as explained in your wiki https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.0.0-v2.0.1#Setting_up_large_annotation_jobs. 

But as such can you tell me what might be wrong with the database not being loaded onto memory. Any suggestions would be very helpful.
Thank you.
Shuba

**Comment by Cantalapiedra** [comment]
Hi @shubavarshini ,

> Hey @Cantalapiedra,
> 
> Sorry to reopen the issue again. In my question I forgot to mention the version of emapper I'm using and it is emapper-2.0.1. This version does not have --dbmem option.

Yes, unfortunately --dbmem option is available since 2.0.4: https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.0.2-v2.0.7#v204-rf1

> 
> Coming back to your suggestions. Below I have explained the various ways I could increase the query search for annotations but no matter which location the database is present the no. of queries processed is less than one per second. I also see that the database does not completely get onto memory even after suggesting it to (not sure I used the wrong parameter) as stated in this issue #74. I do not see a -c1 parameter in emapper help as the log file keeps indicating.

There is now way to load the DB into memory in versions prior to 2.0.4, sorry. The -c1 parameter claim may come from Diamond. This option is implemented also in new versions of emapper: https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.0.2-v2.0.7#v207

> So as you suggested I did the following:
> 
> 1. Included --usemem option (which seemed close to the description of --dbmem option) and put the eggnog.db on a SSD. Following is an example of the time take for annotation:

The --usemem is only useful for HMMER searches. It has no effect on Diamond searches nor on the annotation stage.

>    EXAMPLE 1:
>    Total time = 2516.98s
>    Reported 9149 pairwise alignments, 9149 HSPs.
>    3827 queries aligned.
>    The host system is detected to have 135 GB of RAM. It is recommended to use this parameter for better performance: -c1
>    500 54.1971650124 9.23 q/s (func. annotation)
>    1000 99.751458168 10.02 q/s (func. annotation)
>    1500 170.481554031 8.80 q/s (func. annotation)
>    2000 233.030315161 8.58 q/s (func. annotation)
>    2500 322.251776218 7.76 q/s (func. annotation)
>    3000 351.954100132 8.52 q/s (func. annotation)
>    3500 371.949692011 9.41 q/s (func. annotation)
>    EXAMPLE 2
>    Total time = 2941.09s
>    Reported 34861 pairwise alignments, 34861 HSPs.
>    6633 queries aligned.
>    The host system is detected to have 135 GB of RAM. It is recommended to use this parameter for better performance: -c1
>    500 24.1006889343 20.75 q/s (func. annotation)
>    1000 76.7370841503 13.03 q/s (func. annotation)
>    1500 134.182770967 11.18 q/s (func. annotation)
>    2000 159.310642958 12.55 q/s (func. annotation)
>    2500 200.023893118 12.50 q/s (func. annotation)
>    3000 256.116297007 11.71 q/s (func. annotation)
>    3500 290.809000015 12.04 q/s (func. annotation)
>    4000 313.343295097 12.77 q/s (func. annotation)
>    4500 337.025798082 13.35 q/s (func. annotation)
>    5000 377.14941597 13.26 q/s (func. annotation)
>    5500 410.662472963 13.39 q/s (func. annotation)
>    6000 439.065439939 13.67 q/s (func. annotation)
>    6500 462.704167128 14.05 q/s (func. annotation)
> 2. Only put the eggnog.db on a SSD. Following is an example of the time take for annotation:

This should actually show the same performance as the previous benchmarks, since the --usemem option should have no effect at all. It seems that you changed host. Maybe this could have some effect.

>    EXAMPLE 1:
>    Total time = 9508.67s
>    Reported 3178 pairwise alignments, 3178 HSPs.
>    1835 queries aligned.
>    The host system is detected to have 1964 GB of RAM. It is recommended to use this parameter for better performance: -c1
>    500 2422.60839415 0.21 q/s (func. annotation)
>    1000 2977.51131105 0.34 q/s (func. annotation)
>    1500 3848.49451804 0.39 q/s (func. annotation)
>    EXAMPLE 2:
>    Total time = 7049.09s
>    Reported 2129 pairwise alignments, 2129 HSPs.
>    1182 queries aligned.
>    The host system is detected to have 1964 GB of RAM. It is recommended to use this parameter for better performance: -c1
>    500 1064.48220396 0.47 q/s (func. annotation)
>    1000 2415.33953214 0.41 q/s (func. annotation)
> 3. Followed #80. Following is an example of the time take for annotation:
>    EXAMPLE 1:
>    Total time = 2695.67s
>    Reported 19046 pairwise alignments, 19046 HSPs.
>    7646 queries aligned.
>    The host system is detected to have 811 GB of RAM. It is recommended to use this parameter for better performance: -c1
>    500 832.357953072 0.60 q/s (func. annotation)
>    1000 1712.91443086 0.58 q/s (func. annotation)
>    1500 2701.83414507 0.56 q/s (func. annotation)
>    2000 4185.68198895 0.48 q/s (func. annotation)
>    2500 4777.89802098 0.52 q/s (func. annotation)
>    3000 5896.07213807 0.51 q/s (func. annotation)
>    3500 7160.33796287 0.49 q/s (func. annotation)
>    4000 8370.58011794 0.48 q/s (func. annotation)
>    4500 9280.40227699 0.48 q/s (func. annotation)
>    5000 10243.260679 0.49 q/s (func. annotation)
>    5500 11158.2268279 0.49 q/s (func. annotation)
>    EXAMPLE 2:
>    Total time = 2710.27s
>    Reported 28327 pairwise alignments, 28327 HSPs.
>    7521 queries aligned.
>    The host system is detected to have 811 GB of RAM. It is recommended to use this parameter for better performance: -c1
>    500 1088.10660195 0.46 q/s (func. annotation)
>    1000 1908.42817402 0.52 q/s (func. annotation)
>    1500 3173.41540098 0.47 q/s (func. annotation)
>    2000 4456.79085684 0.45 q/s (func. annotation)
>    2500 5042.87183595 0.50 q/s (func. annotation)
>    3000 5575.31319594 0.54 q/s (func. annotation)
>    3500 7028.57794094 0.50 q/s (func. annotation)
>    4000 8089.7774539 0.49 q/s (func. annotation)
>    4500 9554.01904297 0.47 q/s (func. annotation)
>    5000 10753.790652 0.46 q/s (func. annotation)
> 
> I'm trying to split the process as explained in your wiki https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.0.0-v2.0.1#Setting_up_large_annotation_jobs.
> 
> But as such can you tell me what might be wrong with the database not being loaded onto memory. Any suggestions would be very helpful.

Yes, unfortunately no way to load sqlite DB into memory in version 2.0.1. My suggestion, sincerely, is to update to a new version in which you can use the `--dbmem` option.
A note about benchmarking also, note that some of your previous tests could be different if you erase the host cache before running emapper.py, since the sqlite DB seems to cache previous searches, so that 2nd, 3rd search etc with the same queries usually runs much faster. Anyway, it is intriguing the results of your first test, which are faster than the second and third ones.
However, with --dbmem  you should achieve around 100-200 q/s at least.

> Thank you.
> Shuba

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Hi again,

I have been checking and your 3rd case should be copying the eggnog.db to /dev/shm, right?
It is weird that you got no boost from doing this.
Would you mind sharing the commands that you are running to copy the database and to run emapper.py afterwards?
Thank you.

Carlos

**Comment by shubavarshini** [comment]
Hi @Cantalapiedra ,

Yes i was expecting the 3rd case to work. I had downloaded the databases in my working directory (using download_eggnog_data.py) and I moved them to ~/anaconda3/envs/eggnog/lib/python2.7/site-packages/data/ using the linux command "mv". When I posted the issue I was running the emapper.py wrongly: dbPath=~/anaconda3/envs/eggnog/lib/python2.7/site-packages/data
emapper.py --cpu 10 -i $inFasta --translate --data_dir $dbPath --output ${outPrefix} --output_dir $outDir -m diamond  -d none --tax_scope auto --go_evidence non-electronic --target_orthologs all --seed_ortholog_evalue 0.001 --seed_ortholog_score 60 --query-cover 20 --subject-cover 0 --override --temp_dir /tmp/

Then I realised I was supposed to give /dev/shm as the database path, therefore changed it to:
dbPath=/dev/shm/
emapper.py --cpu 10 -i $inFasta --translate --data_dir $dbPath --output ${outPrefix} --output_dir $outDir -m diamond  -d none --tax_scope auto --go_evidence non-electronic --target_orthologs all --seed_ortholog_evalue 0.001 --seed_ortholog_score 60 --query-cover 20 --subject-cover 0 --override --temp_dir /tmp/

BUT the emapper.py exits with status 1 and the stdout file has the following:
/home/user/anaconda3/envs/eggnog/bin/diamond /home/user/anaconda3/envs/eggnog/lib/python2.7/site-packages
Annotation database data/eggnog.db not present. Use download_eggnog_database.py to fetch it

I know it is there. Do I have to download the database again in the python lib?

**Comment by Cantalapiedra** [comment]
Hi @shubavarshini ,

> Hi @Cantalapiedra ,
> 
> Yes i was expecting the 3rd case to work. I had downloaded the databases in my working directory (using download_eggnog_data.py) and I moved them to /home/user/anaconda3/envs/eggnog/lib/python2.7/site-packages/data/ using the linux command "mv". When I posted the issue I was running the emapper.py wrongly: dbPath=/home/user/anaconda3/envs/eggnog/lib/python2.7/site-packages/data

But you should move the databases to /dev/shm, not to /home/user/anaconda3/envs/eggnog/lib/python2.7/site-packages/data/

> emapper.py --cpu 10 -i $inFasta --translate --data_dir $dbPath --output ${outPrefix} --output_dir $outDir -m diamond -d none --tax_scope auto --go_evidence non-electronic --target_orthologs all --seed_ortholog_evalue 0.001 --seed_ortholog_score 60 --query-cover 20 --subject-cover 0 --override --temp_dir /tmp/
> 
> Then I realised I was supposed to give /dev/shm as the database path, therefore changed it to:
> dbPath=/dev/shm/

You should move the databases to that $dbPath

> emapper.py --cpu 10 -i $inFasta --translate --data_dir $dbPath --output ${outPrefix} --output_dir $outDir -m diamond -d none --tax_scope auto --go_evidence non-electronic --target_orthologs all --seed_ortholog_evalue 0.001 --seed_ortholog_score 60 --query-cover 20 --subject-cover 0 --override --temp_dir /tmp/
> 
> BUT the emapper.py exits with status 1 and the stdout file has the following:
> /home/user/anaconda3/envs/eggnog/bin/diamond /home/user/anaconda3/envs/eggnog/lib/python2.7/site-packages
> Annotation database data/eggnog.db not present. Use download_eggnog_database.py to fetch it
> 
> I know it is there. Do I have to download the database again in the python lib?

"it is there" do you mean in /dev/shm? there is where they should be.
/dev/shm works like a directory, but everything that you copy there is going to be loaded into memory (as you can see with top, htop or any system monitoring app)

So, I am not sure exactly what you did, but you should:
- move (I would better copy them) the databases as you did, but to /dev/shm
- run emapper as in your last example, with --data_dir /dev/shm
- remove the databases from /dev/shm once you finish

I think you are close!
Best,
Carlos

**Comment by shubavarshini** [comment]
Hey @Cantalapiedra ,

Thank you for the inputs. I'll try them.

**Comment by Cantalapiedra** [comment]
Sure, anytime.

**Comment by shubavarshini** [comment]
Hi @Cantalapiedra,

> So, I am not sure exactly what you did, but you should:
> 
> * move (I would better copy them) the databases as you did, but to /dev/shm
> * run emapper as in your last example, with --data_dir /dev/shm
I did the above. The database is in /dev/shm-
ls -ltr /dev/shm
total 47852036
-rw-r--r-- 1 salampal clusers 39715045376 Mar 19  2019 eggnog.db
-rw-r--r-- 1 salampal clusers  9285439161 Mar 19  2019 eggnog_proteins.dmnd

Then I run emapper:
-v emapper.py --cpu 10 -i $inFasta --translate **--data_dir /dev/shm** --output ${outPrefix} --output_dir $outDir -m diamond -d none --tax_scope auto --go_evidence non-electronic --target_orthologs all --seed_ortholog_evalue 0.001 --seed_ortholog_score 60 --query-cover 20 --subject-cover 0 --override --temp_dir /tmp/

emapper.py returns with exist status 1 and the stdout file says:
/home/salampal/anaconda3/envs/eggnog/bin/diamond /home/salampal/anaconda3/envs/eggnog/lib/python2.7/site-packages
Annotation database data/eggnog.db not present. Use download_eggnog_database.py to fetch it

Not sure why is emapper.py still looking in data/ path?
Am I supposed to change the permissions of the database files?

**Comment by Cantalapiedra** [comment]
Hi @shubavarshini ,

are you running emapper in the same computer?  or are you using a cluster or similar?

**Comment by shubavarshini** [comment]
Hi @Cantalapiedra ,

This makes more sense. Yes, I'm submitting the scripts to a (SGE) cluster. I'll include the copy part and check. Thank you for all the help so far.

**Comment by shubavarshini** [comment]
@Cantalapiedra,
Just a update and it worked. Here is the annotation rates:
163500 592.166419029 276.10 q/s (func. annotation)
164000 593.053544998 276.53 q/s (func. annotation)
164500 594.394269943 276.75 q/s (func. annotation)
Thanks for all the help @Cantalapiedra.
Regards,
Shuba

**Comment by Cantalapiedra** [comment]
Glad that is finally working!
And thank you for reporting
