### ISSUE TITLE
Missing  emapper.annotations file

### ISSUE THREAD

**Issue by Geize** [eggnogdb/eggnog-mapper#278]
Hi there, 

**I run emapper like this (my job script):**

```
#!  /bin/bash --login
#$ -cwd #Job will run from the current directory
#$ -pe smp.pe 12
#$ -l mem256 

module load apps/python/eggnog-mapper/2.0.5

emapper.py  --cpu $NSLOTS --scratch_dir ~/scratch -i aminoAcid.fa -o EggNOG 
```

**The output is only  emapper..seed_orthologs. 

And it crashed like this:**

```
#emapper-2.0.5-6
#emapper.py  --cpu 12 --scratch_dir ~/scratch -i aminoAcid.fa -o EggNOG
ESC[1;33m  /opt/apps/apps/python/eggnog-mapper/2.0.5/eggnogmapper/bin/diamond blastp -d /mnt/data-sets/eggnog-mapper/data/eggnog_proteins.dmnd -q /net/scratch2/..../aminoAcid.fa --threads 12 -e 0.001
 -o /net/scratch2/.../emappertmp_dmdn_nc72e2ss/1b82f03109ce4eb598a2c8f1c5aadd37 --query-cover 0 --subject-cover 0 --top 3 ESC[0m
ESC[32mFunctional annotation of refined hits starts nowESC[0m 
```

**It seems the jobscript is running. But stay in this "situation" forever.** 

Do you any idea why I got this message? I appreciate any tips. 

Best,
Geize.

**Comment by Cantalapiedra** [comment]
Hi @Geize ,

It could be a problem reading the sqlite from a NFS drive, but I am not sure.
I would try adding "--dbmem", like:

`emapper.py  --cpu $NSLOTS --scratch_dir ~/scratch -i aminoAcid.fa -o EggNOG --dbmem`

Also, when running large or many jobs, we usually recommend separating the search and annotation steps, something like:
`emapper.py  -m diamond --no_annot --cpu $NSLOTS --scratch_dir ~/scratch -i aminoAcid.fa -o EggNOG`
`emapper.py  -m no_search --annotate_hits_table EggNOG.emapper.seed_orthologs --cpu $NSLOTS --scratch_dir ~/scratch -i aminoAcid.fa -o EggNOG --dbmem`

Let me know if it helps.

Best,
Carlos

**Comment by Geize** [comment]
Hi Carlos, 

Thanks a lot. 

Running these two second commands work pretty well. 

But I'll still have to talk with IT services about sqlite. 

Thanks again. You save my life. 

Best,
Geize.

**Comment by Cantalapiedra** [comment]
Glad that it worked!
Best,
Carlos
