### ISSUE TITLE
single annotation from multi-fasta file

### ISSUE THREAD

**Issue by BishopCD** [eggnogdb/eggnog-mapper#279]
Hi,
New to eggNOG-mapper. Loaded a mutlifasta file. info.txt file recognizes all sequences in the file, but only the first sequence in the file is included in the annotation report. Not sure why. 

emapper_version	2.0
original_file	H_auto_hyp_CDS.fasta
job_input	/data/shared/emapper_jobs/user_data/MM_0io1nr30/query_seqs.fa
job_output	query_seqs.fa
job_output_dir	/data/shared/emapper_jobs/user_data/MM_0io1nr30
email	cbishop@stfx.ca
job_name	MM_0io1nr30
job_path	/data/shared/emapper_jobs/user_data/MM_0io1nr30
nseqs	1245
nsites	337419
seq_type	aa
job_cpus	6
database	none
go_evidence	non-electronic
search_mode	diamond
orthology_type	all
seed_evalue	0.001
seed_score	60
query_cov	20
subject_cov	0
tax_scope	2
emapper_flags	
date_created	02/22/21
cmdline	python2 "$EMAPPERPATH"/emapper.py --cpu "6"        -i "/data/shared/emapper_jobs/user_data/MM_0io1nr30/query_seqs.fa" --output "query_seqs.fa"        --output_dir "/data/shared/emapper_jobs/user_data/MM_0io1nr30"        -m "diamond" -d "none"        --tax_scope "2"        --go_evidence "non-electronic"        --target_orthologs "all"        --seed_ortholog_evalue 0.001        --seed_ortholog_score 60        --query-cover 20        --subject-cover 0        --override                --temp_dir "/data/shared/emapper_jobs/user_data/MM_0io1nr30"

**Comment by BishopCD** [comment]
Ok, simple solution: .fasta file contained all of the "hypothetical proteins" from a previous annotation (DFAST). As such, the headers were labelled "hypothetical protein1.....hypothetical protein2" etc. The space between "hypothetical" and "protein" meant that only the first sequence was read. Changed the file to ensure all headers contained unique names..no spaces....
Hopefully this will be useful to other relative newbs....

**Comment by Cantalapiedra** [comment]
Hi @BishopCD ,

thank you for reporting.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
After checking the input files, I would say this is a general feature of FASTA format, in which sequence identifier should not contain white spaces.
