### ISSUE TITLE
Running Custom hmm Database

### ISSUE THREAD

**Issue by aoukthrilok** [eggnogdb/eggnog-mapper#283]
I have a custom hmm database. In previous, versions you had hmm_search.py for custom hmm databases. The emapper appears in the notes to do custom databases at least in version 2.0.1-rf1. Is this function still available? As I have had difficulties trying to run such an option. Please advise.

**Comment by Cantalapiedra** [comment]
Hi @aoukthrilok ,

yes, you have hmm_mapper, hmm_worker and hmm_server for that purpose. 

https://github.com/eggnogdb/eggnog-mapper/blob/master/hmm_mapper.py

hmm_mapper.py
```
usage: hmm_mapper.py [-h] [--version] [--cpu NUM_CPU] [-i FASTA_FILE] [--translate] [-d DB_PATH] [--servers_list FILE] [--qtype {hmm,seq}] [--dbtype {hmmdb,seqdb}] [--usemem]
                     [-p PORT] [--end_port PORT] [--num_servers NUM_SERVERS] [--num_workers NUM_WORKERS] [--hmm_maxhits MAXHITS] [--report_no_hits] [--hmm_maxseqlen MAXSEQLEN]
                     [--hmm_evalue MIN_E-VALUE] [--hmm_score MIN_SCORE] [--hmm_qcov MIN_QCOV] [--Z DB_SIZE] [--cut_ga] [--clean_overlaps none|all|clans|hmmsearch_all|hmmsearch_clans]
                     [--output FILE_PREFIX] [--output_dir DIR] [--scratch_dir DIR] [--resume] [--override] [--temp_dir DIR] [--no_file_comments]
```

hmm_server.py
```
usage: hmm_server.py [-h] [--version] [--cpu NUM_CPU] [-d HMMER_DB_PREFIX] [--dbtype {hmmdb,seqdb}] [-p PORT] [--end_port PORT] [-w PORT] [--num_servers NUM_SERVERS]
                     [--num_workers NUM_WORKERS] [-o FILE]
```

Further advice would depend on your DB and your specific use case. For example, if you want to perform a single run mapping sequences, use `hmm_mapper.py`. If you are planning carrying out several runs of alignment with different sequence sets, use `hmm_server.py` in combination with `hmm_mapper.py`. Also, depending on your DB and your available RAM, you could create a single server or more than one with `--num_servers`. More servers, and no more CPUs, mean faster results, in my benchmarks with these tools.

I hope this is of help.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Please, re-open or re-issue if needed.

Best,
Carlos
