### ISSUE TITLE
Multithreading by default only apply to the first phase and is disabled in the second phase

### ISSUE THREAD

**Issue by zeqianli** [eggnogdb/eggnog-mapper#289]
When running simple commands like this:
`emapper.py -i input.fa -o out --itype metagenome --cpu 60`
multi-threading is enabled only at the first phase (finding seed orthologous sequences), and the second phase (expanding annotations) only uses one thread. 

I read in the documentation that this can be achieved by manually separating the two steps, and use --annotate_hits_table and --cpu tags at the second step. But isn't it a good idea to automatically apply multi-threading to both phases?

**Comment by Cantalapiedra** [comment]
Hi @zeqianli ,

multi-threading should be enabled in both phases unless you use `--dbmem`.
Which version of emapper.py are you running? Is the command above the whole one you are running?

Best,
Carlos

**Comment by zeqianli** [comment]
Hi Carlos, 

The command I'm running is `emapper.py -i in.fasta -o out --itype metagenome --cpu 60` (file names aren't exactly that; and I'm actually running this in python through subprocess.Popen(), but I don't think this affects anything). 

System info: CPU: AMD threadripper 3970x 32-core processor × 64; Ubuntu 18.04.5 LTS; emapper-2.0.8-2 / Expected eggNOG DB version: 5.0.1 / Installed eggNOG DB version: 5.0.1 / Local diamond version: diamond version 2.0.4 / Local MMseqs2 version: 113e3212c137d026e297c7540e1fcd039f6812b1

I will run the same command in another computer to test if this is a cpu specific problem and I'm let you know the outcome. 

Best,
Zeqian

**Comment by Cantalapiedra** [comment]
How much RAM memory do you have?

**Comment by zeqianli** [comment]
Hi, I re-run some commands and I believe it's a mistake on my end. I'll close the issue. Thanks a lot for the help!

**Comment by Cantalapiedra** [comment]
Glad to try to help.
Best,
Carlos
