### ISSUE TITLE
Sequences in the reverse strand are missing in *.genepred.fasta files

### ISSUE THREAD

**Issue by zeqianli** [eggnogdb/eggnog-mapper#290]
Running the minimal example below gives 13 annotations, two of which are missing in the *.genepred.fasta file. In *.seed_orthologs file, qstart>qend for two sequences (which I guess means that they are on the reverse stand) and qstart<qend for the others. This seems to be the reason why they are missing.

The minimal example: 
`>NODE_5_length_1938_cov_1.953266
TTGGTATGCTCTACCAGTCCACCTGTGTCGGTTTCGGGTACGGTCTCTGTTGGAGTTATT
TCCAGGAACTCCTTCACTGCCGGGAGCAATCCAATAAGCCCCGACAATTTACGGAATTCG
TCACTTCCAACTGGCCCAGGAATATTCACCTGGTTCCCATCGATTACGCCTTTCGGCCTC
ACCTTAGGGGCCGGCTAACCCTGCGCAGATTAGCTTTACGCAGGAACCCTTGGACTTTCG
GCGAGAGTGTCTCTCACACTCTTTGTCGCTACTCATGTCAGCATTCTCACTTCCGATACC
TCCACCCGATCTCACGACCGAGCTTCATCGGCTTACGGAACGCTCCGCTACCGCGTGCTT
GCGCACACCCATACCTTCGGCGAATGGCTTGAGCCCCGTTACATTTTCCGCGCAGGATCG
CTTGACCAGTGAGCTGTTACGCTTTCTTTAAAGGATGGCTGCTTCTAAGCCAACCTCCTG
GTTGTTTTGGGATTTCCACATCCTTTCCCACTTAGCCACGAATTAGGGGCCTTAGCTGTA
GGTCAGGGTTGTTTCCCTCTCCACGACGGACGTTAGCACCCGCCGTGTGACTCCCGGATA
GTACTCTCAGGTATTCGGAGTTTGGTTGGGTTTGGTAAGACGGTAAGTCCCCCTAGCCCA
TCCAGTGCTCTACCCCCTGAGGTATTCATGCGAGGCGATACCTAAATATCTTTCGCGGAG
AACCAGCTATTTCCCAGTTTGATTGGCCTTTCACCCCTAGCCACAACTCATCCGAGGCTT
TTTCAACAGACACCGGTTCGGCCCTCCAGCAGGTGTTACCGCACCTTCAGCCTGGTCATG
GCTAGATCACTAGGTTTCGGGTCTAATCCGACGAACTGAACGCCCTGTTCAGACTCGCTT
TCGCTGCGCCTACGCCTATCGGCTTAAGCTTGCTCGTCAGATTAAGTCGCTGGCCCATTA
TACAAAAGGTACGCCGTCACCCAGGACGAACCTTGGGCTCCGACTGTTTGTAGGCATTCG
GTTTCAGGTCTCTTTCACTCCCCTCGTCGGGGTGCTTTTCACCTTTCCCTCACGGTACTT
GTTCGCTATCGGTCGCTGAGGAGTACTTAGGCTTGGAGGGTGGTCCCCCCACGTTCAGAC
AGGATTTCACGTGTCCCGCCTTACTCAAGGACGATCCTTCGCATTACCCGTACGGGGCTC
TCACCCTCTACGGCACGTTTTTCCAAACGCTTCCGGTTGTCTCTGGATCGTCACTGGCCT
GGTCCGCGTTCGCTCGCCACTACTAGCGGAGTCTCGGTTGATGTCCTTTCCTCCGGGTAC
TTAGATGTTTCAGTTCCCTGGGTTCGCTTAAAACCTCCTATTTTATTCGGAAGTCTCATA
CCTTCACTTGATAACTGGAAATCCAAAACCTCGCGGCTTGAATTCAAACATTGCTGTCTA
AACCCCAAGATACGAGATCTTGGAGTTCCAGCTATCGAAGGTGGGTTTCCCCATTCGGAA
ATCCGTGGATCAAAGCTTCTTCGCAGCTCCCCACGGCTTATCGCAGCGTAGCACGTCCTT
CATCGCCTCTCAGCGCCAAGGCATCCACCGAACACCCTTAAGGCACTTGATTGCTCTCAT
TATCAATGTCCACACACTCGGCAGAATGTAGTCCGCACACTTGCCCGAAAGACCGAAGTC
TCAAGAGCGCGCACCCTCGATGAATGCTGCGTGCGGCCGGACACTGATTAGAAAGACCAG
CTTGCTTCGTAAGATCGAACCGACAGCGAGGCGGTCAAGCTTCGCTAAAAAGATCATTTA
CAACCCGCTCATCTTGCGATGCGCGAGCGCCGAAATGACCTGGAGATTATGAATGAGAGC
CCGCAAATTGCTTTGCAGATCCCAAACTCGGATCGATCTCCTCTTTACGATGTCAGAAAA
CACGCAGGCGATCTCTCG`

Command: `emapper.py -i example.fa -o out --itype metagenome `
(the metagenome tag is because the minimal example is taken out of a metagenome dataset)

System info: Ubuntu 18.04.5 LTS; emapper-2.0.8-2 / Expected eggNOG DB version: 5.0.1 / Installed eggNOG DB version: 5.0.1 / Local diamond version: diamond version 2.0.4 / Local MMseqs2 version: 113e3212c137d026e297c7540e1fcd039f6812b1

**Comment by Cantalapiedra** [comment]
Hi @zeqianli ,

You are right. Thank you very much for reporting.
It should be fixed in the "master" branch.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
I will close this issue.
Please, re-open or re-issue if needed.

Best,
Carlos
