### ISSUE TITLE
Is necessary download the databases "taxa database" and "diamond database" ?

### ISSUE THREAD

**Issue by EulleSA** [eggnogdb/eggnog-mapper#292]
Hi, everybody! 

I noticed that the "download_eggnog_data.py" script downloads 3 databases( annotation, taxa, and diamond).  

Bearing in mind that I only want to perform the functional annotation to get the KO identifier of each annotated sequence, is it necessary to download all the databases?

Thanks in advance!

**Comment by Cantalapiedra** [comment]
Hi @EulleSA ,

You need the taxa database. 

Regarding the diamond database, if your sequences are not eggnog proteins, or you don't have hits to eggnog proteins, you need to perform a search step, either with diamonds, mmseqs2 or hmmer. Diamond is the default, and that is why it is downloaded by default also.

I hope this makes sense.

Best,
Carlos

**Comment by EulleSA** [comment]
I got it! Thank you very much, Catalapiedra!

**Comment by EulleSA** [comment]
@Cantalapiedra Could you tell me if you can define by command line to download all the necessary banks, without having to choose "y" and "n"?

**Comment by Cantalapiedra** [comment]
Hi @EulleSA ,

check `download_eggnog_data.py --help`. You should be able to do it with -D, -M, -H -d, -f, ...

Best,
Carlos

**Comment by EulleSA** [comment]
Thank you very much!
