### ISSUE TITLE
Error when using the "diamond" option (eggNOG-mapper 2.1.0)

### ISSUE THREAD

**Issue by EulleSA** [eggnogdb/eggnog-mapper#293]
`emapper.py  -m diamond --itype metagenome --no_file_comments -i data_raw/qualityControl/amostra_bruta_agua_de_producao_ap1_preprocessing.fastq -o ap1`

Am I doing something wrong? You are giving the following error when executing this command:

  "/lib64/libc.so.6: version` GLIBC_2.17 'not found "

**Comment by Cantalapiedra** [comment]
Hi @EulleSA ,

I would need more info. What is your OS and OS version? How did you install emapper.py? Is the error a single line or could you show the whole error output?

Thank you.

Besides that, it seems you are trying to use as input a fastq file? Note that emapper.py cannot run with sequencing reads as input. It requires either proteins, CDS, assembled contigs or a list of seed orthologs.

Best,
Carlos

**Comment by EulleSA** [comment]
Hi @Cantalapiedra.

In regard the error, I spoke with the owner of the server and he informed me that it is was a problem in the system. 

In regard the "fastq", I didn't know it could be read. In past versions, I used the following and everything worked fine:

`emapper.py -i <input.fastq> -o <output> --output_dir <dir> -m \
diamond --translate --no_file_comments -cpu <n>`



Thanks for listening.

**Comment by Cantalapiedra** [comment]
Hi @EulleSA ,

glad that the error was fixed.
Regarding the input data, the extension (".fastq" in your example) is not really mandatory of the kind of info in the file.
However, I was commenting because ".fastq" usually is used for a format which includes not only the sequences, but also the per-base qualities, whereas ".fasta" (or ".faa", ".fna" and other extensions) usually have only the sequences, without the per-base qualities.

Check:

https://en.wikipedia.org/wiki/FASTA_format
https://en.wikipedia.org/wiki/FASTQ_format

Please, check your input files just to be sure that you are using FASTA (not FASTQ) as input for emapper.

Best,
Carlos

**Comment by EulleSA** [comment]
Let me understand, in the version of eggNOG-mapper (python2) I was able to input the "fastq" file as an input and I got the result. Does this version of eggNOG-mapper (python3) only allow "fasta" type input? If so, would I have to turn my FASTQ into FASTA to run eggNOG-mapper?

Obs.1: In my pipeline I price to carry out the quality control and for that I would need FASTQ.

Obs.2: I always used the file in FASTQ format as input in the python2 versions of eggNOG and it never gave any problem.

**Comment by Cantalapiedra** [comment]
Hi @EulleSA ,

Regarding observation 1, once quality control has been performed why would you need FASTQ format? Anyway, it would be very easy to transform the FASTQ to FASTA.

Regarding observation 2, emapper has always required FASTA format as input.

Check:

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v1#phase-1-homology-searches
https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.0.0-v2.0.1#Basic_usage

That being said, if you are using diamond search maybe it is just working fine (https://github.com/bbuchfink/diamond/wiki/3.-Command-line-options), something which from emapper we are not taking care of. In such case, I guess you can use fastq also in current emapper versions. I just wanted to warn you.

I am not sure what would happen when using HMMER or MMseqs2.

I hope this makes sense.

Best,
Carlos

**Comment by EulleSA** [comment]
Thank you very much @Cantalapiedra. I got it!

**Comment by Cantalapiedra** [comment]
Thanks to you @EulleSA .
