### ISSUE TITLE
Issue about initiating diamond 

### ISSUE THREAD

**Issue by jlk666** [eggnogdb/eggnog-mapper#294]
Dear authors
I have a question when I try running

emapper.py  -m diamond -i GCF_000196095.1_ASM19609v1_translated_cds.faa --itype CDS -o a1
/Users/jlk666/Documents/Project/Vibrio_project/annotation/eggnog-mapper/eggnogmapper/bin/diamond blastx -d /Users/jlk666/Documents/Project/Vibrio_project/annotation/eggnog-mapper/eggnog-mapper-data/eggnog_proteins.dmnd -q /Users/jlk666/Documents/Project/Vibrio_project/annotation/GCF_000196095.1_ASM19609v1_translated_cds.faa --threads 1 -o /Users/jlk666/Documents/Project/Vibrio_project/annotation/test.emapper.hits  --sensitive -e 0.001 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
Error running diamond: /bin/sh: /Users/jlk666/Documents/Project/Vibrio_project/annotation/eggnog-mapper/eggnogmapper/bin/diamond: cannot execute binary file
It always shows that

I have downloaded all required database and software

**Comment by Cantalapiedra** [comment]
Hi @jlk666 ,

You could try running the `diamond` command directly to check the error:

```
/Users/jlk666/Documents/Project/Vibrio_project/annotation/eggnog-mapper/eggnogmapper/bin/diamond blastx -d /Users/jlk666/Documents/Project/Vibrio_project/annotation/eggnog-mapper/eggnog-mapper-data/eggnog_proteins.dmnd -q /Users/jlk666/Documents/Project/Vibrio_project/annotation/GCF_000196095.1_ASM19609v1_translated_cds.faa --threads 1 -o /Users/jlk666/Documents/Project/Vibrio_project/annotation/test.emapper.hits --sensitive -e 0.001 --top 3 --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
```

I am not sure if the `diamond` bundled along with eggnog-mapper will be valid for your OS. You may need to install a `diamond` which runs in your system.

Best,
Carlos

**Comment by jlk666** [comment]
Hi Carlos
I appreciate your quick response! 
When I run the code you provided it appears this. 
I try running eggNOG in my macOS terminal.

zsh: exec format error: /Users/jlk666/Documents/Project/Vibrio_project/annotation/eggnog-mapper/eggnogmapper/bin/diamond

**Comment by Cantalapiedra** [comment]
Hi @jlk666 ,

glad to try to help.
I don't have macOS myself. 
Maybe you should try to install a diamond version for macOS, and add it to the path, so that eggnog-mapper can use that one instead of the bundled one.

Best,
Carlos

**Comment by jlk666** [comment]
Thank you for your greatly helpful advice!
I have downloaded the correct diamond for MacOS
However, when I run 

jlk666@campus-107-177 annotation % emapper.py -m diamond -i GCF_000196095.1_ASM19609v1_translated_cds.faa --itype CDS -o ip
#  emapper-2.1.1-1
# emapper.py  -m diamond -i GCF_000196095.1_ASM19609v1_translated_cds.faa --itype CDS -o ip
  /Users/jlk666/Documents/Project/Vibrio_project/annotation/eggnog-mapper/eggnogmapper/bin/diamond blastx -d /Users/jlk666/Documents/Project/Vibrio_project/annotation/eggnog-mapper/eggnog-mapper-data/eggnog_proteins.dmnd -q /Users/jlk666/Documents/Project/Vibrio_project/annotation/GCF_000196095.1_ASM19609v1_translated_cds.faa --threads 1 -o /Users/jlk666/Documents/Project/Vibrio_project/annotation/ip.emapper.hits  --sensitive -e 0.001 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
Error running diamond: Error: Invalid output field: scovhsp

and even 
jlk666@campus-107-177 annotation % /Users/jlk666/Documents/Project/Vibrio_project/annotation/eggnog-mapper/eggnogmapper/bin/diamond blastx -d /Users/jlk666/Documents/Project/Vibrio_project/annotation/eggnog-mapper/eggnog-mapper-data/eggnog_proteins.dmnd -q /Users/jlk666/Documents/Project/Vibrio_project/annotation/GCF_000196095.1_ASM19609v1_translated_cds.faa --threads 1 -o /Users/jlk666/Documents/Project/Vibrio_project/annotation/test.emapper.hits --sensitive -e 0.001 --top 3 --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp

diamond v0.9.14.115 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Error: Invalid output field: scovhsp

Maybe something run about the output?

**Comment by Cantalapiedra** [comment]
Hi @jlk666 ,

it's weird that it is using diamond 0.9.
What is the output of `emapper.py --version`?
And what is the content of `/Users/jlk666/Documents/Project/Vibrio_project/annotation/eggnog-mapper/eggnogmapper/bin/` directory?

**Comment by jlk666** [comment]
(base) jlk666@campus-107-177 annotation % emapper.py --version
emapper-2.1.1-1

(base) jlk666@campus-107-177 bin % ls
__init__.py		esl-mask		hmmlogo
alimask			esl-reformat		hmmpgmd
diamond			esl-selectn		hmmpress
diamond_0.9.24		esl-seqrange		hmmscan
diamond_2.0.4		esl-seqstat		hmmsearch
esl-afetch		esl-sfetch		hmmsim
esl-alimanip		esl-shuffle		hmmstat
esl-alimap		esl-ssdraw		jackhmmer
esl-alimask		esl-stranslate		makehmmerdb
esl-alimerge		esl-weight		mmseqs
esl-alipid		hmmalign		nhmmer
esl-alistat		hmmbuild		nhmmscan
esl-cluster		hmmc2			phmmer
esl-compalign		hmmconvert		prodigal
esl-compstruct		hmmemit			prodigal.linux
esl-construct		hmmerfm-exactmatch
esl-histplot		hmmfetch

**Comment by Cantalapiedra** [comment]
Hi @jlk666 ,

I really don't know why in your system it is running diamond 0.9.
You may need to install diamond 2.0.4 instead.

https://github.com/bbuchfink/diamond/releases/tag/v2.0.4

**Comment by jlk666** [comment]
Thank you so much. 
Based on your suggestion, I have successfully run eggNOG in my macOS. 
Many thanks!

**Comment by Cantalapiedra** [comment]
Glad that you finally made it.
Sorry for not being very helpful with macOS, and thank you for your patience.

Best,
Carlos
