### ISSUE TITLE
Output of eggnog-mapper

### ISSUE THREAD

**Issue by jlk666** [eggnogdb/eggnog-mapper#295]
Dear authors
After I annotate the bacterial genome, I got a file with the extension "mybacterialgenome.annotations"
Is this SQL Lite-based annotation? Can I use this file as the input to make the ogdb via Annotationforge?

**Comment by Cantalapiedra** [comment]
Hi,

sorry, I don't know the details about AnnotationForge. Maybe someone else could help.

Best,
Carlos
