### ISSUE TITLE
about the output

### ISSUE THREAD

**Issue by Wanli-HE** [eggnogdb/eggnog-mapper#297]
Hi

i have about 20,000+ genes needs to be annotated, it is nucleotide sequence, so i using the command mode '--itype metagenome'.

and i get the results. but i found only 14,000+ genes are annotated. so my question is, is the result normal? and why are the other  6000+ genes not annotated? 

best,
wanli

**Comment by Cantalapiedra** [comment]
Dear @Wanli-HE ,

We have no means to know whether ~70% of genes annotated is normal for your dataset or not.
If it is nucleotide sequence, do you mean contigs from an assembly from metagenomics samples? ORFs from MAGs? transcripts? CDS? Do you expect more genes annotated and why?

Best,
Carlos

**Comment by vragh** [comment]
If these are individual nucleotide sequences, you could try translating them (e.g., with `TransDecoder` and retain only the best ORF for each sequence). If you end up with ca. 14,000 amino acid sequences, that might be one hint at an answer.
