### ISSUE TITLE
Invalid output field: scovhsp

### ISSUE THREAD

**Issue by bpeacock44** [eggnogdb/eggnog-mapper#298]
Hello,

I am trying to run eggnog-mapper on a fasta file of assembled contigs using the following command:

emapper.py  -m diamond --itype metagenome -i all_mysteries_assembled.fasta -o all_mysteries_assembled_eggnog_output --cpu 0

When I do, I get the following output:

  /path/to/miniconda3/bin/diamond blastx -d /path/to/eggnog-mapper-2.1.2/data/eggnog_proteins.dmnd -q /all_mysteries_assembled.fasta --threads 20 -o /all_mysteries_assembled_eggnog_output.emapper.hits  --sensitive -e 0.001 --max-target-seqs 0 --max-hsps 0  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
Error running diamond: Error: Invalid output field: scovhsp

I installed eggnog-mapper with bioconda originally and got this error, and I figured it was not compatible with the updated version of diamond I have on my computer (based on some of the comments on these issues threads) so I removed egg-nog mapper and re-installed it by downloading the source file and installing it manually. I am still getting the same error, though. Do you have any suggestions? Because I am doing blastx, I cannot limit the output fields.

Thank you!!!

**Comment by Cantalapiedra** [comment]
Hi @bpeacock44 ,

glad that you found a workaround.
Note that when you have different software versions you can deal with it with different environments (e.g. different conda environments) or modifying your PATH (in linux) to give preference to certain paths (first in the PATH list) over others (later in the PATH list).

Best,
Carlos

**Comment by bpeacock44** [comment]
Thank you! Yes, I started using conda without fully understanding the importance of environments so unfortunately for the most part I have installed everything in the base environment. I need to take some time and figure out how to remedy that.

This is a tangential question, but I was wondering if you have any recommendations for a program/tool to use to interpret edgeR output with the KEGG IDs that have been assigned using the eggnog-mapper? I apologize, as I know this is unrelated to eggnog-mapper itself.

**Comment by Cantalapiedra** [comment]
Hi @bpeacock44 ,

Sincerely, I am not able to help since I don't know much about tools for downstream interpretation of KEGG IDs. However, this is a recurrent question which we may try to address in the future.

Good luck!

Best,
Carlos
