### ISSUE TITLE
annotation table

### ISSUE THREAD

**Issue by ucassee** [eggnogdb/eggnog-mapper#304]
Hi,
Is there a table for annotation that links protein id in eggNOG_v5.proteomes.faa to the detail description?
Thanks

**Comment by Cantalapiedra** [comment]
Hi,

yes, within the sqlite database provided with eggnog-mapper.

Best,
Carlos

**Comment by ucassee** [comment]
Hi @Cantalapiedra ,

I wonder is it possible for me to get this database in csv or txt format?

Thanks

**Comment by Cantalapiedra** [comment]
Hi @ucassee ,

the sqlite database is downloaded with `download_eggnog_data.py` available in this repo.
You would need to extract the data. Something like:

sqlite3 data/eggnog.db "select * from prots limit 2" | tr "|" "\t"

You may also check the files in the downloads section of the eggNOG database web http://eggnog5.embl.de/#/app/downloads

I hope this helps.

Best,
Carlos

**Comment by ucassee** [comment]
Hi @Cantalapiedra ,

I am not familiar with SQLite database.
I download eggnog.db and use this command `sqlite3 eggnog.db "select * from prots limit 2" | tr "|" "\t"`. 
I meet the following error: `Error: no such table: prots`. 
I just want to extract the protein ids and their corresponding annotations. Could you give me more help?

Thanks,
Yingli

**Comment by Cantalapiedra** [comment]
Hi @ucassee ,

the description returned by emapper is not from proteins but from the Orthologous Groups.
It is using the "og" table, querying for "og.og" and "og.level".

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Closing this.
Please, reopen or reissue if needed.
