### ISSUE TITLE
annotated bacterial reference genomes

### ISSUE THREAD

**Issue by YiJessePi** [eggnogdb/eggnog-mapper#308]
Hi,
Thank you very much for this great db and tool.
I wish to annotate ~13K reference bacterial genomes that I've downloaded from ncbi but executing eggnog-mapper for all these genomes will take quite a while. 
I guess that annotation to these genome was precomputed already and wondering if there a way to get annotation based on refseq/genbank protein id.
Thanks

**Comment by Cantalapiedra** [comment]
Hi,

glad that you like the tool.
Unfortunately, I don't have precomputed annotations.
If you annotate them, you could create a md5 hash (with `--md5`) and then other users could use your precomputed annotations ;)

Best,
Carlos
