### ISSUE TITLE
Accept hmmsearch results as input so that users can run hmmsearch independently.

### ISSUE THREAD

**Issue by xiekunwhy** [eggnogdb/eggnog-mapper#309]
Hi,

Would you please make eggnog-mapper enable to accept hmmsearch results so that we can run hmmsearch independently (including eggnog datahase and/or pfam database) to speed up searching when there are huge sequences need to be annotated.
Like which have done for accepting diamond results https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.2#setting-up-large-annotation-jobs

Best,
Kun

**Comment by Cantalapiedra** [comment]
Hi,

you could run hmmsearch directly using hmm_mapper.py or emapper.py. You could speed up the process creating an hmm_server.py or by increasing the --num_servers to be used.

If you want to use your own data from hmmsearch, you can use either the hits, putting them in the emapper output folder and using --resume, or you could parse them to create a .seed_orthologs file, and use the -m no_search and --annotate_hits_table .seed_orthologs option (see the emapper docs, please). Note that what is mentioned in the link you provide are not "diamond results", but .seed_orthologs created from diamond results (and you can create this .seed_orthologs file also from hmmsearch results if you wish).

There is no way right now to incorportate your own PFAM annotations to the .annotations file directly using emapper.py, though.
But you should be able to do it rather easily with a join command or similar.

I hope all this makes sense.

Best,
Carlos

**Comment by xiekunwhy** [comment]
Hi,

Thank you for your reply.

--annotate_hits_table can not recognize hmm profile names like 2N58B.faa.final_tree.fa, arCOG01659.faa.final_tree.fa, arCOG01670.faa.final_tree.fa (or 2N58B, arCOG01659, arCOG01670) if I prepare .seed_orthologs file using hmmsearch results instead of using diamond results. So --annotate_hits_table is not the right way to run hmmsearch independently.

Here was the command line I used,
python eggnog-mapper/emapper.py --cpu 6 --no_file_comments --go_evidence all --dbmem --tax_scope Viridiplantae --tax_scope_mode broadest --override --annotate_hits_table hmmsearch.seed --output hmm --output_dir hmmsearch/ --data_dir Database/

And the hmmsearch.seed is like followings,
head hmmsearch.seed
#qseqid	sseqid	evalue	bitscore
PH02Gene30126	2N58B	1e-50	500
PH02Gene24328	arCOG01659	1e-50	500
PH02Gene22753	arCOG01659	1e-50	500
PH02Gene32355	arCOG01659	1e-50	500
PH02Gene49742	arCOG01659	1e-50	500
PH02Gene49089	arCOG01659	1e-50	500
PH02Gene49088	arCOG01659	1e-50	500
PH02Gene16704	arCOG01659	1e-50	500
PH02Gene25815	arCOG01659	1e-50	500
......

Best,
Kun

**Comment by Cantalapiedra** [comment]
Did you try the --resume option?

**Comment by Cantalapiedra** [comment]
Closing this.
Please, reopen or reissue if needed.
