### ISSUE TITLE
Names/IDs of all OGs with Phylum level

### ISSUE THREAD

**Issue by Brunokemon** [eggnogdb/eggnog-mapper#310]
To start your tool is really great! No issues with it.
What I need to know is all the possible OGs with Phylum level currently in the database of eggNOG.

Further explanation: I need to create a csv where the columns are all the possible OGs with Phylum level and the rows are the details about those OGs (mainly ID of that OG and explanation about it)

**Comment by Cantalapiedra** [comment]
Hi @Brunokemon ,

you could check the downloads page of eggNOG DB http://eggnog5.embl.de/#/app/downloads to look for something that may help you.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Closing this.
Please, reopen or reissue if needed.
