### ISSUE TITLE
--decorate_gff crashes when the score is '.'

### ISSUE THREAD

**Issue by alimayy** [eggnogdb/eggnog-mapper#312]
Hi there,

Version: 
emapper-2.1.4-2 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: 5.0.2 / Local diamond version: diamond version 2.0.4 / Local MMseqs2 version: 113e3212c137d026e297c7540e1fcd039f6812b1

The pipeline crashes when the --decorate_gff is used with a GFF file that contains '.' in its score field with the following error:

**Comment by Cantalapiedra** [comment]
#313
