### ISSUE TITLE
--decorate_gff crashes when the score is '.'

### ISSUE THREAD

**Issue by alimayy** [eggnogdb/eggnog-mapper#313]
Hi there,

Version: 
`emapper-2.1.4-2 / Expected eggNOG DB version: 5.0.2 / Installed eggNOG DB version: 5.0.2 / Local diamond version: diamond version 2.0.4 / Local MMseqs2 version: 113e3212c137d026e297c7540e1fcd039f6812b1
`

The pipeline crashes when the `--decorate_gff` is used with a GFF file that contains '.' (dot) in its score field with the following error:

```
Funcional annotation of hits...
0 4.291534423828125e-06 0.00 q/s (% mem usage: 16.90, % mem avail: 83.10)
Decorating gff file gff.gff..
Traceback (most recent call last):
  File eggnog-mapper-2.1.4-2/emapper.py", line 665, in <module>
    n, elapsed_time = emapper.run(args, args.input, args.annotate_hits_table, args.cache_file)
  File "ggnog-mapper-2.1.4-2/eggnogmapper/emapper.py", line 324, in run
    n, elapsed_time = self.run_generator(annotated_hits)
  File "eggnog-mapper-2.1.4-2/eggnogmapper/emapper.py", line 262, in run_generator
    for item in generator:
  File "eggnog-mapper-2.1.4-2/eggnogmapper/deco/decoration.py", line 98, in decorate_gff
    g_score = float(g_score)
ValueError: could not convert string to float: '.'
```

probably due to the following block in decoration.py
```

            (g_seqid, g_source, g_type, g_start, g_end,
             g_score, g_strand, g_phase, g_attrs) = list(map(str.strip, line.split("\t")))

            g_start = int(g_start)
            g_end = int(g_end)
            g_score = float(g_score)

```
Prokka uses '.' for this GFF field in all its GFF annotations as far as I know, which I guess will be the tool many emapper users will have their GFFs generated.  According to [wiki ](https://en.wikipedia.org/wiki/General_feature_format) "A value of "." (a dot) is used to define a null value."

**Comment by Cantalapiedra** [comment]
Thank you very much for reporting this.
Hopefully it is already fixed in the 'master' branch.

Best,
Carlos

**Comment by alimayy** [comment]
Hi Carlos,

Thanks, I cloned the master. It now crashes with the following error again during decoration:

```
  /home/ali/packages/eggnog-mapper/eggnogmapper/bin/diamond blastp -d /home/ali/packages/eggnog-mapper-2.1.4-2/data/eggnog_proteins.dmnd -q f.faa --threads 24 -o testemapper.hits  --sensitive -e 0.001 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
Funcional annotation of hits...
0 6.4373016357421875e-06 0.00 q/s (% mem usage: 11.30, % mem avail: 88.68)
Decorating gff file f.gff...
Traceback (most recent call last):
  File "/home/ali/packages/eggnog-mapper/emapper.py", line 668, in <module>
    n, elapsed_time = emapper.run(args, args.input, args.annotate_hits_table, args.cache_file)
  File "/home/ali/packages/eggnog-mapper/eggnogmapper/emapper.py", line 324, in run
    n, elapsed_time = self.run_generator(annotated_hits)
  File "/home/ali/packages/eggnog-mapper/eggnogmapper/emapper.py", line 262, in run_generator
    for item in generator:
  File "/home/ali/packages/eggnog-mapper/eggnogmapper/deco/decoration.py", line 101, in decorate_gff
    record_key = [attr.split("=")[1] for attr in attrs_list

```

Any idea what may be going on?

**Comment by Cantalapiedra** [comment]
Hi @alimayy ,

I will try with that line.
Could you send me your file, or at least a chunk including the line which produces the error?
You could send it to my email if you prefer to don't share it here.
This way, I could test the whole file at once.

Thank you very much.

Carlos

**Comment by Cantalapiedra** [comment]
I noticed your attrs field does not contain an ID field.
Doesn't Prokka include one?
While I fix this, you could try to annotate your GFF using a valid gff ID field which can be matched with the ID used in the annotations file.

check the --decorate_gff option here https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.2

FILE: a new GFF will be created, adding hits and/or annotations to the attributes already existing in the specified FILE. --decorate_gff_ID_field can be used to specify a GFF attribute (see --decorate_gff_ID_field).

If there is a better way to do this for Prokka GFF's I am all ears.

Carlos

**Comment by Cantalapiedra** [comment]
I updated the master branch.
Just let me know if it works for you now, please.

Thank you very much for your help.

Best,
Carlos

**Comment by alimayy** [comment]
@Cantalapiedra yes works, awesome, thanks!

**Comment by Cantalapiedra** [comment]
Glad that it works.
Thank you for your help!
