### ISSUE TITLE
does eggnogMapper gives gene abundance

### ISSUE THREAD

**Issue by khemlalnirmalkar** [eggnogdb/eggnog-mapper#314]
Hi,
Does eggnogMapper give gene abundance/KO/pathways abundance values?

Thanks,

**Comment by Cantalapiedra** [comment]
Hi @khemlalnirmalkar ,

no abundances are reported in eggNOG-mapper.
Do you mean as a summary of terms found in the annotations or as counts from mappings reads to genes or anything else?

Best,
Carlos

**Comment by khemlalnirmalkar** [comment]
Hi @Cantalapiedra ,
I want to know the difference of genes or pathways between my study groups. So, I am looking for the best way to report that.
Does eggnogMapper, give counts from mappings reads to genes?
can we quantify genes/KO?
Thanks

**Comment by Cantalapiedra** [comment]
Hi,

eggNOG-mapper is all about functional annotation (guessing what is the function of your genes).
For quantification you should use other software.
Once you have the counts (normalized counts, for example) you can combine functional annotation + counts to compare your samples.

I hope this makes sense.

Best,
Carlos

**Comment by khemlalnirmalkar** [comment]
yes, completely make sense,

Now i am looking for quantification software,
Thanks,
Khem

**Comment by Cantalapiedra** [comment]
You are welcome.
Reopen or reissue in case of need.
Best,
Carlos
