### ISSUE TITLE
can i use output of prokka 

### ISSUE THREAD

**Issue by khemlalnirmalkar** [eggnogdb/eggnog-mapper#315]
Hi,
I am a newbie to this eggnogmapper.
I have microbiome shotgun data, annotated with prokka. Since prokka uses prodigal, can I use output files of prokka for eggnogmapper?

Thanks

**Comment by Cantalapiedra** [comment]
Hi @khemlalnirmalkar ,

In principle, you should be able to use the file with protein sequences from Prodigal (from Prokka) as input for eggnog-mapper.
You could also use the --decorate_gff option to further annotate your GFF with eggnog-mapper annotations.
Just in case, remember that we provide a web server which you could use to annotate your proteins without much hassle (some options are only available through command line though).

Best,
Carlos

**Comment by khemlalnirmalkar** [comment]
Great, thank you so much.

Best,
Khem

**Comment by Cantalapiedra** [comment]
Anytime!
