### ISSUE TITLE
invalid output field: scovhsp

### ISSUE THREAD

**Issue by Neo-sage** [eggnogdb/eggnog-mapper#316]
Hi, I'm getting this error when trying to use the diamond search within eggnogmapper, any ideas? Cheers

```
(eggnog) user:~/PROJECT_B$ emapper.py -i AllProteins.faa -m diamond -o diamond_test
#  emapper-2.1.3
# emapper.py  -i AllProteins.faa -m diamond -o diamond_test
  /home/em16077/anaconda3/envs/eggnog/bin/diamond blastp -d /home/em16077/anaconda3/envs/eggnog/lib/python3.9/site-packages/data/eggnog_proteins.dmnd -q /home/em16077/PROJECT_B/AllProteins.faa --threads 1 -o /home/em16077/PROJECT_B/diamond_test.emapper.hits  --sensitive -e 0.001 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
Error running diamond: Error: Invalid output field: scovhsp
```

**Comment by Cantalapiedra** [comment]
Hi @Neo-sage ,

which diamond version is it?
`/home/em16077/anaconda3/envs/eggnog/bin/diamond --version`

Best,
Carlos

**Comment by Neo-sage** [comment]
Thanks for the quick response!

Version is: 0.9.21

**Comment by Cantalapiedra** [comment]
You are welcome :)

Note that for your emapper version you would need diamond 2.0.4 or above.
Check https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.2#optional-tools

Best,
Carlos

**Comment by Neo-sage** [comment]
Yes, weirdly when installing through anaconda it gave me version 0.9.21, through both the eggnogmapper bioconda install, and the official diamond bioconda install.

Just installed eggnog mapper through the tar.gz from your github and the bundled diamond version is now working fine!

**Comment by Neo-sage** [comment]
Having said that, I am now encountering another error which I'm not sure how to fix:

`Traceback (most recent call last):
  File "/usr/local/bin/emapper.py", line 4, in <module>
    __import__('pkg_resources').run_script('eggnog-mapper==2.1.4.post2', 'emapper.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1468, in run_script
    script_code = compile(script_text, script_filename, 'exec')
  File "/usr/local/lib/python2.7/dist-packages/eggnog_mapper-2.1.4.post2-py2.7.egg/EGG-INFO/scripts/emapper.py", line 82
    help=f'Input FASTA file containing query sequences (proteins by default; see --itype and --translate). '
                                                                                                           ^
SyntaxError: invalid syntax
`

**Comment by Neo-sage** [comment]
To confirm, installing it on a cluster machine with anaconda also links me to the wrong diamond version, not sure how to fix this:

`The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-4.5-1_gnu
  biopython          pkgs/main/linux-64::biopython-1.78-py38h7b6447c_0
  blas               pkgs/main/linux-64::blas-1.0-mkl
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  ca-certificates    pkgs/main/linux-64::ca-certificates-2021.5.25-h06a4308_1
  certifi            pkgs/main/linux-64::certifi-2021.5.30-py38h06a4308_0
  **diamond            bioconda/linux-64::diamond-0.9.14-h2e03b76_4**
  easel              bioconda/linux-64::easel-0.48-h779adbc_0
  eggnog-mapper      bioconda/noarch::eggnog-mapper-2.1.3-pyhdfd78af_0
  gawk               pkgs/main/linux-64::gawk-5.1.0-h7b6447c_0
  hmmer              bioconda/linux-64::hmmer-3.3.2-h1b792b2_1
  intel-openmp       pkgs/main/linux-64::intel-openmp-2021.2.0-h06a4308_610
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.35.1-h7274673_9
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.3.0-h5101ec6_17
  libgomp            pkgs/main/linux-64::libgomp-9.3.0-h5101ec6_17
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.3.0-hd4cf53a_17
  mkl                pkgs/main/linux-64::mkl-2021.2.0-h06a4308_296
  mkl-service        pkgs/main/linux-64::mkl-service-2.3.0-py38h27cfd23_1
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.3.0-py38h42c9631_2
  mkl_random         pkgs/main/linux-64::mkl_random-1.2.1-py38ha9443f7_2
  mmseqs2            bioconda/linux-64::mmseqs2-13.45111-h95f258a_1
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  numpy              pkgs/main/linux-64::numpy-1.20.2-py38h2d18471_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.20.2-py38hfae3a4d_0
  openssl            pkgs/main/linux-64::openssl-1.1.1k-h27cfd23_0
  pip                pkgs/main/linux-64::pip-21.1.2-py38h06a4308_0
  prodigal           bioconda/linux-64::prodigal-2.6.3-h779adbc_3
  psutil             pkgs/main/linux-64::psutil-5.8.0-py38h27cfd23_1
  python             pkgs/main/linux-64::python-3.8.10-h12debd9_8
  readline           pkgs/main/linux-64::readline-8.1-h27cfd23_0
  setuptools         pkgs/main/linux-64::setuptools-52.0.0-py38h06a4308_0
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_0
  sqlite             pkgs/main/linux-64::sqlite-3.35.4-hdfb4753_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  wget               pkgs/main/linux-64::wget-1.20.1-h20c2e04_0
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3`

**Comment by Cantalapiedra** [comment]
> sr/local/bin/emapper.py", line 4, in <module> __import__('pkg_resources').run_script('eggnog-mapper==2.1.4.post2', 'emapper.py') File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script self.require(req

Hi, it seems that here you are running python 2.7, but you should use python 3.7 or above.

**Comment by Cantalapiedra** [comment]
> To confirm, installing it on a cluster machine with anaconda also links me to the wrong diamond version, not sure how to fix this:
> 
> `The following NEW packages will be INSTALLED:
> 
> _libgcc_mutex pkgs/main/linux-64::_libgcc_mutex-0.1-main
> _openmp_mutex pkgs/main/linux-64::_openmp_mutex-4.5-1_gnu
> biopython pkgs/main/linux-64::biopython-1.78-py38h7b6447c_0
> blas pkgs/main/linux-64::blas-1.0-mkl
> bzip2 pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
> ca-certificates pkgs/main/linux-64::ca-certificates-2021.5.25-h06a4308_1
> certifi pkgs/main/linux-64::certifi-2021.5.30-py38h06a4308_0
> **diamond bioconda/linux-64::diamond-0.9.14-h2e03b76_4**
> easel bioconda/linux-64::easel-0.48-h779adbc_0
> eggnog-mapper bioconda/noarch::eggnog-mapper-2.1.3-pyhdfd78af_0
> gawk pkgs/main/linux-64::gawk-5.1.0-h7b6447c_0
> hmmer bioconda/linux-64::hmmer-3.3.2-h1b792b2_1
> intel-openmp pkgs/main/linux-64::intel-openmp-2021.2.0-h06a4308_610
> ld_impl_linux-64 pkgs/main/linux-64::ld_impl_linux-64-2.35.1-h7274673_9
> libffi pkgs/main/linux-64::libffi-3.3-he6710b0_2
> libgcc-ng pkgs/main/linux-64::libgcc-ng-9.3.0-h5101ec6_17
> libgomp pkgs/main/linux-64::libgomp-9.3.0-h5101ec6_17
> libstdcxx-ng pkgs/main/linux-64::libstdcxx-ng-9.3.0-hd4cf53a_17
> mkl pkgs/main/linux-64::mkl-2021.2.0-h06a4308_296
> mkl-service pkgs/main/linux-64::mkl-service-2.3.0-py38h27cfd23_1
> mkl_fft pkgs/main/linux-64::mkl_fft-1.3.0-py38h42c9631_2
> mkl_random pkgs/main/linux-64::mkl_random-1.2.1-py38ha9443f7_2
> mmseqs2 bioconda/linux-64::mmseqs2-13.45111-h95f258a_1
> ncurses pkgs/main/linux-64::ncurses-6.2-he6710b0_1
> numpy pkgs/main/linux-64::numpy-1.20.2-py38h2d18471_0
> numpy-base pkgs/main/linux-64::numpy-base-1.20.2-py38hfae3a4d_0
> openssl pkgs/main/linux-64::openssl-1.1.1k-h27cfd23_0
> pip pkgs/main/linux-64::pip-21.1.2-py38h06a4308_0
> prodigal bioconda/linux-64::prodigal-2.6.3-h779adbc_3
> psutil pkgs/main/linux-64::psutil-5.8.0-py38h27cfd23_1
> python pkgs/main/linux-64::python-3.8.10-h12debd9_8
> readline pkgs/main/linux-64::readline-8.1-h27cfd23_0
> setuptools pkgs/main/linux-64::setuptools-52.0.0-py38h06a4308_0
> six pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_0
> sqlite pkgs/main/linux-64::sqlite-3.35.4-hdfb4753_0
> tk pkgs/main/linux-64::tk-8.6.10-hbc83047_0
> wget pkgs/main/linux-64::wget-1.20.1-h20c2e04_0
> wheel pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
> xz pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
> zlib pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3`

What conda environment are you using?
From your several questions I would say that you need to control more your environment.
Are you currently using python 2.7 or python 3?

You should be sure to use python 3.7 or above, and dependencies should install ok.
Also, you should be able to ask for specific versions of software to be installed.
Another option is add to your PATH the path to the diamond version bundled with emapper.

Best,
Carlos

**Comment by Neo-sage** [comment]
Hi Carlos,
The 2.7 issue was with a fresh local install of eggnogmapper without using anaconda, I don't know why it's using 2.7 when that machine has python 3.7 on it too. I'm wondering if the setup.py maybe uses python rather than python3?

The other issue above was using anaconda with a fresh environment with python 3.8, I think the diamond version hosted on bioconda may be incorrect as when downloading diamond (without eggnogmapper) it still only downloads 0.9.14, so I'm guessing it's a problem with the diamond bioconda version, and not the eggnogmapper an anaconda.

**Comment by Cantalapiedra** [comment]
Hi,

setup.py should not be using python 2.7, at least in current versions. If you check the setup.py file you will see it begins with:
`#!/usr/bin/env python3`. Maybe you were running it like `python setup.py`? In such case, it will use the `python` command found first in your PATH I guess.

The diamond issue is weird yes, as in the anaconda diamond page you will find that when installing from bioconda channel the default version installed should be 2.0.9 https://anaconda.org/bioconda/diamond

I checked and for me it is installing 2.0.9 version.

```
conda --version
conda 4.6.14
conda create -n diamond_env python=3.8
...
conda activate diamond_env
conda config --show channels
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
conda install -c bioconda diamond
...
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    boost-cpp-1.74.0           |       h312852a_4        16.3 MB  conda-forge
    diamond-2.0.9              |       hdcc8f71_0         1.8 MB  bioconda
    ------------------------------------------------------------
                                           Total:        18.2 MB
...
diamond --version
diamond version 2.0.9
```

**Comment by Neo-sage** [comment]
Okay, after adding the channels in your env, i.e conda config --add channels conda-forge
It is now downloading the correct diamond version, thanks!

**Comment by Neo-sage** [comment]
Okay, after adding the channels in your env, i.e conda config --add channels conda-forge
It is now downloading the correct diamond version, thanks!

**Comment by Cantalapiedra** [comment]
Just by adding conda-forge? I really need to study more about how conda manages this!
Glad that it worked though.
Best,
Carlos

**Comment by Neo-sage** [comment]
Yes, weird! Basically the 'boost-cpp-1.74.0' was required to stop conflicts with diamond and python, but I don't really understand either!  Thanks for the help
