### ISSUE TITLE
The number of queries annotated is less than the number scanned

### ISSUE THREAD

**Issue by Biofarmer** [eggnogdb/eggnog-mapper#317]
Hello,

I am using eggnogmapper/2.1.2 to annotate my sequences. I just found the number of queries in the annotation file is sometime less than the number indicated at the end of the annotation file. For example, the total number of queries is 3000 in annotation file, however, ##3001 queries scanned indicated at the end of this file. When I compared the queries from seed_orthologs to the annotation file, one query indeed is missing in the annotation file.
May I ask if this is normal and why?

Many thanks
Wang

**Comment by Cantalapiedra** [comment]
Hi @Biofarmer ,

it is difficult to say without more details.
Maybe a bug in 2.1.2 or maybe one of your sequences is not getting any annotation.
You could send me (part) of your seeds orthologs file so that I could check it.

Best,
Carlos

**Comment by Biofarmer** [comment]
Hi Carlos,

Many thanks. Can I send it to notifications@github.com? or any other email?

Best,
Wang

**Comment by Cantalapiedra** [comment]
Hi,

your query hit protein "Q775C1_BPBPP".
If I am not mistaken this protein has no orthologous group (OG) in eggnog, so eggnog-mapper cannot annotate it.
Note that not all proteins with hits (with seed orthologs) will have annotation due to several reasons (the main one being a protein which does not belong to an OG).

I hope this makes sense.
Best,
Carlos

**Comment by Biofarmer** [comment]
Hi Carlos,

Thanks for checking. It is great that this is not a bug of the eggnog. So, the ##number of queries scanned at the end of annotation file is the number of hits in seed_orthologs, not the final annotation queries, right?

Wang

**Comment by Cantalapiedra** [comment]
Glad to help!

Yes, queries scanned should be the queries in your input file, to keep
track of how many were processed even when not all of them will have
annotations.

**Comment by Biofarmer** [comment]
Hi Carlos, 
Thanks for quick reply and it is very helpful. 
Best, Wang
