### ISSUE TITLE
GFF decoration failing on sort

### ISSUE THREAD

**Issue by Neato-Nick** [eggnogdb/eggnog-mapper#319]
Hi, I'm using the master branch of emapper because I saw it handles a score of '.' But, I'm still having GFF parsing problems.
It didn't output a line of the gff that caused this issue, so I'm sorry but I don't really know how to begin helping you debug this. Here's the stacktrace:

```
Traceback (most recent call last):
  File "/home/nicholas.carleson@usda-ars.orst.edu/opt/eggnog-mapper/emapper.py", line 668, in <module>
    n, elapsed_time = emapper.run(args, args.input, args.annotate_hits_table, args.cache_file)
  File "/home/nicholas.carleson@usda-ars.orst.edu/opt/eggnog-mapper/eggnogmapper/emapper.py", line 324, in run
    n, elapsed_time = self.run_generator(annotated_hits)
  File "/home/nicholas.carleson@usda-ars.orst.edu/opt/eggnog-mapper/eggnogmapper/emapper.py", line 262, in run_generator
    for item in generator:
  File "/home/nicholas.carleson@usda-ars.orst.edu/opt/eggnog-mapper/eggnogmapper/deco/decoration.py", line 143, in decorate_gff
    for v in sorted(gff_dict.values(), key=lambda x: (x[0], x[3], x[4], x[5])):
TypeError: '<' not supported between instances of 'float' and 'str'

```

I get the error with just the first three genes of my gff, proteins and gff attached so you can try and reproduce it.
[threegenes.peps.fasta](https://github.com/eggnogdb/eggnog-mapper/files/6711215/threegenes.peps.fasta.txt)
[threegenes.gff](https://github.com/eggnogdb/eggnog-mapper/files/6711216/threegenes.gff.txt)

I was running
```
emapper.py --itype proteins -i threegenes.peps.fasta -o threegenes \
        --decorate_gff threegenes.gff --cpu 4 --override 
```

**Comment by Neato-Nick** [comment]
I think it's related to https://github.com/eggnogdb/eggnog-mapper/issues/313 still , maybe python doesn't like there's a mix of '.' and numbers in the score. When I remove that column from the sort, the gff decorates just fine:

for v in sorted(gff_dict.values(), key=lambda x: (x[0], x[3], x[4])):

**Comment by Cantalapiedra** [comment]
Hi @Neato-Nick ,

thank you very much for reporting this!
I guess this only happens when all previous fields are exactly equal in several records.
I will try to fix it with `key=lambda x: (x[0], x[3], x[4], 0 if x[5] == "." else x[5])`
I just need to try to create a test gff which addresses this for the unit tests and I will push to the master branch ASAP.

Best,
Carlos
