### ISSUE TITLE
no result with a web tool 

### ISSUE THREAD

**Issue by cdv22** [eggnogdb/eggnog-mapper#321]
hi, thank you for reading this, I submitted my protein file in the web tool (http://eggnog-mapper.embl.de), it did not generate any results, I don't know why. Could you please guide me by informing me the reason for my error. 
the script from web tool:
` emapper.py --cpu 20 --data_dir /dev/shm/ -o out --output_dir /data/shared/emapper_jobs/user_data/MM_v5ed0wr7 --temp_dir /data/shared/emapper_jobs/user_data/MM_v5ed0wr7 --override -m diamond -i /data/shared/emapper_jobs/user_data/MM_v5ed0wr7/queries.fasta --evalue 0.001 --score 60 --pident 40 --query_cover 20 --subject_cover 20 --itype proteins --tax_scope auto --target_orthologs all --go_evidence non-electronic --pfam_realign none --report_orthologs --decorate_gff yes --excel `

attached the protein file
[2.zip](https://github.com/eggnogdb/eggnog-mapper/files/6730151/2.zip)
Thank you

**Comment by Cantalapiedra** [comment]
Hi,

did you check the "CDS" option in the input form?

Carlos

**Comment by Cantalapiedra** [comment]
Closing this.
Please, reopen or reissue if needed.
