### ISSUE TITLE
Incorrect annotated gene position

### ISSUE THREAD

**Issue by GuillaumePrg** [eggnogdb/eggnog-mapper#324]
Hello, 

I tried to annotate my genome (fasta file) via the web interface. No problem for annotation, however the gff or xls file doesn't contain the good positions. All identified genes starts at position 1 and ends to their associated size. I also tried to annotate the genome from CDS file (gff file with the position of each CDS identified by Prodigal), it doesn't solve anything.  
How to solve this problem ? Only the predicted genes without annotation (CDS) are well placed with Prodigal. 

Thank you for your help,
Guillaume

**Comment by Cantalapiedra** [comment]
Hi,

I would need further information.
Could you share your emapper job ID (MM_...) here or to cpcantalapiedra@gmail.com?

Thanks.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Closing this.
Please, reopen or reissue if needed.
