### ISSUE TITLE
Annotation has no basis

### ISSUE THREAD

**Issue by XK4959** [eggnogdb/eggnog-mapper#326]
Hello, I have a protein sequence, which has the function of protein ubiquitination after annotation. However, after checking the reference protein sequences of the known homologous protein group, it was found that none of these sequences had been studied. How did this comment result come out? Is it reliable?

My protein sequence is as follows：
MQILNLAAVSLFIGSSLAADCFGQAGIGNKFIEGYWDARQKMCSNTECTYQQPCTVTTSKKYTAIGSATLQIEFKRKNTAGKAGYKDCWDATEDIIIQCVRNGDQYSGSWQANGQLYQVNGWYN

This is the comment result：
![image](https://user-images.githubusercontent.com/74860841/126037720-6d0c3d91-ec45-4c2b-82cf-2cfd20d37d89.png)

Looking forward to your reply! Best wishes to you!
Xinlong

**Comment by Cantalapiedra** [comment]
Hi,

Some of the members of the OG may have been annotated with such name, which is then transferred to the OG.
It could be a misannotation, as it happens still today in most large scale databases.

I aligned your protein against uniprot and most of the hits are "uncharacterized", but you still get some hits like "SCP domain containing protein" or "Phospholipid-transporting ATPase".

I hope this makes sense.

Best,
Carlos

**Comment by XK4959** [comment]
Thank you very much！
After research, I think the annotation of the protein is unreliable, so I ruled it out~

Best wishes！
Xinlong
