### ISSUE TITLE
functional annotation of predicted proteins with eggnog

### ISSUE THREAD

**Issue by timase2021** [eggnogdb/eggnog-mapper#329]
Hello,

I want to make a functional annotation with eggnog for predected proteins. I do not know where to start.
I have many questions:

1-is it possible to download the database on an external hard drive and make my annotation?

I'am working on linux, I found this command
python emapper.py -i <input_file> --output <output_file> -m [diamond, hmm] --usemem -d <database_name>

2-is this the correct ? Can you explain me what does -m [diamond, hmm] mean what do I put in this part?

thank you

**Comment by Cantalapiedra** [comment]
Closing this.
Please, reopen or reissue if needed.
