### ISSUE TITLE
eggnog diamond database update

### ISSUE THREAD

**Issue by typlam** [eggnogdb/eggnog-mapper#330]
I have just upgraded my old eggnog-mapper from v2.0.1 to the latest v2.1.4-2.  After installing a new conda env for the new version and re-importing the databases, I got an error message that the base diamond database was created with a different version of diamond and so cannot be used?  Which version of Diamond were those created?

Or could the base diamond-related databases be updated? Or how may I work around this? - apart from installing an older version of eggnog-mapper?

Thanks.

**Comment by Cantalapiedra** [comment]
Hi @typlam ,

which version of diamond are you using (i.e. is found in your PATH?).

Check version used by eggnog-mapper at https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.2-to-v2.1.4#Optional_tools

Best,
Carlos

**Comment by typlam** [comment]
Thanks for getting back to me Carlos.
I've resolved it now.  I initially installed the programme using conda install on our linux server - and realised that instead of the latest version, it took the version 2.1.3. So I downloaded v2.1.4 manually and uncompressed it for installation.  And everything works now.
Cheers.

**Comment by Cantalapiedra** [comment]
Hi @typlam ,

I suspected that you solved it, because you closed the issue.
But I wanted to answer just in case.

Best,
Carlos
