### ISSUE TITLE
eggnog mapper download

### ISSUE THREAD

**Issue by timase2021** [eggnogdb/eggnog-mapper#332]
to use eggnog mapper I have to download the whole database?? (/download/egglog_5.0/) about 24 G, or is there a file to download only ??

**Comment by Cantalapiedra** [comment]
Hi,

please, take a look at https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.2-to-v2.1.4#Setup

**Comment by Cantalapiedra** [comment]
and https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.2-to-v2.1.4#storage-requirements

**Comment by Cantalapiedra** [comment]
you also have the option to use http://eggnog-mapper.embl.de/

**Comment by Cantalapiedra** [comment]
Closing this.
Please, reopen or reissue if needed.
