### ISSUE TITLE
eggnog-mapper_COGextraction 

### ISSUE THREAD

**Issue by timase2021** [eggnogdb/eggnog-mapper#333]
Hello, 

I made a functional annotation of a set of transcripts using eggnog from the result i got " *.emapper.annotations " I would like to extract the COGS_category, I found this program:
 https://github.com/raymondkiu/eggnog-mapper_COGextraction /blob/extract_COG-updated/extract_COG.sh
 But when I run the sript with the command % ./extract_COG.sh FILENAME it doesn't work (I am working on linux from command line)
Has anyone ever used this script or extracted COGS from the results? could you help me?

**Comment by Cantalapiedra** [comment]
Hi @timase2021 ,

are you using eggnog-mapper command line or results from the web?
if command line, what eggnog-mapper version are you using? `emapper.py --version`
what is exactly what you want to extract or do? The COG_category column has one or more COG categories for each hit. Do you want to summarize it? To sum occurences of every COG category? To obtain the description?

Best,
Carlos

**Comment by timase2021** [comment]
Hi, 

Thank you for your answer.
I'am not using it in web I download it and I'am using it with command line
emapper.py --version : emapper-2.1.3
I want to extract the COG_Category column to then have the number of COG_category that looks the same and have a description

cheers,
tima

**Comment by Cantalapiedra** [comment]
Hi @timase2021 ,

In version 2.1.3 the COG category column is the 7th, according to https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.2-to-v2.1.4#annotations-file

To extract only that column you could do something like:

```
cat ANNOTATIONS_FILE | cut -f 1,7 > COG_CATS_FILE
```

To "have the number of COG_category that looks the same", maybe you could do something like:

```
grep -v "^#" emapper_benchmark_genome/results/proteome_diamond_annot/out.emapper.annotations | cut -f 7 | awk '{fo
r (i=1;i<=length($1);i++) {print substr($1,i,1)}}' | sort | uniq -c
```

Regarding the descriptions, you could check them here:

https://ecoliwiki.org/colipedia/index.php/Clusters_of_Orthologous_Groups_(COGs)

or here also

https://www.ncbi.nlm.nih.gov/research/cog#

I hope this is of help.

Best,
Carlos

**Comment by timase2021** [comment]
Thnk you very much

**Comment by Cantalapiedra** [comment]
Anytime
