### ISSUE TITLE
what's wrong happening when i download eggNOG-mapper databases with conda enviroment?

### ISSUE THREAD

**Issue by gaoxiangcao** [eggnogdb/eggnog-mapper#338]
Download main annotation database? [y,n] y
Downloading "eggnog.db" at /newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/lib/python3.9/site-packages/data...
cd /newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/lib/python3.9/site-packages/data && wget -nH --user-agent=Mozilla/5.0 --relative --no-parent --reject "index.html*" --cut-dirs=4 -e robots=off -O eggnog.db.gz http://eggnogdb.embl.de/download/emapperdb-5.0.2/eggnog.db.gz && echo Decompressing... && gunzip eggnog.db.gz 
sh: Row 0:cd: /newlustre/home/xm/miniconda3/envs/eggNOG_mapper/lib/python3.9/site-packages/data: no such file or directory
Download taxa database? [y,n] y
Downloading "eggnog.taxa.db" at /newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/lib/python3.9/site-packages/data...
cd /newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/lib/python3.9/site-packages/data && wget -nH --user-agent=Mozilla/5.0 --relative --no-parent --reject "index.html*" --cut-dirs=4 -e robots=off -O eggnog.taxa.tar.gz http://eggnogdb.embl.de/download/emapperdb-5.0.2/eggnog.taxa.tar.gz && echo Decompressing... && tar -zxf eggnog.taxa.tar.gz && rm eggnog.taxa.tar.gz
sh: Row 0:cd: /newlustre/home/xm/miniconda3/envs/eggNOG_mapper/lib/python3.9/site-packages/data: no such file or directory
Download diamond database (~4GB after decompression)? [y,n] y
Downloading fasta files " at /newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/lib/python3.9/site-packages/data...
cd /newlustre/home/caogx/miniconda3/envs/eggNOG_mapper/lib/python3.9/site-packages/data && wget -nH --user-agent=Mozilla/5.0 --relative --no-parent --reject "index.html*" --cut-dirs=4 -e robots=off -O eggnog_proteins.dmnd.gz http://eggnogdb.embl.de/download/emapperdb-5.0.2/eggnog_proteins.dmnd.gz && echo Decompressing... && gunzip eggnog_proteins.dmnd.gz 
sh: Row 0:cd: /newlustre/home/xm/miniconda3/envs/eggNOG_mapper/lib/python3.9/site-packages/data: no such file or directory
Skipping Pfam database (or already present). Use -P and -f to force download
Skipping MMseqs2 database (or already present). Use -M and -f to force download
No HMMER database requested. Use "-H -d taxid" to download the hmmer database for taxid
Finished.

**Comment by Cantalapiedra** [comment]
Hi @gaoxiangcao ,

the key seems to be:
```
sh: Row 0💿 /newlustre/home/xm/miniconda3/envs/eggNOG_mapper/lib/python3.9/site-packages/data: no such file or directory
```
You may need to use the `--data-dir` option to specify a directory where to store the databases.
Please, check https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5#Setup

I hope this is of help.

Best,
Carlos

**Comment by zeynepkurtw** [comment]
I'm having the same issue with the conda installation however --data-dir option is not recognized

```
download_eggnog_data.py --data-dir .

usage: download_eggnog_data.py [-h] [-D] [-F] [-P] [-M] [-H] [-d HMMER_DBS] [-y] [-f] [-s] [-q] [--data_dir]

download_eggnog_data.py: error: unrecognized arguments: --data-dir .
```

**Comment by Cantalapiedra** [comment]
Hi,

I think I typed incorrectly the option. It should be `--data_dir`. 
Let me know if that fixes the problem.

Best,
Carlos

**Comment by MirianDeyssi** [comment]
Hello Carlos I'm having the same problem and adding `--data_dir` didn't work it may seems that there are some lacking 
lib/python3.10/site-packages/data: No such file or directory

**Comment by Cantalapiedra** [comment]
Hi @MiriamDeyssi,

Could you please share the commands that you used to install eggnog-mapper and to run the scripts?

Best,
Carlos

**Comment by MirianDeyssi** [comment]
Hello Carlos,

I used this commands to install
first.
conda install  eggnog-mapper
second
pip install eggnog-mapper

to run 
emapper.py -i Prokka.faa -o Eggonogmapper

**Comment by Cantalapiedra** [comment]
Hi @MirianDeyssi,

did you install the eggnog DB with `download_eggnog_data.py`?

**Comment by MirianDeyssi** [comment]
Hi Carlos
I used this comands
Insatall: conda install eggnog-mapper
             emapper.py -i FASTA.FAA -o Fasta.faaO

I tried to install by source code and I get the same error

Insatall: pip install eggnog-mapper

**Comment by Cantalapiedra** [comment]
Hi @MirianDeyssi ,

But you said that you got an error running `download_eggnog_data.py` with `--data_dir`?
Sorry, but I am not sure which of your commands is yielding the error.

If you installed eggnog-mapper with conda, which should be `conda install -c bioconda eggnog-mapper`, then you should be able to run `download_eggnog_data.py`, maybe using `--data_dir` to point to a directory you created to store the eggnog data.

Once the eggnog data is correctly installed, you should be able to run `emapper.py` with `--data_dir` pointing to the directory where you downloaded eggnog data in the previous step.

I hope this is of help.

Best,
Carlos

**Comment by wkipandula** [comment]
Hi Carlos, 
I am having more like similar problem when trying to download the database.However, for me i think it is failling to download Hmmer.See the command and error below.

(eggnog-mapper) wakisa@lab417:~$ download_eggnog_data.py


sh: 1: cd: can't cd to /home/wakisa/miniconda3/envs/eggnog-mapper/lib/python3.12/site-packages/data
Skipping Pfam database (or already present). Use -P and -f to force download
Skipping MMseqs2 database (or already present). Use -M and -f to force download
No HMMER database requested. Use "-H -d taxid" to download the hmmer database for taxid

**Comment by hellopeccat** [comment]
The option `--data_dir` and command `download_eggnog_data.py` seems to be old fashion. 

When I run download_eggnog_data.py with `--data_dir`, only eggnog.db was downloaded. Then emapper.py didn't recognize this option.
