### ISSUE TITLE
Job failed

### ISSUE THREAD

**Issue by LeonardosMageiros** [eggnogdb/eggnog-mapper#352]
Hi, 

I am trying to annotate a multifasta file with each entry corresponding to the sequence of a gene as it was reported by prokka. 

Nonetheless my job fails. 
The files of my job can be found here: 
http://eggnog-mapper.embl.de/MM_kvb7jdcf/

Could you tell me what I am doing wrong? 

Thank you in advance for your time. 
Best
 
Leonardos

**Comment by Cantalapiedra** [comment]
Hi @LeonardosMageiros ,

not sure if this is in your original file or not, but in the .raw and .fasta within the job there is a sequence with this format:

```
>hdl___#N/A
IVa
```

This may be the one causing the error.
Please, check it and let me know, so that we can identify the error.

Thank you.

Best,
Carlos

**Comment by LeonardosMageiros** [comment]
Carlos apologies I missed that. 
Everything is ok now. 

Thank you very much for your help. 
Best 
Leonardos

**Comment by Cantalapiedra** [comment]
Glad that it worked!

Thank you.

Best,
Carlos
