### ISSUE TITLE
PFAM translation to PF number

### ISSUE THREAD

**Issue by jjkoehorst** [eggnogdb/eggnog-mapper#356]
The results regarding PFAM show the more human readable identifier e.g., DDE_Tnp_1 but is it possible to provide a mapping to the corresponding PF01609 id? I checked the latest HMM file provided by PFAM but some identifiers do not match up due to release differences and I could not find in the documentation which Pfam database is currently in use.

**Comment by Cantalapiedra** [comment]
Hi @jjkoehorst ,

If I recall correctly, the PFAM database is PFAM 31, since it is the same used in eggNOG 5.
However, you should be able to use any PFAM database when using the realignment options.
I already did annotations with PFAM32 and 33 if I am not mistaken.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Closing this issue.

Please, re-open or re-issue if needed
