### ISSUE TITLE
In the annotation output, what is meant by best GO?

### ISSUE THREAD

**Issue by kenscripts** [eggnogdb/eggnog-mapper#357]
The annotations output contains a field called "best GO". 

What is technically meant by best GO? How do you determine the best GO from the list of GO terms assigned to a particular protein? Did you determine the information content from the list of GO terms and choose the most informative one? How did you choose which ontology (BP, CC, MF) to choose for the best GO?

Thank you for your contribution with this amazing tool!

**Comment by Cantalapiedra** [comment]
Hi @kenscripts ,

Thank you for your kind words.

Which version of eggnog-mapper are you using?

If I recall correctly, the best OG (OG of Orthologous Group, not best GO) field was the one showing the OG chosen to retrieve annotations from eggNOG and transfer them to the queries.

Take a look at:
https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.0.0-v2.0.1#v200
https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.0-v2.1.1#orthologous-groups-fields

If you want to check other versions:
https://github.com/eggnogdb/eggnog-mapper/wiki#documentation

I hope this makes sense and is of help.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
you can also find the current equivalent field, as "max_annot_lvl" here:

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.6#Orthologous_Groups_fields

**Comment by kenscripts** [comment]
Hi Carlos,

Thanks for the quick response. However, for my purpose, I am not interested in the Orthologous Groups (OG). 

I am referring to the best GO (Gene Ontology) field in the annotation output. The annotation output assigns a list of GO (Gene Ontology) terms to each protein and then from this list a best GO term is selected and that is what goes under the "best GO" field. I am wondering how you define best GO? How was it selected?

I am using emapper v2.0.1.

-Kenny

**Comment by Cantalapiedra** [comment]
Hi @kenscripts ,

sorry, but I cannot remember which best GO field you refer to.
Could you please paste an example of output with such field?

Thank you

Carlos
