### ISSUE TITLE
Error running diamond: Error: Invalid option: iterate

### ISSUE THREAD

**Issue by TKsh6** [eggnogdb/eggnog-mapper#360]
here is the code: python eggnog-mapper/emapper.py -i gene.faa --output func_anno --output_dir res -m diamond -d eggnog-mapper/data/eggnog --cpu 18
and i got the error: Error running diamond: Error: Invalid option: iterate.
I’ll appreciate that someone can help me deal with this:)

**Comment by Cantalapiedra** [comment]
Hi @TKsh6 ,

please, check https://github.com/eggnogdb/eggnog-mapper/issues/351 to see if it is the same issue.

Thank you.

Best,
Carlos

**Comment by TKsh6** [comment]
> 
thanks a lot:)

yours,
tk

**Comment by TKsh6** [comment]
> Hi @TKsh6 ,
> 
> please, check #351 to see if it is the same issue.
> 
> Thank you.
> 
> Best, Carlos

thanks a lot :)

yours,
tk

**Comment by Cantalapiedra** [comment]
Closing this issue. Not sure if really identified the problem or fixed yet.

Please, re-open or re-issue if needed.

Best,
Carlos
