### ISSUE TITLE
eggNOG mapper online tool

### ISSUE THREAD

**Issue by PaulaCat** [eggnogdb/eggnog-mapper#366]
Hi!

I want to use the eggNOG mapper to annotate some metagenomic assemblies. Unfortunately, the link to the online tool is not working. Therefore, I would be grateful if you give me further information on the availability of the online tool.

Thank you!

**Comment by Cantalapiedra** [comment]
Hi @PaulaCat ,

Unfortunately one main server in the infrastructure which serves eggNOG-mapper crashed.
We are working to have eggNOG-mapper available online as soon as possible, but we cannot tell a date yet.

Sorry for the incoveniences.

Best,
Carlos

see #361

**Comment by PaulaCat** [comment]
Thank you, Cantalapiedra! I will use the command line tool meanwhile. Have a good day!

**Comment by Cantalapiedra** [comment]
Hi,

glad to tell you that http://eggnog-mapper.embl.de/ is working again.
Please, report any problem/bug you may experience.

Sorry for the inconveniences.

Best,
Carlos

ps: I am closing this issue. Please, go to #361 , or re-issue or re-open this issue if you find any problem with the web tool

**Comment by PaulaCat** [comment]
Hi Carlos,

Thank you! I have been trying to upload my metagenomes but it seems like my assembly has more contigs than what is allowed to upload. Do you know a way around this situation? Should I better use the command line tool?

Thanks!!

**Comment by Cantalapiedra** [comment]
Hi @PaulaCat ,

yes, if you are able to use the command line efficiently I recommend you using it.
Another way would be to upload the contigs to the web service in chunks (splitting your contig files into several files).

Best,
Carlos

**Comment by PaulaCat** [comment]
Hi Carlos!

I successfully managed to perform the annotation with the command line version of the eggNOG mapper. I had a look at the results, and I noticed that the taxonomic annotation of the archaea present on my metagenome does not include groups like Bathyarchaeota, which are highly abundant in my samples. I was wondering if the Bathyarchaeota are still classified within the Crenarchaeota in the reference databases that the eggNOG mapper uses.

Thank you very much!

Paula.

**Comment by Cantalapiedra** [comment]
Hi @PaulaCat ,

Sincerely I don't know. Maybe you could check the taxonomic annotation of specific proteins and OGs at:

http://eggnog5.embl.de

Also, here http://eggnog5.embl.de/#/app/downloads I could find Crenarchaeota but couldn't find Bathyarchaeota.

Hopefully this is updated in a new iteration of the eggNOG DB.

I hope this makes sense.

Best,
Carlos
