### ISSUE TITLE
Incorrect gene positions in GFF file

### ISSUE THREAD

**Issue by xpolak37** [eggnogdb/eggnog-mapper#367]
I have the same problem as described in issue #324. All my annotated genomes contain an incorrect start and end in the gff file, they all start at position 1. For example job MM_fhq38t16, but unfortunately, this happened on all the genomes I annotated. However, the coordinates in the genepred.fasta file are correct. Am I doing something wrong? Thank you for your answer. 

Petra

**Comment by Cantalapiedra** [comment]
Hi Petra (@xpolak37),

Thank you for reporting this. 
It seems that we have a bug when generating the gff with some specific eggNOG-mapper modes, including the one used in the web for genomes. We are working to fix it as soon as possible.

Sorry for the inconveniences.

Best,
Carlos

**Comment by xpolak37** [comment]
Thank you very much @Cantalapiedra! Just one more question, can I expect a correct version anytime soon? I am using the results from your program in my bachelor thesis and just want to know if I should wait for the correction or I should use a different approach. 

Thanks and have a nice day.
Petra

**Comment by Cantalapiedra** [comment]
Hi @xpolak37 ,

I cannot promise, but we are working hard to fix it. Hopefully it will be ready by the end of this week.
But, again, this is just in case there are no contingencies.

Best,
Carlos

**Comment by xpolak37** [comment]
@Cantalapiedra I totally understand, thanks for your help.

**Comment by Cantalapiedra** [comment]
Hi,

I updated the repo, and hopefully the issue is fixed.
I need to update the web yet to use this new version (I will update the "News" section in the web once it is done).
I would be very grateful if you notify any bug or error related with this update.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
It should be ready on the web version too

**Comment by xpolak37** [comment]
Hi,
thanks for the correction. Unfortunately, I noticed the same problem as I described above also with proteins and CDS inputs. For example, in job M_sgpccmn_.

**Comment by Cantalapiedra** [comment]
Hi @xpolak37 ,

I guess that with proteins and CDS as input all the GFF start positions will be 1, since there are not contigs.
Not sure if this is what you mean.

Best,
Carlos
