### ISSUE TITLE
Not Outputting Correct Files

### ISSUE THREAD

**Issue by ashdederich** [eggnogdb/eggnog-mapper#368]
I downloaded the most recent version of eggnog-mapper available through conda and ran emapper.py with a .faa file as input.

I gave it the following options:

- use diamond blast
- ignore diamond warnings
- the --dmnd_algo option
- I said 'yes' to decorate_gff
- I gave it the --excel flag

When it finishes executing, I am missing all of the output files. There are no output files generated with the "prefix.emapper." beginning. What is going on?

Here is the command I ran for context:
```
emapper.py --cpu 16 -i 17978X1_NODE_1_length_607754_cov_33.762272.fasta.faa.gz -o eggnog17978X1 -output_dir $SCRDIR --override -m diamond --dmnd_ignore_warnings --dmnd_algo ctg --decorate_gff yes --excel
```

Here, $SCRDIR is an environment variable I created that leads to my scratch directory.

**Comment by Cantalapiedra** [comment]
Hi @ashdederich ,

I am not sure what could be happening.
Did you try running it in a local directory?
Did emapper.py finished OK?
What are the contents of the $SCRDIR after the emapper.py run?

Let's see if we can figure it out.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Hi @ashdederich ,

jaja I didn't notice the missing "-" in your previous message. You are right. Glad that it worked at last!

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Hi,

I will close this issue.
Please, re-open or re-issue if needed.

Best,
Carlos
