### ISSUE TITLE
error with diamond

### ISSUE THREAD

**Issue by cdanielmachado** [eggnogdb/eggnog-mapper#372]
Hello,

After conda installing the latest version of eggnog I get this error when calling diamond:

`Error running diamond: Error: Invalid output field: scovhsp`

The diamond version installed by conda is 0.9. I tried to upgrade to version 2.0 but conda gives a dependency conflict between the latest diamond and libgcc. 

Any suggestions?

Best regards,
Daniel

**Comment by Cantalapiedra** [comment]
Hi @cdanielmachado ,

did you try updating conda first?
Another solution would be to install diamond yourself and adding it to your PATH.

Best,
Carlos

**Comment by cdanielmachado** [comment]
Updating conda didn't work. And diamond refuses to install any version above 0.9.

But I managed to run eggnog with mmseqs instead of diamond :)

Should I expect any significant differences in terms of run time or results ?

**Comment by Cantalapiedra** [comment]
Hi @cdanielmachado ,

I am sorry to hear that. Maybe it depends on your OS then. Maybe you could take a look or ask here https://github.com/bbuchfink/diamond/issues

Glad that you can use mmseqs instead. There can be differences, both in runtime and sensitivity (check Fig 2 and other things here https://academic.oup.com/mbe/article/38/12/5825/6379734), but it will depend a lot on the size of your input (e.g. number of sequences), the level of sensitivity you aim for (are you working with very divergent queries?), and the available computational resources (if I recall correctly, MMseqs needs more free mem to achieve full speed).

Good luck!

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Thank you very much @levlitichev for reporting your solution. 
It seems a problem with channels then? Let's hope it is useful for others too.
Best,
Carlos

**Comment by cdanielmachado** [comment]
I can confirm that this solution worked for me, thank you :)
