### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by tarunpal33** [eggnogdb/eggnog-mapper#373]
http://eggnog-mapper.embl.de/ web-link not opening and 504 Gateway Time-out error is reflected.

**Comment by Cantalapiedra** [comment]
Hi @tarunpal33 ,

Thank you for reporting this. It seems the network under which eggnog-mapper runs is down.
I hope it is fixed soon.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
It should be up and running again.

Sorry for the inconveniences.

Best,
Carlos
