### ISSUE TITLE
Error: annotation went wrong for hit

### ISSUE THREAD

**Issue by chaohaoyu** [eggnogdb/eggnog-mapper#380]
Hi @Cantalapiedra ,

 I recently meet a strange problem. In short, when too many protein sequences are used (= 500), errors will occur, while when there are few protein sequences (= 50), the code will run normally.

the code is as follows：
**Error status: when protein sequences >= 500 (Only for testing) :**
```
$ head -1000 cw.pep.30470.fa > test_500
$ emapper.py -i test_500 -o cw_500 -d euk --cpu 10 --override
#  emapper-2.1.3
# emapper.py  -i test_500 -o cw_500 -d euk --cpu 10 --override
  /root/softwear/diamond blastp -d /root/miniconda3/envs/python3/lib/python3.7/site-packages/data/eggnog_proteins.dmnd -q /root/genome/cornus_wilsoniana/test_500 --threads 10 -o /root/genome/cornus_wilsoniana/cw.emapper.hits  --sensitive -e 0.001 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp

Funcional annotation of hits...
0 2.86102294921875e-06 0.00 q/s (% mem usage: 10.20, % mem avail: 89.75)
Traceback (most recent call last):
  File "/root/miniconda3/envs/python3/lib/python3.7/site-packages/eggnogmapper/annotation/annotator_worker.py", line 104, in annotate_hit_line
    eggnog_db = eggnog_db)
  File "/root/miniconda3/envs/python3/lib/python3.7/site-packages/eggnogmapper/annotation/annota.py", line 14, in summarize_annotations
    for fields in eggnog_db.get_annotations(','.join(['"%s"' % n for n in seq_names])):
  File "/root/miniconda3/envs/python3/lib/python3.7/site-packages/eggnogmapper/annotation/db_sqlite.py", line 82, in get_annotations
    , (seq,))
sqlite3.DatabaseError: database disk image is malformed
Error: annotation went wrong for hit ['CW10G22890', '29760.VIT_03s0038g02640.t01', 4.34e-132, 405.0, 1, 485, 1, 510, 51.1, 94.0, 75.4]. database disk image is malformed
```
**Success status: when protein sequences <= 50 (Only for testing) :**
```
$ head -100 cw.pep.30470.fa > test_50
$ emapper.py -i test_50 -o cw_50 -d euk --cpu 10 --override
#  emapper-2.1.3
# emapper.py  -i test_50 -o cw_50 -d euk --cpu 10 --override
  /root/softwear/diamond blastp -d /root/miniconda3/envs/python3/lib/python3.7/site-packages/data/eggnog_proteins.dmnd -q /root/genome/cornus_wilsoniana/test_100 --threads 10 -o /root/genome/cornus_wilsoniana/cw_100.emapper.hits  --sensitive -e 0.001 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
Funcional annotation of hits...
0 2.6226043701171875e-06 0.00 q/s (% mem usage: 10.10, % mem avail: 89.89)
44 3.6168830394744873 12.17 q/s (% mem usage: 10.10, % mem avail: 89.88)
Done
   /root/genome/cornus_wilsoniana/cw_50.emapper.hits
   /root/genome/cornus_wilsoniana/cw_50.emapper.seed_orthologs
   /root/genome/cornus_wilsoniana/cw_50.emapper.annotations
================================================================================
CITATION: .....
================================================================================
Total hits processed: 44
Total time: 327 secs
FINISHED
```

version (I don't think it's a version problem):
```
$ python --version
Python 3.7.11
$ sqlite3 --version
3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1
$ emapper.py --version
emapper-2.1.3
$ diamond --version
diamond version 2.0.14
```

Although I succeeded in using the following code in the end, I wasted a lot of time and hope to get an answer. Thanks.
```
for i in $(seq 1 305);do
j="$[$i*100]"
head -${j} cw.pep.30470.fa | tail -100 > temp.${i}
emapper.py -i temp.${i} -o temp.${i} -d euk --cpu 10
done
```

Best,
Haoyu

**Comment by chaohaoyu** [comment]
oh my god!

I succeeded in adding `--dbmem` parameter after reading other issues. 

The running speed is super fast. Total time: 1139 secs for 28697 hits !

Amazing!!!

But, now i have another question: How to specify only eukaryotic plant when using `-d euk` parameter. Because I'm worried that some plants proteins will be annotated into animals. This is what I don't want

**Comment by Cantalapiedra** [comment]
> Hi @Cantalapiedra ,
> 
> I recently meet a strange problem. In short, when too many protein sequences are used (= 500), errors will occur, while when there are few protein sequences (= 50), the code will run normally.
> 
> the code is as follows： **Error status: when protein sequences >= 500 (Only for testing) :**
> 
> ```
> $ head -1000 cw.pep.30470.fa > test_500
> $ emapper.py -i test_500 -o cw_500 -d euk --cpu 10 --override
> #  emapper-2.1.3
> # emapper.py  -i test_500 -o cw_500 -d euk --cpu 10 --override
>   /root/softwear/diamond blastp -d /root/miniconda3/envs/python3/lib/python3.7/site-packages/data/eggnog_proteins.dmnd -q /root/genome/cornus_wilsoniana/test_500 --threads 10 -o /root/genome/cornus_wilsoniana/cw.emapper.hits  --sensitive -e 0.001 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
> 
> Funcional annotation of hits...
> 0 2.86102294921875e-06 0.00 q/s (% mem usage: 10.20, % mem avail: 89.75)
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/python3/lib/python3.7/site-packages/eggnogmapper/annotation/annotator_worker.py", line 104, in annotate_hit_line
>     eggnog_db = eggnog_db)
>   File "/root/miniconda3/envs/python3/lib/python3.7/site-packages/eggnogmapper/annotation/annota.py", line 14, in summarize_annotations
>     for fields in eggnog_db.get_annotations(','.join(['"%s"' % n for n in seq_names])):
>   File "/root/miniconda3/envs/python3/lib/python3.7/site-packages/eggnogmapper/annotation/db_sqlite.py", line 82, in get_annotations
>     , (seq,))
> sqlite3.DatabaseError: database disk image is malformed
> Error: annotation went wrong for hit ['CW10G22890', '29760.VIT_03s0038g02640.t01', 4.34e-132, 405.0, 1, 485, 1, 510, 51.1, 94.0, 75.4]. database disk image is malformed
> ```
> 
> **Success status: when protein sequences <= 50 (Only for testing) :**
> 
> ```
> $ head -100 cw.pep.30470.fa > test_50
> $ emapper.py -i test_50 -o cw_50 -d euk --cpu 10 --override
> #  emapper-2.1.3
> # emapper.py  -i test_50 -o cw_50 -d euk --cpu 10 --override
>   /root/softwear/diamond blastp -d /root/miniconda3/envs/python3/lib/python3.7/site-packages/data/eggnog_proteins.dmnd -q /root/genome/cornus_wilsoniana/test_100 --threads 10 -o /root/genome/cornus_wilsoniana/cw_100.emapper.hits  --sensitive -e 0.001 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
> Funcional annotation of hits...
> 0 2.6226043701171875e-06 0.00 q/s (% mem usage: 10.10, % mem avail: 89.89)
> 44 3.6168830394744873 12.17 q/s (% mem usage: 10.10, % mem avail: 89.88)
> Done
>    /root/genome/cornus_wilsoniana/cw_50.emapper.hits
>    /root/genome/cornus_wilsoniana/cw_50.emapper.seed_orthologs
>    /root/genome/cornus_wilsoniana/cw_50.emapper.annotations
> ================================================================================
> CITATION: .....
> ================================================================================
> Total hits processed: 44
> Total time: 327 secs
> FINISHED
> ```
> 
> version (I don't think it's a version problem):
> 
> ```
> $ python --version
> Python 3.7.11
> $ sqlite3 --version
> 3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1
> $ emapper.py --version
> emapper-2.1.3
> $ diamond --version
> diamond version 2.0.14
> ```
> 
> Although I succeeded in using the following code in the end, I wasted a lot of time and hope to get an answer. Thanks.
> 
> ```
> for i in $(seq 1 305);do
> j="$[$i*100]"
> head -${j} cw.pep.30470.fa | tail -100 > temp.${i}
> emapper.py -i temp.${i} -o temp.${i} -d euk --cpu 10
> done
> ```
> 
> Best, Haoyu

Hi @chaohaoyu ,

I am not sure what is the problem with the sqlite DB, but if it is something a bit random, the more input sequences the more chances to happen. However, I am not sure about this. Also, some other issues pointed out that when the sqlite DB is on a NFS it often fails. Maybe the problem is related with that.

**Comment by Cantalapiedra** [comment]
> oh my god!
> 
> I succeeded in adding `--dbmem` parameter after reading other issues.
> 
> The running speed is super fast. Total time: 1139 secs for 28697 hits !
> 
> Amazing!!!

Yes, it is much faster using `--db-mem`. The only reason why it is not active by default is that it requires substantial available RAM to be used. See https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.7#Other_Requirements 

> 
> But, now i have another question: How to specify only eukaryotic plant when using `-d euk` parameter. Because I'm worried that some plants proteins will be annotated into animals. This is what I don't want

Note that if you are using diamond, the `-d` parameter has no effect (see https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.7#HMMER_search_options). In order to change taxonomic scope of annotations you may try other options, like `--tax_scope` or `--target_taxa` (see https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.7#annotation-options).

I hope this is of help.

Best,
Carlos

**Comment by chaohaoyu** [comment]
Thanks, @Cantalapiedra 

I get it! Thank you very much!

you can close this issue.

**Comment by Cantalapiedra** [comment]
Glad to be of help.

Please, re-open if you need further help.
