### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by TaoL-coder** [eggnogdb/eggnog-mapper#382]
http://eggnog-mapper.embl.de/ cannot open.

**Comment by Cantalapiedra** [comment]
Hi @TaoL-coder ,

sorry for the delay answering, and thank you very much for reporting this.
Lately, we are experiencing problems with the servers hosting eggnog-mapper.
Hopefully it will run find from now on.
Sorry for any inconvenience.

Best,
Carlos
