### ISSUE TITLE
HMMER database downloading error.

### ISSUE THREAD

**Issue by ap1438** [eggnogdb/eggnog-mapper#383]
(Eggnor) [group_bin]$ ./download_eggnog_data.py -H -d taxid 
Skipping eggnog.db database (already present). Use -f to force download
Skipping eggnog.taxa.db database (already present). Use -f to force download
Skipping diamond database (or already present). Use -f to force download
Skipping Pfam database (or already present). Use -P and -f to force download
Skipping MMseqs2 database (or already present). Use -M and -f to force download
Download HMMER database of tax ID taxid? [y,n] y
Please, specify a non-empty name for the database (e.g. Bacteria) [default:taxid]: 
Downloading HMMER database of tax ID taxid as "taxid" to /home/internal/anaconda3/envs/Eggnor/EGGNOG_DATA_DIR/hmmer/taxid
Note that this can take a long time for large taxonomic levels
cd /home/internal/anaconda3/envs/Eggnor/EGGNOG_DATA_DIR/hmmer/taxid; echo Downloading HMMs... && wget -N -nH --user-agent=Mozilla/5.0 --relative -r --no-parent --reject "index.html*" --cut-dirs=4 -e robots=off http://eggnog5.embl.de/download/eggnog_5.0/per_tax_level/taxid//taxid_hmms.tar.gz && echo Decompressing HMMs... && tar zxf taxid_hmms.tar.gz && echo taxid/* | xargs mv -t ./ && rm -r taxid && rm taxid_hmms.tar.gz; numf=$(find ./ | grep -c ".hmm$"); curr=0; cat /dev/null > taxid.hmm_tmp; for file in $(find ./ | grep ".hmm$"); do curr=$((curr+1)); echo "merging HMMs... ${file} (${curr}/${numf})"; cat "${file}" | sed -e "s/.faa.final_tree.fa//" -e "s/.faa.final_tree//" >> taxid.hmm_tmp; rm "${file}"; done; mv taxid.hmm_tmp taxid.hmm; (if [ -f taxid.hmm.h3i ]; then rm taxid.hmm.h3*; fi) && echo "hmmpress-ing HMMs... " && hmmpress taxid.hmm && echo "generating idmap file... " && cat taxid.hmm | grep "^NAME" | sed -e "s/^NAME *//" | awk '{print NR"	"$0}' > taxid.hmm.idmap && echo "removing single OG hmm files... " && echo ./*hmm | xargs rm; 
Downloading HMMs...
--2022-04-19 04:15:33--  http://eggnog5.embl.de/download/eggnog_5.0/per_tax_level/taxid//taxid_hmms.tar.gz
Resolving eggnog5.embl.de (eggnog5.embl.de)... 194.94.44.170
Connecting to eggnog5.embl.de (eggnog5.embl.de)|194.94.44.170|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-19 04:15:33 ERROR 404: Not Found.

hmmpress-ing HMMs... 

Error: File format problem in trying to open HMM file taxid.hmm.
File exists, but appears to be empty?

cd /home/internal/Sys_Bio/anaconda3/envs/Eggnor/EGGNOG_DATA_DIR/hmmer/taxid; echo Downloading FASTAs... && wget -N -nH --user-agent=Mozilla/5.0 --relative -r --no-parent --reject "index.html*" --cut-dirs=4 -e robots=off http://eggnog5.embl.de/download/eggnog_5.0/per_tax_level/taxid//taxid_raw_algs.tar && echo Decompressing FASTAs... && tar xf taxid_raw_algs.tar && echo taxid/* | xargs mv -t ./ && rm -r taxid && rm taxid_raw_algs.tar; numf=$(find ./ | grep -c ".faa.gz$"); curr=0; for file in $(find ./ | grep ".faa.gz$"); do curr=$((curr+1)); echo "processing FASTAs...  ${file} (${curr}/${numf})"; outf=$(echo "$file" | sed "s/\.raw_alg\.faa\.gz/\.fa/"); zcat "$file" | awk '/^>/{print; next}{gsub("-", ""); print}' > "$outf" && rm "$file"; done
Downloading FASTAs...
--2022-04-19 04:15:34--  http://eggnog5.embl.de/download/eggnog_5.0/per_tax_level/taxid//taxid_raw_algs.tar
Resolving eggnog5.embl.de (eggnog5.embl.de)... 194.94.44.170
Connecting to eggnog5.embl.de (eggnog5.embl.de)|194.94.44.170|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-19 04:15:34 ERROR 404: Not Found.

Finished.
I got this error for HMM database download.
I also tried to force it with -f but it didinot work

Please help me resolve this issue.

**Comment by Cantalapiedra** [comment]
Hi @ap1438 ,

You need to specify an actual "taxid" (taxonomical identifier) for the -d option. For example "-d 2" for Bacteria.

Best,
Carlos

**Comment by ap1438** [comment]
Thanks for your quick reply

I want to download all the available datasets for HMMER like bacteria(2).Can you guide me how can i do it , like which option will do so?

**Comment by Cantalapiedra** [comment]
Hi @ap1438 ,

You should use the previous command you showed, with a specific tax ID for the "-d" option.
For example `./download_eggnog_data.py -H -d 2` for Bacteria.
You may check the available options with `download_eggnog_data.py --help`.

All the available datasets should be found here http://eggnog5.embl.de/#/app/downloads

If you want to download all you may need to loop over all available taxa.
One option it could be looping through the list output by `emapper.py --list_taxa`

Best,
Carlos

**Comment by ap1438** [comment]
Thanks for your valuable time and suggestion.
