### ISSUE TITLE
emapper-2.1.3 hmmer can't find hmm db

### ISSUE THREAD

**Issue by PuspenduSardar** [eggnogdb/eggnog-mapper#388]
Hello!

Thank you very much for developing this great tool.
I have run into two issues. 1st is concerning hmm db and the second is diamond db. I have installed emapper in conda with a separate db location. I can confirm that the db is in my $PATH.

1st issue:
I downloaded the hmm database using `download_eggnog_data.py -H -d 2` for bacterial db. The download was successful and 206783 *.fa files were downloaded. I tried running with `-d` with absolute file-path (hmm folder) and it did't work. I am not sure if I need to concatenate all the *.fa files and `hmmpress` it before running emapper. Here is the error message:

`emapper.py  --cpu 32 -i bin.10_rename.fa --itype metagenome --output bin.10_rename -m hmmer -d /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm --pident 80 --evalue 1e-05 --tax_scope Bacteria --go_evidence non-electronic --target_orthologs one2one --genepred prodigal --output_dir ./eggnog_result3`

/home/usr/miniconda3/envs/functional_annotation/bin/prodigal -i 
/home/usr/sharing/bin.10_rename.fa -p meta -o 
/home/usr/sharing/emappertmp_prod_0h074aop/output.gff -f gff -a 
/home/usr/sharing/emappertmp_prod_0h074aop/output.faa -d 
/home/usr/sharing/emappertmp_prod_0h074aop/output.fna -s 
/home/usr/sharing/emappertmp_prod_0h074aop/output.orfs
hmmer.py:search DB: /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm
Database /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm not present. Use "hmmpress" to create the .h3* files
Database /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm not found
#emapper-2.1.3

"Bacteria_hmm" is the folder with all the *.fa files.

Could you please suggest how I can fix this?

2nd issue:
This one is minor, but I would like to solve it.
While I am using `-m diamond` with default diamond databases then everything goes well. But, when I try to use a specific database created using `create_dbs.py`, I need to give the full file path of the database after `--dmnd_db` otherwise emapper can't find the .dmnd file. Please note that all the `.dmnd` files are at the directory set with `EGGNOG_DATA_DIR` variable.

Could you please let me know where things are wrong?

Regards,
Puspendu

**Comment by Cantalapiedra** [comment]
Hi @PuspenduSardar ,

> Hello!
> 
> Thank you very much for developing this great tool. I have run into two issues. 1st is concerning hmm db and the second is diamond db. I have installed emapper in conda with a separate db location. I can confirm that the db is in my $PATH.

Thank you for your kind words. I will try to help below each issue.

> 
> 1st issue: I downloaded the hmm database using `download_eggnog_data.py -H -d 2` for bacterial db. The download was successful and 206783 *.fa files were downloaded. I tried running with `-d` with absolute file-path (hmm folder) and it did't work. I am not sure if I need to concatenate all the *.fa files and `hmmpress` it before running emapper. Here is the error message:
> 
> `emapper.py --cpu 32 -i bin.10_rename.fa --itype metagenome --output bin.10_rename -m hmmer -d /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm --pident 80 --evalue 1e-05 --tax_scope Bacteria --go_evidence non-electronic --target_orthologs one2one --genepred prodigal --output_dir ./eggnog_result3`
> 
> /home/usr/miniconda3/envs/functional_annotation/bin/prodigal -i /home/usr/sharing/bin.10_rename.fa -p meta -o /home/usr/sharing/emappertmp_prod_0h074aop/output.gff -f gff -a /home/usr/sharing/emappertmp_prod_0h074aop/output.faa -d /home/usr/sharing/emappertmp_prod_0h074aop/output.fna -s /home/usr/sharing/emappertmp_prod_0h074aop/output.orfs hmmer.py:search DB: /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm Database /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm not present. Use "hmmpress" to create the .h3* files Database /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm not found #emapper-2.1.3
> 
> "Bacteria_hmm" is the folder with all the *.fa files.
> 
> Could you please suggest how I can fix this?

What name did you give to the database when using the download script? Did you try using that same name with the -d option? What is the content of the /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm folder?

> 
> 2nd issue: This one is minor, but I would like to solve it. While I am using `-m diamond` with default diamond databases then everything goes well. But, when I try to use a specific database created using `create_dbs.py`, I need to give the full file path of the database after `--dmnd_db` otherwise emapper can't find the .dmnd file. Please note that all the `.dmnd` files are at the directory set with `EGGNOG_DATA_DIR` variable.

I guess this is how it is implemented. Take a look at https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.7#diamond-search-options

--dmnd_db FILE
path to diamond-compatible database. Useful to specify a location different than data/, EGGNOG_DATA_DIR or --data_dir.

So I guess that is only useful when you specify an actual path, and not just a DB name. If your new database is within EGGNOG_DATA_DIR I guess it should be enough to work without using the --dmnd_db option. Let me know if this is of help.

> 
> Could you please let me know where things are wrong?
> 
> Regards, Puspendu

Best,
Carlos

**Comment by PuspenduSardar** [comment]
Hi @Cantalapiedra

Thank you so much for your quick and kind reply.
Below are my comments.

> Hi @PuspenduSardar ,
> 
> > Hello!
> > Thank you very much for developing this great tool. I have run into two issues. 1st is concerning hmm db and the second is diamond db. I have installed emapper in conda with a separate db location. I can confirm that the db is in my $PATH.
> 
> Thank you for your kind words. I will try to help below each issue.
> 
> > 1st issue: I downloaded the hmm database using `download_eggnog_data.py -H -d 2` for bacterial db. The download was successful and 206783 *.fa files were downloaded. I tried running with `-d` with absolute file-path (hmm folder) and it did't work. I am not sure if I need to concatenate all the *.fa files and `hmmpress` it before running emapper. Here is the error message:
> > `emapper.py --cpu 32 -i bin.10_rename.fa --itype metagenome --output bin.10_rename -m hmmer -d /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm --pident 80 --evalue 1e-05 --tax_scope Bacteria --go_evidence non-electronic --target_orthologs one2one --genepred prodigal --output_dir ./eggnog_result3`
> > /home/usr/miniconda3/envs/functional_annotation/bin/prodigal -i /home/usr/sharing/bin.10_rename.fa -p meta -o /home/usr/sharing/emappertmp_prod_0h074aop/output.gff -f gff -a /home/usr/sharing/emappertmp_prod_0h074aop/output.faa -d /home/usr/sharing/emappertmp_prod_0h074aop/output.fna -s /home/usr/sharing/emappertmp_prod_0h074aop/output.orfs hmmer.py:search DB: /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm Database /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm not present. Use "hmmpress" to create the .h3* files Database /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm not found #emapper-2.1.3
> > "Bacteria_hmm" is the folder with all the *.fa files.
> > Could you please suggest how I can fix this?
> 
> What name did you give to the database when using the download script? Did you try using that same name with the -d option? What is the content of the /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm folder?

**Update:**
My mistake. There are 206778 *.fa files and 5 `Bacteria_hmm.hmm*` files in the /home/usr/sharing/database/eggnog_db/hmmer/Bacteria_hmm folder. I didn't see those .hmm files earlier. can I delete all those .fa files if hmmer is going to use only the .hmm files?

Many thanks for your time.

> 
> > 2nd issue: This one is minor, but I would like to solve it. While I am using `-m diamond` with default diamond databases then everything goes well. But, when I try to use a specific database created using `create_dbs.py`, I need to give the full file path of the database after `--dmnd_db` otherwise emapper can't find the .dmnd file. Please note that all the `.dmnd` files are at the directory set with `EGGNOG_DATA_DIR` variable.
> 
> I guess this is how it is implemented. Take a look at https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.7#diamond-search-options
> 
> --dmnd_db FILE path to diamond-compatible database. Useful to specify a location different than data/, EGGNOG_DATA_DIR or --data_dir.
> 
> So I guess that is only useful when you specify an actual path, and not just a DB name. If your new database is within EGGNOG_DATA_DIR I guess it should be enough to work without using the --dmnd_db option. Let me know if this is of help.

This helps. Thanks for clearing it up.

> 
> > Could you please let me know where things are wrong?
> > Regards, Puspendu
> 
> Best, Carlos

Regards,
Puspendu

**Comment by Cantalapiedra** [comment]
Hi @PuspenduSardar ,

If I recall correctly, you really need those fasta files. The hmm profiles are used first to determine the Orthologous Group (OG) Then, the fasta file of each of those OGs is used to obtain the best hit of a specific query within its corresponding OG (the "seed ortholog").

I hope this makes sense.

Best,
Carlos

**Comment by PuspenduSardar** [comment]
> Hi @PuspenduSardar ,
> 
> If I recall correctly, you really need those fasta files. The hmm profiles are used first to determine the Orthologous Group (OG) Then, the fasta file of each of those OGs is used to obtain the best hit of a specific query within its corresponding OG (the "seed ortholog").
> 
> I hope this makes sense.
> 
> Best, Carlos

Hi @Cantalapiedra,

Many thanks for helping me on this.
Yes, it make sense.

Regards,
Puspendu
