### ISSUE TITLE
Emapper in job arrays takes too long to complete

### ISSUE THREAD

**Issue by ozan-kanbertay** [eggnogdb/eggnog-mapper#392]
Hello,

I am running emapper-2.1.7 on a HPC cluster with job arrays via Slurm. I have chunks of 500 CDS files for running in parallel. When I run emapper on a single file it takes less than 5 minutes. Up to 100 jobs can run in parallel, so I would expect all jobs to complete in less than an hour. However, it takes between 6 and 8 hours or more.

The problem is that when put in an array, most of the jobs took much longer than individual runs when I monitor the running times. I have contacted technical support for the cluster and here is what they told me:

> It seems that for the first 5-10 minutes, your job consumes resources and afterwards it just does nothing anymore. In the first part, the program 'diamond' is doing a lot of work. After that not much happens anymore, the 'emapper.py' still runs, but doesn't use many resources. So it seems that the python script doesn't exit correctly.

Here is my script for submitting a job array via Slurm:

```
#!/bin/bash

#SBATCH --cpus-per-task=24
#SBATCH --mem-per-cpu=3G
#SBATCH -C scratch
#SBATCH --time=10:00:00

shopt -s nullglob
arr=(*.fna.gz)

module purge
module load python

export PATH=/usr/users/kanbertay/.local/bin:"$PATH"
export EGGNOG_DATA_DIR=/scratch/users/kanbertay/eggnog-mapper-data/

mkdir -p annotations

emapper.py --cpu 24 --itype CDS -i ${arr[$SLURM_ARRAY_TASK_ID]} -o $(basename ${arr[$SLURM_ARRAY_TASK_ID]} .fna.gz) --output_dir annotations --temp_dir $TMP_LOCAL
```

I call the sbatch with this line:

`sbatch -a 0-$(($(ls ./*.fna.gz | wc -l)-1)) emapper-array.sh`

Do you have any suggestions to solve this problem?

**Comment by Cantalapiedra** [comment]
Hi @ozan-kanbertay ,

Could you share the emapper.py output/error?
Is the eggnog.db sqlite file in a network drive? Maybe this or maybe not, but it has often been reported to be a problem.

Besides that, if you have at least 44-48 GB of RAM in cluster nodes, you may try running less con current jobs but with `--dbmem` option, which usually speeds up the annotation step.

Also, to avoid running everything from scratch every time, you may want to use the --resume option, or run only the annotation step, to avoid repeating the diamond mapping step.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Hi @ozan-kanbertay ,

I don't know either why that difference between one or two steps.
Let me know how it goes, or if you find any clue about what is happening, or if you face further problems.

Best,
Carlos

**Comment by carlosj-rr** [comment]
Hello @ozan-kanbertay and @Cantalapiedra,

Sorry for barging in, but since the issue was open, I wanted to hop on and ask something linked to this. I've been having a really hard time running emapper.py with the hmmer search option (for a diversity of reasons that I don't think are related to the software itself), on the last (mostly successful) runs I ended up with the *.emapper.hits file, but emapper was unable to find the reference database for annotation (again, I think this was my mistake). Would you be willing, @ozan-kanbertay, to share the commands you ran in order to do the annotation separately from the search? Otherwise, @Cantalapiedra, where in the manual could I find an example for an annotation-only command line to process the hits file from an emapper hmmer search?

Thanks to both so much!

Best wishes,

-carlos

**Comment by Cantalapiedra** [comment]
Hi @carlosj-rr ,

If you only have the .emapper.hits file, I guess that the best you could try is to run again emapper.py with the --resume option. Check https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.8#execution-options and the second paragraph here: https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.8#v217

I would first make a backup of your hits file, just in case it is cleared if the command was not successfully resumed.

However, you should have a .emapper.seed_orthologs file if the script really crashed before the annotation step. It is difficult to know what happened without seeing your command and output/error messages.

Best,
Carlos

**Comment by carlosj-rr** [comment]
Hello Carlos,

Ah perfect, yes, thanks a lot! I will try that and report back. If I get an error, I'll post the message here, that way I can provide more information.

Best wishes,

-carlos

**Comment by carlosj-rr** [comment]
Hello all,

In the end, it was a problem of it not finding the databases in the right place...all good now on my side (but I can't close the issue!).

Best wishes,

-carlos

**Comment by Cantalapiedra** [comment]
Thank you for reporting back!
Best,
Carlos

**Comment by qbdong122** [comment]
> I separated the whole process into search and annotation phases for each single job. This seems to resolve the issue for now. Each job takes minutes not hours (or indefinite) as before. But I don’t quite understand why running a single job without separate steps results in program to not exit. Anyway, I’ll do some more tests and let you know if the issue persists. Thanks again.
@ozan-kanbertay ，Hi, ozan-kanbertay.
What did you actually do when you saying "separated the whole process into search and annotation phases for each single job"? I also met this issue: I split my job into 1000 batch, most of the jobs took much longer than individual runs when I monitor the running times
