### ISSUE TITLE
Error using eggnog mapper web.

### ISSUE THREAD

**Issue by FuyuanQ** [eggnogdb/eggnog-mapper#403]
Hello!
I'm trying to use eggnog mapper wep (http://eggnog-mapper.embl.de/). But there are two problems.
1. I was unable to submit genomic data successfully. (There is a circle turning all the time on the page, which should indicate that it is working, but the process cannot be completed, no matter how long it takes.)
2. After I successfully submitted the protein data, the page displayed "[Errno 28] No space left on device".

This is my first time to use eggnog mapper. I don't know how to solve this situation. I'm looking forward to your guidance.
Thank you very much for your help.

**Comment by Cantalapiedra** [comment]
Hi @FuyuanQ ,

Thank you very much for reporting this.
We have a problem with drives "virtually" filling periodically.
We have tried several things to try to fix it, without success.
Therefore, warnings as yours are super valuable.

I hope it is fixed now and you are able to submit your jobs successfully.
If the issue persists, just tell me, please.

Best,
Carlos

**Comment by xiasijian** [comment]
Now it is also, error for no space on device.

**Comment by Cantalapiedra** [comment]
Hi @xiasijian ,

Thank you very much for reporting this.
Hopefully, it should be working fine now.

Best,
Carlos

**Comment by xiasijian** [comment]
Thanks♪(･ω･)ﾉ

**Comment by jpmgzmn** [comment]
Hi @Cantalapiedra ,

I happened to experience the same problem as in this thread too. I tried .fa and .fa.gz files already but I get the same issue. The page just loads for a while until I get an error (either the same as the one reported here in this thread or the same as in #458 ). 

Thank you so much!

**Comment by Cantalapiedra** [comment]
Hi, did you experience this issue again recently?

**Comment by jpmgzmn** [comment]
> Hi, did you experience this issue again recently?

Hi @Cantalapiedra ! I resolved the issue already. Apparently, it was just about the amount of sequences I tried to run. So I just broke down all my sequences into several files. My bad. Thank you so much, though!

**Comment by Cantalapiedra** [comment]
Hi @jpmgzmn ,

Thank you for reporting back and glad that you solved it!

Best,
Carlos

**Comment by LJH0406** [comment]
> > 您好，您最近是否又遇到了这个问题？
> 
> 你好@Cantalapiedra！我已经解决了这个问题。显然，问题出在我尝试运行的序列数量上。所以我只是将所有序列分解成几个文件。这是我的错。不过还是非常感谢！

Hello! The compressed file I submitted is 1.5GB, is that large? It also keeps loading.
