### ISSUE TITLE
Run against  legacy eggnog_3.0

### ISSUE THREAD

**Issue by matthpich** [eggnogdb/eggnog-mapper#410]
Hi,
Thanks for the great tool!
For legacy reasons, is it possible to run emapper on eggnog_3.0?
If yes, how to do so?
Many thanks for your help!

**Comment by Cantalapiedra** [comment]
Hi @matthpich,

Thank you for your kind words.

To be honest, I never tried to use eggnog 3 with eggnog-mapper.
I am not sure whether there is an eggnog-mapper version able to run with an eggnog3 DB, but my bet is that there is not.
Note that, if I am not mistaken, eggnog-mapper was developed for eggnog 4.5 (https://academic.oup.com/mbe/article/34/8/2115/3782716).

Maybe you could try downloading files from here http://eggnog.embl.de/version_3.0/downloads.html and use them yourself to map your sequences to those files, either with HMMER to hmms or with diamond to proteins. The hard part may be obtaining the annotations from the mappings.

I hope that you find the way to do what you need.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
I am closing this issue.
Please, re-open if needed.
