### ISSUE TITLE
sqlite3.DatabaseError: malformed database schema (prots) - near "WITHOUT": syntax error

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [eggnogdb/eggnog-mapper#413]
when i run the command "~/software/eggnog-mapper-master/emapper.py -i hap2_protein.fasfa  --output xx1 --override " 
its show error 
The output (if any) follows:

#  emapper-2.1.9
# emapper.py  -i hap2_protein.fasfa --output xx1 --override
  /public/home/zhaoli/software/diamond-master/bin/diamond blastp -d /public/home/zhaoli/software/eggnog-mapper-master/data/eggnog_proteins.dmnd -q /public/home/zhaoli/dama/annotation/hap2/interopro/hap2_protein.fasfa --threads 1 -o /public/home/zhaoli/dama/annotation/hap2/interopro/xx1.emapper.hits --tmpdir /public/home/zhaoli/dama/annotation/hap2/interopro/emappertmp_dmdn_zucc7v4p --sensitive --iterate -e 0.001 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
Error: annotation failed. malformed database schema (prots) - near "WITHOUT": syntax error
when check the log, its show
sqlite3.DatabaseError: malformed database schema (prots) - near "WITHOUT": syntax error

and I check in the website https://github.com/eggnogdb/eggnog-mapper/issues/291
 and  update the sqlite3 and diamond version 

![image](https://user-images.githubusercontent.com/101324838/193436345-89444269-e3e0-4c89-b187-26c0013301a0.png)
![image](https://user-images.githubusercontent.com/101324838/193436353-57365f19-afed-4951-9460-585aa2e2e72a.png)
![image](https://user-images.githubusercontent.com/101324838/193436358-2e2ef09d-0327-4e93-93a2-afc286e002c4.png)

but it was still error , how could it solve this error .
thank you

**Comment by Jiangjiangzhang6** [comment]
use the iqlite 36 its ok

**Comment by Cantalapiedra** [comment]
Hi @Jiangjiangzhang6 ,

Glad that you solved it. As it is shown in issue #291 there seems to be problems with different sqlite versions.
