### ISSUE TITLE
How to download virus DIAMOND database

### ISSUE THREAD

**Issue by meenachakra** [eggnogdb/eggnog-mapper#416]
Hello,

Thank you for the tool! We are trying to make a virus-specific DIAMOND protein database for use with EGGNOG. We utilized the following commands, however no taxa were found and no proteins are present in the resulting file. In fact, viruses don't even seem to be present in our e5.taxid_info.tsv.

`create_dbs.py -m diamond --dbname virus --taxa Viruses`
`create_dbs.py -m diamond --dbname virus --taxids 10239`
`create_dbs.py -m diamond --dbname virus --taxa virus`

Any advice would be most appreciated. Thank you so much in advance.

**Comment by Cantalapiedra** [comment]
Hi @meenachakra ,

Yes, it seems there are no viruses within e5.taxid_info.tsv.

Maybe you could create the diamond protein database downloading the protein sequences from:
http://eggnog5.embl.de/#/app/downloads

More specifically from:
http://eggnog5.embl.de/download/eggnog_5.0/per_tax_level/10239/10239_raw_algs.tar

You may need to remove gaps from the alignment, and run diamond yourself, though.

I hope this is of help.

Best,
Carlos

**Comment by meenachakra** [comment]
Thanks so much for your quick reply! Really appreciate it.

**Comment by yipinto** [comment]
Hi @Cantalapiedra,
Just want to verify- the viral database (10239) that you recommended @meenachakra to download is part of the eggNog5.0 db, so the OG on 10239 should be included in the default eggnog5.0 db, right?
We are wondering if viral specific 10239 db has the potential to annotate genes that were not annotated by mapping to eggnog5.0.
Thanks
