### ISSUE TITLE
eggnog-mapper web server seems blocked 

### ISSUE THREAD

**Issue by zjhcarbonic** [eggnogdb/eggnog-mapper#417]
Hello.
Could you check the online service?  many jobs are queued because a user has submitted a large number of sequences

**Comment by Cantalapiedra** [comment]
Hi @zjhcarbonic ,

Yes, I don't know what was going on yesterday but everything was super slow. Maybe some automated submission, I don't know.
I hope everything runs ok now.

Thank you for reporting it.

Best,
Carlos
