### ISSUE TITLE
Empty output after running Eggnog CLI

### ISSUE THREAD

**Issue by nitinra** [eggnogdb/eggnog-mapper#418]
Hello, 

I tried running eggNOG on my test genome. After the eggNOG run, all the output was empty. Here are my files:

[fasta file](https://github.com/eggnogdb/eggnog-mapper/files/9793021/eller_fa.txt)
[ella.emapper.seed_orthologs.txt](https://github.com/eggnogdb/eggnog-mapper/files/9793022/ella.emapper.seed_orthologs.txt)
[ella.emapper.orthologs.txt](https://github.com/eggnogdb/eggnog-mapper/files/9793023/ella.emapper.orthologs.txt)
[ella.emapper.hits.txt](https://github.com/eggnogdb/eggnog-mapper/files/9793024/ella.emapper.hits.txt)
[ella.emapper.decorated_gff.txt](https://github.com/eggnogdb/eggnog-mapper/files/9793025/ella.emapper.decorated_gff.txt)
[ella.emapper.annotations.txt](https://github.com/eggnogdb/eggnog-mapper/files/9793026/ella.emapper.annotations.txt)
[01.test_script_sh.txt](https://github.com/eggnogdb/eggnog-mapper/files/9793027/01.test_script_sh.txt)
[01.test_out.txt](https://github.com/eggnogdb/eggnog-mapper/files/9793029/01.test_out.txt)
[01.test_err.txt](https://github.com/eggnogdb/eggnog-mapper/files/9793030/01.test_err.txt)

Here is my script: 
`emapper.py -i eller.fa --override --cpu 28 --mp_start_method forkserver \
--num_servers 2 -m diamond --evalue 0.001 \
--score 60 --pident 40 --query_cover 20 --subject_cover 20 --itype proteins \
--tax_scope auto --target_orthologs all \
--go_evidence experimental --pfam_realign realign --report_orthologs --decorate_gff yes -o ella`

**Comment by Cantalapiedra** [comment]
I used the fasta file that you linked to run emapper again, because #417 reported some temporary error in the server. It seems that the re-run is yielding results now: http://eggnog-mapper.embl.de/job_status?jobname=MM_wsj24dqy

**Comment by nitinra** [comment]
Hello, 

Thanks for the response. Yes, the web eggNOG run seems to be working fine, but the command line version (stand alone version) seems to produce empty files. I have used the same command that I previously used on the web eggNOG. Is there any reason it is failing with the stand alone version?

**Comment by nitinra** [comment]
I have about 300 + genomes that I want to annotate and I figured using the command line version would be the best. Thank you for your help!

**Comment by Cantalapiedra** [comment]
Hi @nitinra ,

In the case of the stand alone version I would need more info.

What is the exact command you are running and what is the output and error you get?

**Comment by nitinra** [comment]
Hi @Cantalapiedra , 

I have included all the files in the main post of this thread. The script is [01.test_script_sh.txt](https://github.com/eggnogdb/eggnog-mapper/files/9793027/01.test_script_sh.txt),  the run output is here: [01.test_out.txt](https://github.com/eggnogdb/eggnog-mapper/files/9793029/01.test_out.txt) and the error is here: [01.test_err.txt](https://github.com/eggnogdb/eggnog-mapper/files/9793030/01.test_err.txt)

All the other output files from the run are also in my main post.

**Comment by Cantalapiedra** [comment]
> I have about 300 + genomes that I want to annotate and I figured using the command line version would be the best. Thank you for your help!

It is likely that is going to be more convenient for you than the web version.
However, note that using the stand alone version is not so straightforward, specially if you are looking for efficient runs.
I recommend you to check the wiki page at the github and look for important parameters (like --dbmem) and whether you have the computational resources available to make it more efficient than just using the web.

**Comment by Cantalapiedra** [comment]
> e also in my main

Sorry, I thought these were files from the web. Now I see the slurm script. Let me check them.

**Comment by Cantalapiedra** [comment]
It seems that diamond worked fine but the problem is with the annotation step.
It is weird that it is finishing without rising any error though.
What are the contents of /work/nitinr/eggnog_data_dir?

**Comment by nitinra** [comment]
Here is what is in that directory:

<img width="860" alt="Screen Shot 2022-10-15 at 6 23 20 PM" src="https://user-images.githubusercontent.com/70153351/196009793-8c8b6c47-0b69-45db-8f48-dac7fa2ed1b5.png">

**Comment by Cantalapiedra** [comment]
Thank you.

I did a test. I downloaded your .seed_orthologs file, and used the 100 first rows (actually, 94 seed orthologs after removing the "#" comments) to perform only the annotation step:

`emapper.py -m no_search --annotate_hits_table ./ella.emapper.seed_orthologs.100.txt -o out`

I obtained 94 rows of annotations.
So, to be honest I don't know why you are not getting any result.
Could you try to replicate the test I did to check whether it works for you or not?

**Comment by nitinra** [comment]
it worked with the command that you tried as above! Thank you. Is there a way I can decorate the gff and get the pfam realignment from the seed_orthologs file???? Thank you so much!
<img width="640" alt="Screen Shot 2022-10-16 at 7 43 28 AM" src="https://user-images.githubusercontent.com/70153351/196033501-e885cc17-bc68-4f6b-87c9-a8e73ff9bab7.png">

**Comment by nitinra** [comment]
I think I might have figured out where the error is occuring. It is in the pfam realignment step. I reran the analysis with the following command: 

`/work/nitinr/eggnog-mapper/emapper.py -i eller.fa --override --cpu 28 --evalue 0.001 -m diamond --dmnd_ignore_warnings --score 60 --pident 40 --query_cover 20 --subject_cover 20 --itype proteins --target_orthologs all --tax_scope 6656 --num_servers 2 --go_evidence experimental --report_orthologs --decorate_gff yes -o lise`

When I look at the files, it looks like it has annotated everything! 
<img width="1057" alt="Screen Shot 2022-10-16 at 10 18 01 AM" src="https://user-images.githubusercontent.com/70153351/196040508-1ac94ee9-0045-4b59-8c16-8311c2ff8393.png">

Is there any other way to get Pfam realignment done??

**Comment by Cantalapiedra** [comment]
If I am not mistaken, the PFAM database is missing from your EGGNOG_DATA_DIR. You should install it with `download_eggnog_data.py`. Maybe (I am not sure), the PFAM realignment is failing due to that.

Also, if you are going to annotate +300 genomes, you may benefit from other emapper.py options, as I told you before. Specially, if you have >45GB RAM available, the `--dbmem` option makes the annotation step much faster than without it.

Best,
Carlos

**Comment by nitinra** [comment]
everything works perfectly! It was indeed the pfam database.. Thank you all for your help!

**Comment by Cantalapiedra** [comment]
Glad that it worked! Sorry for the inconveniences. Good luck!

Best,
Carlos

**Comment by giacomomutti** [comment]
Hello! I recently had the same issue and I think it would be great if emapper failed if --pfam_realign is specified and the pfam db is not in the eggnog folder instead of printing empty outputs. Thanks!

**Comment by Cantalapiedra** [comment]
@giacomomutti I will annotate this as feature request. Thank you!
