### ISSUE TITLE
Problem with eggnog.db data

### ISSUE THREAD

**Issue by alajus** [eggnogdb/eggnog-mapper#419]
Hello developer,
I want to use the sqlite database eggnog.db but as soon as I query it I get the following error message:
sqlite3 eggnog.db
SQLite version 3.7.17 2013-05-20 00:56:22 Enter ".help" for instructions Enter SQL statements terminated with a ";"
sqlite> .schema
Error: malformed database schema (prots) - near "WITHOUT": syntax error

I am using sqlite 3.7.17. What should I do?
Best regards
Aurélie

**Comment by Cantalapiedra** [comment]
Hi @alajus ,

Please, check other similar issues like https://github.com/eggnogdb/eggnog-mapper/issues/413
It seems that this kind of problem use to be solved by using a different sqlite version.

If this does not solve your problem, please tell me.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
I am closing this issue.
Please, re-open if needed.
