### ISSUE TITLE
Error in using Eggnog web tool

### ISSUE THREAD

**Issue by Rosh2496** [eggnogdb/eggnog-mapper#425]
For two days when I am trying to open the Eggnog website I am seeing this error .
<html>
<body>
<pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Job MM_opottcnu was not found.</pre>

Request Method: | GET
-- | --
http://eggnog-mapper.embl.de/
3.2.4
Exception
Job MM_opottcnu was not found.
/services/emapper_web/emapper_web/job_info.py, line 101, in get_job_info
/home/ubuntu/services/miniconda3/bin/python
3.7.7
['/services/emapper_web',  '/services/miniconda3/bin',  '/home/ubuntu/services/miniconda3/lib/python37.zip',  '/home/ubuntu/services/miniconda3/lib/python3.7',  '/home/ubuntu/services/miniconda3/lib/python3.7/lib-dynload',  '/home/emapper/.local/lib/python3.7/site-packages',  '/home/ubuntu/services/miniconda3/lib/python3.7/site-packages']
Fri, 28 Oct 2022 05:37:18 +0000

</body>
</html>

**Comment by Cantalapiedra** [comment]
Hi @Rosh2496 ,

Thank you very much for reporting this.
A few days ago we had problems with the servers and this has caused some inconsistencies with the server files.
I will try to fix it as soon as possible.

Best,
Carlos

**Comment by Cantalapiedra** [comment]
I hope it is fixed now. Thank you very much again.

**Comment by Rosh2496** [comment]
It is fixed now. Thank you!

**Comment by Cantalapiedra** [comment]
Thanks you!
