### ISSUE TITLE
eggnog reference protein id > CDS

### ISSUE THREAD

**Issue by matthpich** [eggnogdb/eggnog-mapper#430]
Hi,
Thanks for the great tool.
Can you advise how to go from an eggnog reference protein id to its corresponding CDS sequence?
For intance, 264199.stu1398
Many thanks for your help.
Best,
Matt

**Comment by Cantalapiedra** [comment]
Hi @matthpich ,

I don't know if there is a way to obtain the CDS sequence for eggNOG 5 proteins.

You may obtain the protein sequence by looking for the protein ID (stu1398) in eggnog5.embl.de and then downloading the protein sequences of the (smaller?) group, which should include your query among them. But, again, this will be the protein sequence, and not the CDS sequence.

You may also use http://eggnog5.embl.de/#/app/api to do the same thing.

Best,
Carlos

**Comment by matthpich** [comment]
Thanks a lot for the prompt answer and for the lead.

**Comment by Cantalapiedra** [comment]
I am closing this issue.
Please, re-open or re-issue if needed.
