### ISSUE TITLE
eggNOG-mapper job MM_bnezijl6 finished, with status failed

### ISSUE THREAD

**Issue by dbn202** [eggnogdb/eggnog-mapper#431]
Hi,
I used eggnog mapper web tool (http://eggnog-mapper.embl.de/)
After I submit my data, I started to run and then it failed 

Any idea why? Is it an error with the tool?

**Comment by Cantalapiedra** [comment]
Hi @dbn202 ,

Is your file a .tar file?
Maybe that is the reason of the error that you can see in `emapper.out` at http://eggnog-mapper.embl.de/MM_bnezijl6/

If that is the case, please use a FASTA file as input.

Best,
Carlos
