### ISSUE TITLE
502 Bad Gateway error when accessing Eggnog-mapper web

### ISSUE THREAD

**Issue by gdalba** [eggnogdb/eggnog-mapper#442]
Hi all,

I wonder if anyone else has been facing this problem since yesterday (02/14) when trying to access the web version of eggnog-mapper? Would this affect the ability to install it locally?

Many thanks for any help provided !

**Comment by 871378200** [comment]
Yes, I also encountered this problem，hope it will work soon.

**Comment by gdalba** [comment]
I am able to access it now !

**Comment by Cantalapiedra** [comment]
Hi,

Thank you very much for reporting this. Sorry guys to not answer before. 
Our servers underwent maintenance and I prioritized make it working again.
Please, re-open or re-issue if you encounter any issues with the web.

Best,
Carlos

**Comment by gdalba** [comment]
Many thanks, Carlos! Awesome work on Eggnog-mapper :)

**Comment by Cantalapiedra** [comment]
:) thank you, and also for your patience
