### ISSUE TITLE
unknown gene function clarification: S vs -

### ISSUE THREAD

**Issue by franciscozorrilla** [eggnogdb/eggnog-mapper#443]
Some unknown genes are annotated with the `S` COG category, while other simply have a `-`. Is there a difference between these two types of unknown genes or are they effectively equivalent?

**Comment by Cantalapiedra** [comment]
Hi @franciscozorrilla ,

Technically the difference would be that the proteins of the OG (Orthologous Group) are actually annotated as "S", whereas when there is a "-" it is likely that there is no annotation or not "consensus" COG for the OG.

Best,
Carlos
