### ISSUE TITLE
Error running 'mmseqs search'

### ISSUE THREAD

**Issue by Ben-41** [eggnogdb/eggnog-mapper#448]
Hi,
here is my command when I try to run the program:

`emapper.py -m mmseqs --itype metagenome -i $infile -o $outfile --override --evalue 0.00001 --cpu 0`

**and then I've got a error messages:**

emapper-2.1.4
emapper.py  -m mmseqs --itype metagenome -i /scratch/PI/boqianpy/App/share_data/fangwenyu/cd-hit_seawater/temp/total.fasta -o /scratch/PI/boqianpy/App/share_data/fangwenyu/eggnog_seawater/ --override --evalue 0.00001 --cpu 0
[1;33m  /scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/eggnogmapper/bin/mmseqs createdb /scratch/PI/boqianpy/App/share_data/fangwenyu/cd-hit_seawater/temp/total.fasta /home/wfangab/result/procedure/eggmapper/emappertmp_mmseqs_7sg0_r75/96329a32d34e448f849b912fe00fd020 --dbtype 2[0m
[1;33m  /scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/eggnogmapper/bin/mmseqs search -a true /home/wfangab/result/procedure/eggmapper/emappertmp_mmseqs_7sg0_r75/96329a32d34e448f849b912fe00fd020 /scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/db/mmseqs/mmseqs.db /home/wfangab/result/procedure/eggmapper/emappertmp_mmseqs_7sg0_r75/372ff545666e44f98a253e0e9715ec3e /home/wfangab/result/procedure/eggmapper/emappertmp_mmseqs_7sg0_r75 --start-sens 3 --sens-steps 3 -s 7 --threads 40[0m
Error running 'mmseqs search': /home/wfangab/result/procedure/eggmapper/emappertmp_mmseqs_7sg0_r75/5286583486545266364/blastp.sh: line 99: 112646 Killed                  $RUNNER "$MMSEQS" prefilter "$INPUT" "$TARGET" "$TMP_PATH/pref_$STEP" $PREFILTER_PAR -s "$SENS"

**In addition, I have tried using diamond instead,**

`emapper.py -m diamond --itype metagenome -i $infile -o $outfile --override --evalue 0.00001 --cpu 0`

**and I got error message again:**

Traceback (most recent call last):
  File "/scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/emapper.py", line 660, in <module>
    emapper = Emapper(args.itype, args.genepred, args.mode, (not args.no_annot),
  File "/scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/eggnogmapper/emapper.py", line 102, in __init__
    silent_rm(pjoin(self.output_dir, outf))
  File "/scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/eggnogmapper/common.py", line 280, in silent_rm
    os.remove(f)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/PI/boqianpy/App/share_data/fangwenyu/eggnog_seawater/.emapper.hits'
emapper-2.1.4
emapper.py  -m diamond --itype metagenome -i /scratch/PI/boqianpy/App/share_data/fangwenyu/cd-hit_seawater/temp/total.fasta -o /scratch/PI/boqianpy/App/share_data/fangwenyu/eggnog_seawater/ --override --evalue 0.00001 --cpu 0
Traceback (most recent call last):
  File "/scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/emapper.py", line 660, in <module>
    emapper = Emapper(args.itype, args.genepred, args.mode, (not args.no_annot),
  File "/scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/eggnogmapper/emapper.py", line 102, in __init__
    silent_rm(pjoin(self.output_dir, outf))
  File "/scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/eggnogmapper/common.py", line 280, in silent_rm
    os.remove(f)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/PI/boqianpy/App/share_data/fangwenyu/eggnog_seawater/.emapper.hits'
emapper-2.1.4
emapper.py  -m diamond --itype metagenome -i /scratch/PI/boqianpy/App/share_data/fangwenyu/cd-hit_seawater/temp/total.fasta -o /scratch/PI/boqianpy/App/share_data/fangwenyu/eggnog_seawater/ --override --evalue 0.00001 --cpu 0
srun: error: hhnode-ib-92: tasks 21,32: Exited with exit code 1

**Comment by Cantalapiedra** [comment]
Hi @Ben-41 ,

Does this happen if you change the `-o` option to `--output_dir` ?

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.10#output-options

Best,
Carlos

**Comment by Cantalapiedra** [comment]
Does this directory `/scratch/PI/boqianpy/App/share_data/fangwenyu/eggnog_seawater/` exist?

**Comment by Ben-41** [comment]
Yes!

**Comment by Cantalapiedra** [comment]
It can be seen (i.e. is it mounted) from a slurm job?
Maybe you could test something like `srun ls /scratch/PI/boqianpy/App/share_data/fangwenyu/eggnog_seawater`

**Comment by Ben-41** [comment]
after I run the command, error exist:
srun: error: Unable to allocate resources: No partition specified or system default partition

**Comment by Cantalapiedra** [comment]
I don't know which are the partitions available in your slurm configuration.
I guess you need to specify one with `srun -p PARTITION_NAME ls ...`

**Comment by Cantalapiedra** [comment]
Another test you could do, is check if it is working from another mount point, for instance from your home folder. Something like:

```
outfile="~/emapper_test/"
mkdir "${outfile}"
emapper.py -m diamond --itype metagenome -i $infile -o seawater_out --output_dir $outfile --override --evalue 0.00001 --cpu 0
```

Is this rising the same error?

**Comment by Ben-41** [comment]
here is the result
`(eggmapper) [wfangab@login-0 eggmapper]$ srun -p cpu ls /scratch/PI/boqianpy/App/share_data/fangwenyu/eggnog_seawater`
seawater_out.emapper.hits

**Comment by Cantalapiedra** [comment]
Also, what happens if you run it without `--override`?

**Comment by Ben-41** [comment]
after I set the output in my own home folder and deleted `--overide`, another error rised:
mapper-2.1.4
emapper.py  -m diamond --itype metagenome -i /scratch/PI/boqianpy/App/share_data/fangwenyu/cd-hit_biofilm/temp/total.fasta -o biofilm_out --output_dir /home/wfangab/result/procedure/eggmapper/emapper_test/ --evalue 0.00001 --cpu 0
[1;33m  /scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/eggnogmapper/bin/diamond blastx -d /scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/db/eggnog_proteins.dmnd -q /scratch/PI/boqianpy/App/share_data/fangwenyu/cd-hit_biofilm/temp/total.fasta --threads 40 -o /home/wfangab/result/procedure/eggmapper/emapper_test/biofilm_out.emapper.hits  --sensitive -e 1e-05 --max-target-seqs 0 --max-hsps 0  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp[0m
Error running diamond: Failed to allocate sufficient memory. Please refer to the manual for instructions on memory usage.
srun: error: hhnode-ib-4: task 10: Exited with exit code 1

but I don't think that true since the SLURM I used should be have enough memory and I also set `--blocksize 1.0`, another error rised:
  emapper-2.1.4
 emapper.py  -m diamond --itype metagenome -i /scratch/PI/boqianpy/App/share_data/fangwenyu/cd-hit_biofilm/temp/total.fasta -o biofilm_out --output_dir /home/wfangab/result/procedure/eggmapper/emapper_test/ --evalue 0.00001 --cpu 0 --block_size 1.0
[1;33m  /scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/eggnogmapper/bin/diamond blastx -d /scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/db/eggnog_proteins.dmnd -q /scratch/PI/boqianpy/App/share_data/fangwenyu/cd-hit_biofilm/temp/total.fasta --threads 40 -o /home/wfangab/result/procedure/eggmapper/emapper_test/biofilm_out.emapper.hits  --sensitive -e 1e-05 --block-size 1.0 --max-target-seqs 0 --max-hsps 0  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp[0m
Error running diamond: Building reference seed array...
srun: error: hhnode-ib-4: task 27: Exited with exit code 1

**Comment by Ben-41** [comment]
I set the output file in my own partition and ran this command :`emapper.py -m diamond --itype metagenome -i $infile -o seawater_out --output_dir $outfile --evalue 0.00001 --dmnd_iterate no --block_size 1.0 --override` 
the same error of  "No such file or directory" raised again:
Traceback (most recent call last):
  File "/home/wfangab/anaconda3/envs/eggmapper/bin/emapper.py", line 706, in <module>
    args.resume, args.override)
  File "/home/wfangab/anaconda3/envs/eggmapper/lib/python3.7/site-packages/eggnogmapper/emapper.py", line 104, in __init__
    silent_rm(pjoin(self.output_dir, outf))
  File "/home/wfangab/anaconda3/envs/eggmapper/lib/python3.7/site-packages/eggnogmapper/common.py", line 304, in silent_rm
    os.remove(f)
FileNotFoundError: [Errno 2] No such file or directory: '/home/wfangab/result/procedure/eggmapper/emapper_test/seawater_out.emapper.hits'

However, I actually find this `seawater_out.emapper.hits` file in my folder.

**Comment by Ben-41** [comment]
yeah, I have 2 versions of eggmapper in the cluster, one is 2.1.4 which was used by some other people in my lab, when I ran 2.1.4, I got the error message of: `Error running diamond: Building reference seed array...`
the other is 2.1.10 which was installed via conda, and the error message was:` FileNotFoundError: [Errno 2] No such file or directory:`
but both versions share the same database which was downloaded previously.

**Comment by Cantalapiedra** [comment]
Hi @Ben-41 ,

You may test a simple python script trying to do what emapper does:

```
import os
f = '/home/wfangab/result/procedure/eggmapper/emapper_test/seawater_out.emapper.hits'
os.remove(f)
```

**Comment by Ben-41** [comment]
Hi, just test that, it works.

**Comment by Cantalapiedra** [comment]
How did you exactly test it? Which commands and running on local or slurm?

**Comment by Ben-41** [comment]
```
import os
f = '/home/wfangab/result/procedure/eggmapper/emapper_test/seawater_out.emapper.hits'
os.remove(f)
```
I test this script using the command on slurm: `python test.py`
and it works and remove the file `seawater_out.emapper.hits`.

**Comment by Cantalapiedra** [comment]
It is super weird xD

Then, I would recommend trying to run first emapper without the --override option. You will need to remove manually the files if you rerun, but at least you should be able to run it.

Once you have run emapper successfully without the --override option, we may come back to use the --override option, to see if we can figure it out.

Sorry, but it is the only advice I can give you at this point, since I cannot reproduce your issue myself.

**Comment by Ben-41** [comment]
Hi Cantalapiedra,

I ran emapper without --override on version 2.1.10 but still got error:

  emapper-2.1.10
 emapper.py  -m diamond --itype metagenome -i /scratch/PI/boqianpy/App/share_data/fangwenyu/cd-hit_seawater/temp/total.fasta -o seawater_out --output_dir /home/wfangab/result/procedure/eggmapper/emapper_test/ --evalue 0.00001 --dmnd_iterate no --block_size 1.0 --cpu 1
[1;33m  /scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/eggnogmapper/bin/diamond blastx -d '/scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/db/eggnog_proteins.dmnd' -q '/scratch/PI/boqianpy/App/share_data/fangwenyu/cd-hit_seawater/temp/total.fasta' --threads 1 -o '/home/wfangab/result/procedure/eggmapper/emapper_test/seawater_out.emapper.hits' --tmpdir '/home/wfangab/result/procedure/eggmapper/emappertmp_dmdn_sj_7eu0t' --sensitive -e 1e-05 --block-size 1.0 --max-target-seqs 0 --max-hsps 0  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp[0m
Error running diamond:   what():  Error closing file /home/wfangab/result/procedure/eggmapper/emappertmp_dmdn_sj_7eu0t/diamond-tmp-Y13TBV
srun: error: hhnode-ib-109: task 15: Exited with exit code 1

**Comment by Cantalapiedra** [comment]
Hi @Ben-41 ,

if you run the diamond outside emapper, is it working?

For instance:

```
/scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/eggnogmapper/bin/diamond blastx -d '/scratch/PI/boqianpy/App/eggnog-mapper-2.1.4/db/eggnog_proteins.dmnd' -q '/scratch/PI/boqianpy/App/share_data/fangwenyu/cd-hit_seawater/temp/total.fasta' --threads 1 -o '/home/wfangab/result/procedure/eggmapper/emapper_test/seawater_out.emapper.hits' --tmpdir '/home/wfangab/result/procedure/eggmapper/emappertmp_dmdn_sj_7eu0t' --sensitive -e 1e-05 --block-size 1.0 --max-target-seqs 0 --max-hsps 0 --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp
```

**Comment by Ben-41** [comment]
Hi @Cantalapiedra,
I still can not solve this problem and I try to use my own laptop to run it, it works, thank you so much for your patient guides.

**Comment by Cantalapiedra** [comment]
Hi @Ben-41 ,

I understand that it is working fine in your laptop?

**Comment by Ben-41** [comment]
Hi @Cantalapiedra,
Yes, it works perfectly in my M1 pro MacBook pro. However, just reminder: after `pip install eggnog-mapper`, I need to install diamond for mac manually to run diamond rather than just use the diamond from emapper because its for linux.

**Comment by Cantalapiedra** [comment]
Glad that is working fine on your laptop. I guess there is something on your cluster that makes it incompatible... sad to not be able to solve it though.

Yes, the bundled software are compiled binaries, so it cannot be used on Windows or Mac.

Best,
Carlos
