### ISSUE TITLE
Too many KO id in one reads in emapper.annotations

### ISSUE THREAD

**Issue by Ben-41** [eggnogdb/eggnog-mapper#452]
Hi,

I want to know in the file emapper.annotations, if a reads corresponds to 3 ko's, for example K1111,K1112,K1113, does it mean that the first K1111 has the lowest e-value?

Yours,
Ben

**Comment by Cantalapiedra** [comment]
Hi @Ben-41 ,

As far as I know, no, there is no meaning in the order of list of KOs. They are retrieved from the OG proteins regardless of the original e-value they had from eggNOG DB annotation.

Best,
Carlos

**Comment by Ben-41** [comment]
Hi @Cantalapiedra，

Get it.
Thank you for your reply.

Regards,
Ben
