### ISSUE TITLE
--excluded_taxa not working

### ISSUE THREAD

**Issue by albidgy** [eggnogdb/eggnog-mapper#457]
Hello,

I'm trying to get annotation file for Viridiplantae (NCBI taxid 33090) excluded Brassicaceae (3700). Command:

download_eggnog_data.py -y
emapper.py -m diamond --itype proteins --translate -i input.fasta -o test --cpu 30 --decorate_gff yes --decorate_gff_ID_field GeneID --go_evidence all --dbmem --tax_scope 33090 --excluded_taxa 3700.

However, there are genes from species from the Brassiacaceae in the results (for example, genes from Arabidopsis thaliana). I can't figure out why this view is not excluded from creating an annotation file. Please advise, thank you.

Example output in test.emapper.annotations:

NODE_4_length_15552_cov_87.286646_g1_i0.p1	__3702.AT3G02260.1__	0.0	9878.0	KOG1776@1|root,KOG1776@2759|Eukaryota,37NYR@33090|Viridiplantae,3G7MS@35493|Streptophyta,3HPWU@3699|Brassicales	33090|Viridiplantae	T	Auxin transport protein	-	GO:0000003,GO:0000902,GO:0003006,GO:0005575,GO:0005622,GO:0005623,GO:0005737,GO:0005829,GO:0005911,GO:0006810,GO:0007275,GO:0008150,GO:0009314,GO:0009416,GO:0009506,GO:0009605,GO:0009607,GO:0009620,GO:0009628,GO:0009639,GO:0009640,GO:0009653,GO:0009719,GO:0009725,GO:0009733,GO:0009791,GO:0009826,GO:0009914,GO:0009926,GO:0009987,GO:0010015,GO:0010016,GO:0010033,GO:0010101,GO:0010102,GO:0010229,GO:0010311,GO:0010817,GO:0016020,GO:0016043,GO:0016049,GO:0022414,GO:0022622,GO:0030054,GO:0032501,GO:0032502,GO:0032989,GO:0040007,GO:0042221,GO:0043207,GO:0044424,GO:0044444,GO:0044464,GO:0048281,GO:0048364,GO:0048367,GO:0048527,GO:0048528,GO:0048589,GO:0048608,GO:0048646,GO:0048731,GO:0048856,GO:0048869,GO:0050896,GO:0051179,GO:0051234,GO:0051704,GO:0051707,GO:0055044,GO:0060560,GO:0060918,GO:0061458,GO:0065007,GO:0065008,GO:0071840,GO:0090567,GO:0090696,GO:0090697,GO:0090698,GO:0099402,GO:1905392,GO:1905393	2.3.2.27	ko:K10691	ko05165,ko05203,map05165,map05203	-	-	-	ko00000,ko00001,ko01000,ko04121	-	-	-	E3_UbLigase_R4,ZZ

**Comment by Cantalapiedra** [comment]
Dear @albidgy ,

`--excluded_taxa` doesn't work during the search step (diamond). To limit the results from diamond to specific taxa you may need to build a custom diamond database. One way to do may be using https://github.com/eggnogdb/eggnog-mapper/blob/master/create_dbs.py

`--excluded_taxa` works only during the annotation stage, as described here:

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.10#user-content-Annotation_Options

I hope this is of help.

Best,
Carlos

**Comment by albidgy** [comment]
Thank you!
