### ISSUE TITLE
get parent og from og

### ISSUE THREAD

**Issue by matthpich** [eggnogdb/eggnog-mapper#460]
Hi,
There used to be ways to identify parent og from og ids through sqlite3 tables.
Could you tell me where to find this information?
I am using emapperdb version 5.0.2.
Many thanks for your help.
Best,
Matthieu

**Comment by Cantalapiedra** [comment]
Hi, 

I would say there is no way to do such mapping using eggnog-mapper database 5.0.2.
You may try using the OG ID to retrieve the OGs to which the same protein belongs to, which should contain (all?) the parents:

`select ogs from prots where ogs LIKE '%2VK9J@28216%'`

But I am afraid you won't know which are parents and children unless you use NCBI taxonomy to parse the results.

Best,
Carlos

**Comment by matthpich** [comment]
Thanks for sharing this great idea Carlos.

**Comment by matthpich** [comment]
Carlos's answer answers the question.
