### ISSUE TITLE
Problems about using eggNOG-mapper web

### ISSUE THREAD

**Issue by YueeeXiao** [eggnogdb/eggnog-mapper#465]
Hi, I am writing because I found problems in uploading data on eggNOG-mapper. 

After I clicked "Submit", the webpage appeared like this:
![微信截图_20230518140625](https://github.com/eggnogdb/eggnog-mapper/assets/133945918/4ece17bd-b41a-4101-a1e9-49eeeebb644f)

I have tried several times but failed to submit my sequences and perform the analysis. Also, I did not see anything in the section of Server Status. I had used eggNOG-mapper on Monday this week and it worked well. 

I wonder if something goes wrong and when can I use it to do functional annotation again.

Thank you very much and looking forward to your reply.

**Comment by Cantalapiedra** [comment]
Hi @YueeeXiao ,

Thank you very much for reporting this. It is very important to us, to be able to fix it as soon as possible.
Hopefully, it should be working fine right now.

Best,
Carlos

**Comment by YueeeXiao** [comment]
Hi @Cantalapiedra ,

Thank you so much for your reply. I have tried and it is working fine now :)

Best,
Yue

**Comment by Cantalapiedra** [comment]
Thank you for confirming!
Best,
Carlos
