### ISSUE TITLE
problem running emapper.py

### ISSUE THREAD

**Issue by yeon-y** [eggnogdb/eggnog-mapper#472]
Hello,

1. I seem to have problem running emapper.py from conda.
I've downloaded databases using download_eggnog_data.py and accepting downloads.
`download_eggnog_data.py -P -M -H`
Also I created db.
`create_dbs.py -m diamond --dbname bacteria --taxa Bacteria`

I have a wholegenome sequence FASTA file(7659kb) of some bacteria. I'm trying this line:
`emapper.py --cpu 15 --itype genome -m diamond --genepred prodigal -i wgs.fasta --output_dir ~/data/ -o test`

After run this code, I get the emaooertemp_prod folder.
Then this line in yellow color on the screen:
` /home/~/diamond blastp -d /home/~/data/eggnog_proteins.dmnd -q /home/~/data/emappertmp_prod_z5dkw5sn/output.faa --threads 15 -o /home/~/data/test.emapper.hits  --sensitive -e 0.001 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp`

Nothing seems to happen then. The .hits file and temp folder are indeed created, but nothing writes to it.
I've been waiting for an 2hours. I'm not sure if it's working . . .

I checked emapper version : emapper-2.1.3.

Am I missing something obvious?
I saw a similar question post, but I didn't know if I should wait a few more hours or if there was a problem with how to do it, so I asked for help.

Is there any way of running emapper?

Thanks!

**Comment by yeon-y** [comment]
I'm sorry.
I waited 3 hours and it was solved.
Just in case anyone experiences a similar situation, I won't delete the post!

**Comment by Cantalapiedra** [comment]
Thank you for reporting back.

**Comment by hellopeccat** [comment]
> I'm sorry. I waited 3 hours and it was solved. Just in case anyone experiences a similar situation, I won't delete the post!

Hi there,

I also encountered the same problem but with default cpu of 1. When I change it to 20, anything works well. 

However your thread is set as 15, close to mine, I am curious about what's actually wrong with your running and rendered you waiting for 3 hours.

Best.
