### ISSUE TITLE
Issue when using mmseqs instead of diamond: "Error running 'mmseqs search': - Aminoacid"

### ISSUE THREAD

**Issue by plaquette** [eggnogdb/eggnog-mapper#479]
hey!
 thank you for the mapper!
 
 
 I have problems, if i try to use it with mmseqs (it works fine with diamond) - i run it like this:

``` bash
emapper.py \
--override \
-i in.fasta \
-m mmseqs \
--mmseqs_db ..path_to/get_db/eggnog-mapper-data/bacteria.mmseqs \
--itype proteins \
-o out \
--data_dir ..path_to/get_db/eggnog-mapper-data
```

on a input like this:

```
>ERS990587|ERS990587_08430
MQAVKKIILSETFPGILLIFFTLLALLFKNSSLSVIYTDFFHANFTIGFDHFQIAKSLDLWINDGLIAIFFLCIGLELKYEILRGQLKNIRSVSLPIFGALGGMIVPALIFSAINYSHEFAMKGWAIPTATDIAFAVGILMLLGNKIPSSLKLFLLSLAIFDDLGAIIIIALFYTDQLSTLAIIVCLLCVFILFVLNYFHVTHLPLYVLVGVVLWIAMLKSGVHATLAGVIIALFIPLDTKNKKPYLHEVHKDLNPWVVYFILPLFAFANAGIDLRDMHFESIVSPVSMGIMLGLFLGKQLGVFGFCYLAIKLKLAKLPENIKYKKFYGICILTGIGFTMSLFIDGLAYKNSNIFEHADKLAILIASFLSAIVGFIYLKIVK
>ERS990617|ERS990617_01095
MQAVKKIILSETFPGILLIFFTLLALLFKNSSLSVIYTDFFHANFTIGFDHFQIAKSLDLWINDGLIAIFFLCIGLELKYEILRGQLKNIRSVSLPIFGALGGMIVPALIFSAINYSHEFAMKGWAIPTATDIAFAVGILMLLGNRIPSSLKLFLLSLAIFDDLGAIVIIALFYTDQLSALAIIICLFCIFALLLLNYYHITHLSLYVLVGVVLWIAMLKSGVHATLAGVIIALFIPLDTKNKKPYLHEVHKDLNPWVVYFILPLFAFANAGIDLRDMHLGSVFSPVSLGIILGLFLGKQLGVFGFCYLAIKLKLAKLPENIKYGKFYGICILTGIGFTMSLFIDGLAYKNSDIFEYADKLAILVASFLSAIVGFIYLKIIK

```

but it fails always with this error:

`Error running 'mmseqs search': - Aminoacid`

and i can not figure out what causes this.

I build the bacteria database and the mmseqs-index as described in the wiki.

Would be amazing if you could help me fix this. 

Thank you!

Best,

j.

**Comment by Dr-Doomhammer** [comment]
Hi, I encounted this issue, too. Could you please tell me how to fix this?

**Comment by Dr-Doomhammer** [comment]
> can be closed, was a fault on my end.
Hi, I encounted this issue, too. Could you please tell me how to fix this?

**Comment by mchenaux** [comment]
@plaquette  or @Dr-Doomhammer, I am also seeing this, but don't know what the issue is. How did you solve this?

**Comment by Dr-Doomhammer** [comment]
> [@plaquette](https://github.com/plaquette) or [@Dr-Doomhammer](https://github.com/Dr-Doomhammer), I am also seeing this, but don't know what the issue is. How did you solve this?

Still unsolved.

**Comment by plaquette** [comment]
sorry - i completely missed the notifications

i'll try to look into it next week and reverse engineer what i did 🫣

Dr-Doomhammer ***@***.***> schrieb am Sa. 23. Aug. 2025 um
09:39:

**Comment by rockseworia** [comment]
Hey, I’m running into the same issue — has anyone figured out a solution yet?

**Comment by mchenaux** [comment]
@rockseworia For me it turned out to be an issue downloading completely. The connection from my server kept dropping; I ultimately downloaded locally and then uploaded to the server, which was a ridiculous workaround.

**Comment by rockseworia** [comment]
@mchenaux Thanks for your reply, I just ran using diamond, hope it won't be too slow,i'll try upload mmseqs later.
