### ISSUE TITLE
Error: annotation went wrong for pfam alignment in parallel

### ISSUE THREAD

**Issue by zhaoc1** [eggnogdb/eggnog-mapper#482]
Hi,

Here is my emapper command: 
```
emapper.py -i centroids.ffn --itype CDS -m diamond --sensmode more-sensitive --data_dir eggnog_data  --cpu 10 --output batch_18 --override --dbmem --pfam_realign realign --temp_dir temp/ --output_dir output
```

I got an error message like the following:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/czhao/miniconda3/envs/geneannot/lib/python3.11/site-packages/eggnogmapper/annotation/pfam/pfam_scan.py", line 24, in pfam_align_parallel_scan
    for alignments in pool.imap(query_pfam_annotate_scan,
  File "/opt/czhao/miniconda3/envs/geneannot/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
ValueError: Error parsing fasta file. GUT_GENOME287165_01908 has no sequence
```

I doubled check the input `centroids.ffn` is valid FASTA and GUT_GENOME287165_01908 does have sequences in the input FASTA. So the error message seems to indicate missing sequences for GUT_GENOME287165_01908 at some intermediate steps. Any ideas what's going on here? Thank you!

Chunyu

**Comment by Cantalapiedra** [comment]
Hi @zhaoc1 ,

I am not able to reproduce the error. You may share your fasta file with me by email or link, if it isn't very large.

Best,
Carlos

**Comment by zhaoc1** [comment]
Hi Carlos,

Thanks for the reply. The original input `centroids.ffn` was multiple FASTA catted into one file. I tried to rerun eggnog with individual FASTAs instead, and I no longer encountered the same problem 🤔

Anyway, I am closing this issue now. 

Chunyu

**Comment by Cantalapiedra** [comment]
Hi @zhaoc1 ,

Thank you very much for your feedback.

Best,
Carlos

**Comment by zhaoc1** [comment]
Actually, I located the problem FASTA input (attached). I also attached the GNU Time log file. 

[centroids.ffn.zip](https://github.com/eggnogdb/eggnog-mapper/files/12820714/centroids.ffn.zip)

[eggnog.log](https://github.com/eggnogdb/eggnog-mapper/files/12820716/eggnog.log)

**Comment by Cantalapiedra** [comment]
My guess is that this sequence is not detected as CDS, because it doesn't start with ATG:

>GUT_GENOME287165_01908
TGA...

So the CDS will be empty. You could try using a different translation table, or translating them yourself to proteins and using --itype protein. I am not sure if UGA is a start codon anywhere...

Best,
Carlos

**Comment by zhaoc1** [comment]
It makes sense. Looking back to the prokka annotation of "GUT_GENOME287165_01908", it is "23S ribosomal RNA (partial)". Thanks Carlos.

**Comment by Cantalapiedra** [comment]
Ah if it is a rRNA it makes sense yes.
We should add code that checks whether the CDS are non-empty.
Sorry for the inconveniences.
Best,
Carlos
