### ISSUE TITLE
Are the online resources down?

### ISSUE THREAD

**Issue by adrienchaton** [eggnogdb/eggnog-mapper#488]
Hi and thanks for the great work.
I wanted to look more into the data and try the webserver, however over the last days I cant seem to be able to connect to the EMBL hosted services:

- https://eggnog-mapper.embl.de/

- https://eggnog5.embl.de/

Am I using wrong links please? Or will these services be resumed in the near future please?

**Comment by adrienchaton** [comment]
sorry, it seems there was a proxy issue on my side and the websites were actually up and running

**Comment by Cantalapiedra** [comment]
Anyway, thank you for warning us. It is very valuable when it actually happens. 

Best,
Carlos
