### ISSUE TITLE
How to change the diamond software path that mapper.py runs?

### ISSUE THREAD

**Issue by mondayz11** [eggnogdb/eggnog-mapper#490]
Because I installed a diamond software on the local server, when I installed egg-nog with conda, I installed a diamond. Every time I ran emapper.py with conda, I retrieved another diamond. I wanted to retrieve the diamon under conda. Could you tell me how to modify should be? Or what parameters can be used? thank you.
I am currently using emapper software version 2.1.12, if I call another diamond software, the Error is Error running diamond: Error: Invalid option: iterate

**Comment by Cantalapiedra** [comment]
Hi @mondayz11 ,

Could you show me how your conda environment and your environment variable PATH look like?

Best,
Carlos

**Comment by mondayz11** [comment]
> 你好@mondayz11,
> 
> 你能告诉我你的 conda 环境和环境变量 PATH 是什么样的吗？
> 
> 最好的， 卡洛斯

my bro,I have already solved the problem. I found out that it was calling the software under the global variable, while I ran it using the path. It defaulted to the global variable directly, so I just needed to make a slight modification. Thank you for your response, and I wish you all the best.
