### ISSUE TITLE
Server Down

### ISSUE THREAD

**Issue by KyleMondron** [eggnogdb/eggnog-mapper#496]
Hello, it appears that the eggnog-mapper.embl.de website is down. You may already know this and be working on a solution. I believe this is on the side of the server, rather than a local issue as all other webpages I try to open are successful. 

Let me know if I can provide any other information.

**Comment by KyleMondron** [comment]
This appears to have been resolved, as the website is functional once more.

**Comment by Cantalapiedra** [comment]
Hi @KyleMondron ,

Sorry for answering sooo late. Thank you for reporting this. It is always useful to have this kind of notifications (even when we don't properly answer in time).

Best,
Carlos
