### ISSUE TITLE
Question about KEGG_pathway result 

### ISSUE THREAD

**Issue by HuangLoong** [eggnogdb/eggnog-mapper#502]
I obtained the KEGG pathway results using standard procedures. However, why did the result file contain two types of exactly the same pathway information, but identified by koxxxxx and mapxxxxx respectively? For example, ko00010 and map00010.
![image](https://github.com/eggnogdb/eggnog-mapper/assets/162462313/db7768b5-82a9-4807-a9c5-7c8d5fecafa7)
![image](https://github.com/eggnogdb/eggnog-mapper/assets/162462313/0676a4c8-e619-44cb-b706-f715b65a7448)

**Comment by Cantalapiedra** [comment]
Dear @HuangLoong ,

To me, if this is an issue, it would be a KEGG issue?

https://www.genome.jp/dbget-bin/www_bget?pathway+ko00010
https://www.genome.jp/dbget-bin/www_bget?map00010

Best,
Carlos
