### ISSUE TITLE
Mapping eggnog with other annotations

### ISSUE THREAD

**Issue by matthpich** [eggnogdb/eggnog-mapper#503]
Hi,
Not an issue but Is the mapping between eggnogs and other annotations available somewhere?
Many thanks!

**Comment by matthpich** [comment]
Found it in data/eggnog.db:

SELECT pname, gos, kegg_ec, kegg_ko, kegg_pathway, kegg_module, kegg_reaction, kegg_rclass, kegg_brite, kegg_tc, kegg_cazy, bigg_reaction, pfam FROM prots

**Comment by Cantalapiedra** [comment]
Dear @matthpich ,

Glad that you found what you were looking for. Note that most of this information should be also available at http://eggnog5.embl.de/#/app/downloads

Best,
Carlos
