### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by linruoran1999** [eggnogdb/eggnog-mapper#509]
http://eggnog-mapper.embl.de/ cannot open.

**Comment by xiefumin1** [comment]
I have meet the same situation now

**Comment by peterthorpe5** [comment]
Me too. Is the server down or has this wonderful service stopped?

**Comment by Jenifferbio** [comment]
I just sent a support request in the contact field https://www.embl.org/sites/heidelberg/. I've been seeing this error for days

**Comment by Cantalapiedra** [comment]
#506

**Comment by Cantalapiedra** [comment]
Thank you very much for reporting this and for your patience

**Comment by Emberhaha** [comment]
http://eggnog-mapper.embl.de/ cannot open. it shows 502 bad gateway again.

**Comment by Cantalapiedra** [comment]
Hi @Emberhaha ,

Thank you for reporting this! Please, follow updates on this here #511

**Comment by Emberhaha** [comment]
> Hi [@Emberhaha](https://github.com/Emberhaha) ,
> 
> Thank you for reporting this! Please, follow updates on this here [#511](https://github.com/eggnogdb/eggnog-mapper/issues/511)

Do you have any idea when it will be fixed? I have some urgent use for this site. Thank you very much!

**Comment by Liang-1103** [comment]
http://eggnog-mapper.embl.de/ cannot open. It showed 502 Bad Gateway.

**Comment by Cantalapiedra** [comment]
#511

**Comment by basilmars** [comment]
Same proplem. Help, please!

**Comment by Liny2333** [comment]
I have meet the same problem , help please

**Comment by Cantalapiedra** [comment]
Please, follow issue #511 for updates
