### ISSUE TITLE
Please consider distributing gzipped HMMs

### ISSUE THREAD

**Issue by bachev** [eggnogdb/eggnog-mapper#59]
Hi there,

could you please consider, for the next release, distributing gzipped HMM files and have your download script unzip them locally? A quick test with gzip -9 and the bact_50 database files reduced them from 26 GiB to 12 GiB, which is quite substantial, especially when all you have is a 200 KiB/s line.

Thanks,
  Bastien

**Comment by jhcepas** [comment]
we will, thanks
