### ISSUE TITLE
six frame translation of nucleotide sequences

### ISSUE THREAD

**Issue by alicedb2** [eggnogdb/eggnog-mapper#75]
When feeding nucleotide sequences to emapper.py, the --translate argument propagates to eggnogmapper/seqio.py but only yields
```
prot = Seq(full_seq, generic_dna).translate(to_stop=True)
```
once per fasta entry.

Would be useful to allow for the yielding of all 6 frames
```
Seq([...]).translate([...])
Seq([...])[1:-2].translate([...])
Seq([...])[2:-1].translate([...])
Seq([...]).reverse_complement().translate([...])
Seq([...]).reverse_complement()[1:-2].translate([...])
Seq([...]).reverse_complement()[2:-1].translate([...])
```
in case one is feeding emapper, say, the nucleotide sequence of a whole genome. It might also mean setting `to_stop=False` and to further split Seq on `*` and add a suffix to `seq_name` specifying the frame (1 to 6) and the start-stop position of the split.

This would basically mimick an esl-translate (from the HMMER/Easel suite) preprocessing step.

**Comment by Cantalapiedra** [comment]
Hopefully, diamond and mmseqs "blastx" searches will address this issue.
Please, re-open or re-issue if needed.
