### ISSUE TITLE
--cpu doesn't prevent phmmer's default behavior from saturating multicore machines

### ISSUE THREAD

**Issue by alicedb2** [eggnogdb/eggnog-mapper#76]
During the refinement stage, the --cpu X argument is used to start X phmmer processes, but phmmer's own --cpu argument is left unspecified. By default phmmer will use all available cores and X such instances will together saturate all cpus!

I think a quick fix would be to use phmmer --cpu 1, but I'm unsure if it'd be consistent with all use cases.

**Comment by jhcepas** [comment]
parallelization is per phmmer process.
I remember doing some tests and seeing that 10 parallel phmmer processes were faster than ten times phmmer --cpu 10.

**Comment by alicedb2** [comment]
What I'm trying to say is that emapper starts phmmer without --cpu argument and by default, if left unspecified, phmmer will try to use all available cores. Therefore when you call emapper --cpu 10, emapper creates 10 phmmer processes (expected) but each one of these processes tries to use as many cores as possible (unexpected), which can be anything from 1 to 6 depending on the machine's IO capacity.

On our 64 cores server almost all 64 cores end up being utilized even though eggnog was called with emapper --cpu 10. Starting 10 phmmer processes with phmmer --cpu 1 would fix this behavior.

**Comment by jhcepas** [comment]
Sorry, I misunderstood the problem. In that case you are right, we should force --cpu 1 in `phmmer`. Thanks for reporting it.

**Comment by Cantalapiedra** [comment]
If I am not wrong, this should be fixed in current versions.
