### ISSUE TITLE
make emapper.py compatible with python3

### ISSUE THREAD

**Issue by ShaiberAlon** [eggnogdb/eggnog-mapper#78]
Hi, would you consider making changes to `emapper.py` so that it would be compatible with both python 2.7 and python 3?

**Comment by jhcepas** [comment]
sure. I just didn't have time to make the conversion, but PR are welcome
thanks!

**Comment by ShaiberAlon** [comment]
I would be happy to give it a try in the near future.

Thank you,

Alon

**Comment by MrTomRod** [comment]
What is the status of the Python3-Port? Is [refactor branch 2.0.2](https://github.com/eggnogdb/eggnog-mapper/releases/tag/2.0.2-rf1) functional?

**Comment by Cantalapiedra** [comment]
It is not functional yet. Hopefully it will be soon. Sorry for the inconveniences.

**Comment by Cantalapiedra** [comment]
The refactor branch is currently functional and it should be fully python3
