### ISSUE TITLE
Add protein prediction step 

### ISSUE THREAD

**Issue by cuencam** [eggnogdb/eggnog-mapper#96]
Hi Jaime,

I was sharing the software with some wet-lab biologist, and they were stuck on the protein prediction phase. Would it be possible to integrate prodigal or any other protein prediction step as a pre-procesing step so less computational people can use it easily? 
Miguel

**Comment by cuencam** [comment]
I forgot to say that I am referring to the webserver, not to eggnog-mapper itself

**Comment by jhcepas** [comment]
thanks, it would be a nice addon, but not sure how difficult to implement
and maintain.
Also, worried about performance. how long does it take a typical prodigal
run with your datasets?

**Comment by cuencam** [comment]
Hi!

The people that I just talked to annotate one bacterial / phage genome at a time (so between 10 kb to 5 Mb), so I would expect that this would not take very long (a phage is one min max)

**Comment by Cantalapiedra** [comment]
It should be already working in the "refactor" branch.
Thank you.
Carlos
