### ISSUE TITLE
struct.error: unpack requires a string argument of length 72

### ISSUE THREAD

**Issue by davidbio** [eggnogdb/eggnog-mapper#99]
I was trying to run emapper.py locally and installed the NOG database.
First I ran:
`eggnog-mapper-1.0.3/emapper.py -i ../genes_fgs.fasta.faa -o . -d NOG --override --cpu 32`
After realizing that the machine was practically idling (load ~ 1), I thought --usemem would help.
But this brought me the following stacktrace:
```
#  emapper-1.0.3
# ./emapper.py  -i ../genes_fgs.fasta.faa -o . -d NOG --override --cpu 32 --usemem
eggnog-mapper-1.0.3/data/hmmdb_levels/NOG_hmm/NOG_hmm.all_hmm
Loading server at localhost, port 51700-51701
Waiting for server to become ready... localhost 51700
<omitted>
Reading idmap /mnt/d3/eggnog-mapper-1.0.3/data/hmmdb_levels/NOG_hmm/NOG_hmm.all_hmm.idmap
190648 names loaded
Sequence mapping starts now!
Traceback (most recent call last):
  File "/mnt/d3/eggnog-mapper-1.0.3/emapper.py", line 1001, in <module>
    main(args)
  File "/mnt/d3/eggnog-mapper-1.0.3/emapper.py", line 222, in main
    dump_hmm_matches(args.input, hmm_hits_file, dbpath, port, scantype, idmap, args)
  File "/mnt/d3/eggnog-mapper-1.0.3/emapper.py", line 397, in dump_hmm_matches
    base_tempdir=args.temp_dir)):
  File "/mnt/d3/eggnog-mapper-1.0.3/eggnogmapper/search.py", line 179, in iter_seq_hits
    fixed_Z=fixed_Z)
  File "/mnt/d3/eggnog-mapper-1.0.3/eggnogmapper/search.py", line 87, in scan_hits
    dom = struct.unpack("4i 5f 4x d 2i Q 8x" * ndom, dombit)
struct.error: unpack requires a string argument of length 72
```

The machine has 32 cores and 245 GB RAM.
Any thoughts on this?

**Comment by jhcepas** [comment]
I never found this error. It seems to be related with the specific result that HMMER is producing for a given query sequence. Could you try to isolate that sequence?  (I guess you already checked that your input file is a normal fasta file with protein sequences. i.e. no empty sequences, no weird chars, etc.)

**Comment by davidbio** [comment]
Thanks for replying.
I ran the same command without usemem again on a smaller data-set (250 protein sequences) and it went through. Trying with usemem gave me the same problem as before, so I modified search.py:
```
line 87: print len(dombit)
line 88: dom = struct.unpack("4i 5f 4x d 2i Q 8x" * ndom, dombit)
```
Which gives me the following:
```
Reading idmap /mnt/d3/eggnog-mapper-1.0.3/data/hmmdb_levels/NOG_hmm/NOG_hmm.all_hmm.idmap
190648 names loaded
Sequence mapping starts now!
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
72
0
Traceback (most recent call last):
  File "/mnt/d3/eggnog-mapper-1.0.3/emapper.py", line 1001, in <module>
    main(args)
  File "/mnt/d3/eggnog-mapper-1.0.3/emapper.py", line 222, in main
    dump_hmm_matches(args.input, hmm_hits_file, dbpath, port, scantype, idmap, args)
  File "/mnt/d3/eggnog-mapper-1.0.3/emapper.py", line 397, in dump_hmm_matches
    base_tempdir=args.temp_dir)):
  File "/mnt/d3/eggnog-mapper-1.0.3/eggnogmapper/search.py", line 180, in iter_seq_hits
    fixed_Z=fixed_Z)
  File "/mnt/d3/eggnog-mapper-1.0.3/eggnogmapper/search.py", line 88, in scan_hits
    dom = struct.unpack("4i 5f 4x d 2i Q 8x" * ndom, dombit)
struct.error: unpack requires a string argument of length 72
```
Without usemem, the additional print is not visible in the console, which makes me think that other classes may be used instead. This seems to be a problem with search.py, rather than with my data.
This is head -n10 of the fasta file I use:
```
>NODE_1_length_398483_cov_53.519999_197_670_+
MLHIVLYQPEIPPNTGNVIRLCANTGYQLHLIEPLGFDLEDKKLRRAGLDYHEFARLKRYPDFQAFVDQNDIGTIYALTTKGSRPHSEAAFKANDVLVFGPETRGLPAEFIEALPKEQRLRLPMQANSRSLNLSNTVAVMVYESWRQLGYQMPAGEQ
>NODE_2_length_214486_cov_22.250449_1_620_-
MENLSLQMNNKDDLNTLFSLLIDVKIAELELAQNSFYIKNSQINIRNKKSEYKAGELDISDLNDAIMTRNQLSDKRKELELSKLITLNSIKKYSNKKHETINIPNVKLMSKDIYLQNASSLKYAKLDIDVNNSLYKIKKSDYLPSLSVTGKYGYKETSLVDGDNYYSYGLNVSMPLNFSSSSDIEQTKINYLISQKELSDELINSE
>NODE_3_length_199526_cov_49.238526_1_818_+
SSGIVAAVSSYLAEHDCYISEMHQFDDEESNRFFMRAECRIEGGAQSIASVRDGFAAQVTRFNMDWEILDKSKPVKVLFMVSKFDHCLDDLLYRHRKGELSMEITAVVSNHRDLRPMVEREGIRFVHLPVTKDNKAEQEKALLNIIDETNTDLVVLARYMQILSDSLCKKLHGRAINIHHSFLPGFKGAKPYHQAHERGVKLIGATAHYVTSDLDEGPIIEQSVQPVNHTYSPERLVAIGRDTETVALATAVRMHLEHRVFMYGNKTVVFK
>NODE_4_length_166172_cov_40.777729_203_1249_+
MSELFDKVALRATVQQHLSAAEKSLESPALDNDALREEIKTLLKQKNAVLVAHYYTDDAIQELAEETGGVIADSLEMARFGANHEAETLVVAGVKFMGETAKILSPEKTILMPTLEATCSLDIGCPIDDFSAFCDQYPDRKVVVYANTSAAVKARADWVVTSSIALDVVNHLNDMGEKIIWAPDQHLGGYIQRETGADMILWDGACIVHEEFKAKGILDLKSIYPDAAVLVHPESPEPVVEVADVVGSTSQLLKASKEMSNETFIVATDRGIFYKMKQASPGKRFVEAPTAGSGANCRSCAHCPWMALNSLELLRNALRDGTDEIFVAEETRAKALIPLQRMLDFQVS
>NODE_5_length_156904_cov_18.848338_1_1421_+
QEQVMQIVQVIGGFSLGGADLVRRAMGKKIVEEMDRLKGEFADGGVKKGYNKQHCEELFDLIVKFAGYGFNKSHSAAYALVTFYTSYLKCYYPTEFMASLLTLEKDNTDKVVKYVDEVKRMGYDLVPPDINKSYLVFSADTLEDEREVVLFGMGALKGAGDVAINSIIASREEGEFADLSDFVSRIDSSKVNKRVIETLIKSGAFDKFGYTRKALLMQIEDIVETAGKAAQAKKQAVGSLFGDDEDMIKIDISLNDMPEYDDKEILEFEKASLGFYVSGHPLDEFRETLDEIKYTLSSEIDTLADGSEALLVGKIEAIIEKVSKKGNKFGIATIMDLHGSIELMLFEDRIKELREDFDLTKPIAFKVGVKIDDFGTKFSLKKIESLKEAKTEKLKKGKKVEKVQAPLNVAIEFSEDDKIIYALFNIISQNQGKREVTLTIKSKLGDVELDSGYYVNNNVEGLLKELPGVYVS
```

**Comment by jhcepas** [comment]
could you send your 250 seq dataset? I would need to test locally to check what could be happening...

**Comment by davidbio** [comment]
Anything else you would need to know?
[genes_fgs_500.fasta.txt](https://github.com/jhcepas/eggnog-mapper/files/2254391/genes_fgs_500.fasta.txt)

**Comment by davidbio** [comment]
Maybe there is something wrong with my hmmer installation in general?
A test with diamond finished after 50 minutes (500000), whereas the test with hmmer is still running (2 whole days). Also, the CPU load with hmmer is really low, it's close to 1, although I use -cpu 32.
Then again hmmer finished with the small example data-set I sent you earlier.

**Comment by jhcepas** [comment]
diamond is general the best way to go for large datasets. hmmer is substantially slower and and in all our tests the quality of predictions was very similar. 
could you check if your test genes run ok using the online eggnog-mapper tool using euk or bact databases? If so, the problem should be on your hmmer installation.

**Comment by davidbio** [comment]
My data is analyzed just fine through the webpage. I just reinstalled emapper and will give it another try during the weekend.
Thanks for your efforts.

**Comment by CatKucha** [comment]
Hi, I met the same problem. But it seems I find a solution. I got the solution from this page [http://www.chenlianfu.com/?p=2804](url) . It is said to add eggnog-mapper to the $PATH. I did like this and it really worked, although I don't know why it can solve this problem.

> export PATH=/opt/biosoft/eggnog-mapper-1.0.3/bin/:$PATH
